### ISSUE TITLE
Netdata uninstall does not recognize netdata

### ISSUE THREAD

**Issue by deedeefink** [TechPerplexed/Gooby#10]
1st of all thanks for the progress.

I installed Netdata via GooPlex version 1.1.1 and wanted to test the Remove function (D,A,R), but it returned "Netdata is not installed yet"

**Comment by deedeefink** [comment]
You can close the ticket.
For other reasons I decided to reinstall the complete OS. In the process I though discovered that there is a difference in the netdata install depending on wether you use the "apt install netdata" or the "bash <(curl -Ss https://my-netdata.io/kickstart.sh)". It seems that the bash script provides a more complete install in terms of active plugins. Ie. sensors, fail2ban and nginx (given that these are installed)

**Comment by TechPerplexed** [comment]
Perfect, thanks for letting me know!
