### ISSUE TITLE
Radarr4k Container Unhealthy

### ISSUE THREAD

**Issue by mr-handerson** [TechPerplexed/Gooby#100]
Looking for some help here, I don't know why or how to correct what is causing the health check to fail (or if it even matters, other thank being irksome).

Installed radarr4k using the preconfig yaml
Tried using the default image and also the linuxserver version, same result
Everything seems to work, but it fails the health check and therefore the container shows up as unhealthy
Health check is failing per

netstat -ntlp | grep :7879 && mountpoint /Media
tcp6       0      0 :::7879                 :::*                    LISTEN      10710/docker-proxy
mountpoint: /Media: No such file or directory

However, /Media is accessible because I could import existing movies and have been able to add, download and transfer new movies.

Have also done a System Cleanup, but haven't tried a server restart

**Comment by TechPerplexed** [comment]
Oh I'll flag @bdschuster because he recently made changes to the "main" Radarr container - I wonder if that might be the issue. To be continued :)

**Comment by bdschuster** [comment]
Ok, should have fixed it. You will have to remove the yaml, run system cleanup so that it updates gooby, then copy the yaml back over and test. Let me know if you need more specifics and if it works.

**Comment by mr-handerson** [comment]
Fixed, thanks! I updated the yaml in place with your change (assuming that means the check has to work on the external port for the app and not the container custom port), did a system cleanup and everything is now showing as healthy.

I'll go ahead and close this.

**Comment by bdschuster** [comment]
Glad it worked for you! Oh, and congrats on being the 100th issue!! LOL

**Comment by mr-handerson** [comment]
Thanks haha, I noticed the milestone. ^_^ Although with only 76 closed I assume some were deleted/merged/invalid so perhaps there's a ways to go yet...? ¯\_(ツ)_/¯

**Comment by TechPerplexed** [comment]
Haha no never deleted anything, not merged, so I assume GitHub just cannot count :D

**Comment by bdschuster** [comment]
@TechPerplexed Probably changing them to feature requests or something? I dunno, maybe they can't count...lol

**Comment by mr-handerson** [comment]
It seems that anything was labelled doesn't show in the default count. All the issues that had a label attached account for the missing 24. So this was the actual 100th. And 0 open, great support and development!

**Comment by bdschuster** [comment]
@mr-handerson , nice find! And thanks, @TechPerplexed and I try :-)
