### ISSUE TITLE
System cleanup already running?

### ISSUE THREAD

**Issue by ffwjb** [TechPerplexed/Gooby#101]
Hello, 

First I'd want to thank you for this fantastic program!

When I preform a system cleanup, it only run's once, when I want to run it again it returns to the menu without preforming a cleanup. I have to reboot the server to get it running again. When I scroll up I see the message 24220 already running.

any ideas? system is up to date, I'm running a debian install.

**Comment by TechPerplexed** [comment]
Hmm so when you run a system cleanup from the menu, does it finish at some point and go back to the menu again?

**Comment by bdschuster** [comment]
Also, what user are you running this with? Root? Or did u create a separate user?

**Comment by ffwjb** [comment]
Yes when I run it the first time it finishes and returns to the menu, buy if I want to run it again it just returns to the menu.

I never had this problem before, I run it from a separate user.

**Comment by TechPerplexed** [comment]
Yeah it doesn't ring a bell for me either, I can't even think of what it might be. It seems like the process never finishes (hence the message it's already running), but in that case it shouldn't go back to the menu either.

Can you try just to run rclean separately (not from the menu) after a reboot and see if it gets stuck somewhere?

**Comment by ffwjb** [comment]
Just tried it again and there was a little update of docker. It seems to be working just fine again.
Thank you for your reaction

**Comment by TechPerplexed** [comment]
Glad it got sorted :)
