### ISSUE TITLE
Issues updating Rclone config

### ISSUE THREAD

**Issue by bifa2** [TechPerplexed/Gooby#102]
Hi,

I just ran through the wizard to update my rclone config (to use my own client id and secret) and as far as I can tell, the config file is updated, however it's complaining when trying to write to it:

`/opt/Gooby/install/apps/update-rclone.sh: line 45: /home/myusername/.config/rclone/rclone.conf: Permission denied`

It's also truncating some of the output in the wizard:
`Confirm that this is what you named your mount: rive-Movi`
`What is your media folder in rive-Movi? (leave empty for root):`

My remote is 'GDrive-Movies' not 'rive-Movi' 🤣 

Running through the wizard again, it show the client id and secret I specified so it seems the file was written to afterall?

**Comment by TechPerplexed** [comment]
Sounds like a permission problem, you could try to solve it by typing `sudo chown -R $USER:$USER $HOME`
Then run the wizard again (you can delete your .config/rclone/rclone.conf file first to make sure only the correct information is retained).

Let us know if that solves your issue :)

**Comment by bifa2** [comment]
Sadly I still get the same permission issue when hitting q to quit the config. Can't understand why it's able to write to the file but complains about permission denied.

The truncating issue is still present too, and seems to have stripped even more characters: `Confirm that this is what you named your mount: ive-Mov`

**Comment by bifa2** [comment]
I've just run the wizard again, and it's trimmed not 2 (from the start and end) but 3 characters now:
`Confirm that this is what you named your mount: ve-Mo`.

So bizarre lol.

**Comment by bifa2** [comment]
Ok, ran `sudo chmod ugo+rwx rclone.conf` and that seems to have fixed both issues. I'm not sure if this is *too* permissive in terms of permissions, but it should be ok.
