### ISSUE TITLE
Backup not uploading?

### ISSUE THREAD

**Issue by christeasdale** [TechPerplexed/Gooby#103]
I hate asking dumb questions but I don't seem to be able to find a solution to my issue.  

Ubuntu 18.04.3 LTS hosted at DigitalOcean

I just setup Gooby and have Plex and rClone working.  But when I attempt to make a manual backup with Gooby it gives these messages:

/var/local/Gooby/Docker/.env: line 21: unexpected EOF while looking for matching                                       
/var/local/Gooby/Docker/.env: line 33: syntax error: unexpected end of file

It then continues with the backup file being created in the /tmp folder,  it completes but it never makes it to Google Drive.  I tested moving files to rClone mount and they make it to Google Drive so writes are working.

So I am not sure what I am doing wrong?

Another random question but with WinSCP I can't see the /Media folder that is mounted to Google Drive but I can see it from the Plex settings?

Thanks for the help and all the hard work.

**Comment by bdschuster** [comment]
Can you please run `cat /var/local/Gooby/Docker/.env` and post it here?

Also, the Media folder inside any Docker container is mapped to "/mnt/Google", so when you WinSCP in, look to that folder.

**Comment by christeasdale** [comment]
###########################
#  Environment variables  #
#     for Gooby v2.2.0    #
###########################

CONFIGS=/var/local/Gooby
DOWNLOADS=/home/chris/Downloads
GOOGLE=/mnt/google
GROUPID=1000
GROUPNAME=
HOMEDIR=/home/chris
IP=(correct redacted)
LOGS=/home/chris/logs
MEDIA=/mnt/google
ORGMENU=menu
MOUNTTO=/mnt/google
MYDOMAIN=(correct redacted)
MYEMAIL=christopherjteasdale@gmail.com
PLEXCLAIM=claim-VDz53FDyb6af1s3MvLie
RCLONEFOLDER=Chris' Movies
RCLONEHOME=/home/chris/.config/rclone
RCLONEMOUNT=/mnt/rclone
RCLONEPASSWORD=Go0by
RCLONESERVICE=Google Drive
RCLONEUSERNAME=gooby
TCONFIGS=/var/local/.Gooby
TIMEZONE=US/Pacific
UNSYNCED=/mnt/local
UPLOADS=/mnt/uploads
USERID=1000
USERNAME=

My public ip and mydomain showed up correctly but I didn't think posting them was smart.  I am fair at using Ubuntu but totally new to containers.  Thanks for the help.

**Comment by bdschuster** [comment]
Weird, couple things wrong here. Missing Username and Group name, which by the look of your homedir, should be chris for both of them. But you issue, for this at least, is the **'** in your RCLONEFOLDER=Chris' Movies    I'm actually surprised it mounted, but the backup script does not like that **'**. Anyway that could be changed in Google Drive and then in this file? also, linux really doesn't like spaces either, so maybe change it to "ChrisMovies". You will more than likely have to rerun rclone setup after as well. 

Let us know how it goes.

**Comment by bdschuster** [comment]
@christeasdale any update?

**Comment by christeasdale** [comment]
I was able to resolve my issues.  Even though not best practice rclone is able to work with the spaces.  The issues was the gooby backup script didn't like the space I used in the RCLONESERVICE name.  When I re-ran rclone installer and setup with "Gdrive" it cleared up my issues.  I have gone a bit soft using Window and MacOS and all the spaces.  Thanks again for the help.
