### ISSUE TITLE
Certificate Error On All Apps/Sites

### ISSUE THREAD

**Issue by mr-handerson** [TechPerplexed/Gooby#104]
Not sure what has happened here, but it seems that nginx/letsencrypt is no longer serving proper certificates and as such I cannot connect securely to anything.

Did a server reboot from terminal for maintenance/troubleshooting.
Everything seemed to come back online ok but when I went tried to go to portainer it spat me out an error in Chrome

NET::ERR_CERT_AUTHORITY_INVALID
Subject: letsencrypt-nginx-proxy-companion
Issuer: letsencrypt-nginx-proxy-companion

And in Firefox

Error code: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT
The certificate is not trusted because it is self-signed.
HTTP Strict Transport Security: true
HTTP Public Key Pinning: false

If I clear cookies in Firefox it allows me to add an exception and proceed, but then I just get a 500 Internal Server Error

If I connect insecurely through Edge, then everything loads OK. So it is all running, just the HTTPS is broken.

I've tried doing a Gooby update and a system cleanup, both of which seem to complete successfully, but the issue remains.

From memory (although I may be recalling incorrectly so this could be a red herring), previously the certificate would match the URL eg. portainer.domain.com
But now every site seems to be issued to letsencrypt-nginx-proxy-companion

Thoughts? Ideas? Suggestions? Help? Please, and thank you.

**Comment by TechPerplexed** [comment]
Hmmm I have no idea... nothing has changed at all with Gooby and I haven't heard about this issue yet. Perhaps they are down at the moment? (not trying to blame someone else, I just can't think what it could be) :)

**Comment by bdschuster** [comment]
I've only run into this issue when the container isn't coming up or I don't have the whatever.domain.com listed correctly in both places in the yaml file for the service. I've made changes to the docket file before and have forgotten to change it in both places.

**Comment by mr-handerson** [comment]
Yeah, I noticed there were no recent commits which is why I'm so stumped. 

All containers are up and healthy, and I didn't make any changes to anything. Was purely a server reboot.

I'm pulling down my last backup so I can compare and try and discern if there's anything glaringly different and obvious.

**Comment by mr-handerson** [comment]
OK. So it turns out all my certificates were gone. The /var/local/Gooby/Docker/certs folder had all the subfolders for each subdomain, but the root was empty.

I tried restoring all the certs from the backup, but that didn't seem to have any impact.
So I did another system cleanup, which said it completed successfully.
Gooby reports that all containers are healthy, but if I try and access anything now I get

Welcome to nginx!
If you see this page, the nginx web server is successfully installed and working. Further configuration is required.
For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.
Thank you for using nginx.

I also noticed that my .env file changed.
Currently on the server I have a GROUPNAME and USERNAME set
In my backup from last weekend the GROUPNAME and USERNAME are blank
What would cause it to change? Is it related?

I also restored it, did another system cleanup, but noticed that it updated the file and re-added the GROUPNAME and USERNAME back

**Comment by bdschuster** [comment]
strange. @TechPerplexed any ideas here?

**Comment by mr-handerson** [comment]
I'm still working on this, I had to sleep.
So the certs I mentioned were actually symlinks, so the initial way I had restored didn't work ( I had extracted from the backup and copied in via SFTP gui).

Since my backup was only 6 days old I decided to just try a full restore. Oddly it restored everything except for the 4 plex symlinks. I tried manually restoring directly from the tar via terminal. They're now properly in place, but plex is still giving a security error.

That's where I'm picking up today.

**Comment by mr-handerson** [comment]
After a system cleanup, it has deleted the 4 plex symlinks and the env has been updated again to set the GROUPNAME and USERNAME.

I'm now about out of ideas so I might just have to nuke the server and start from scratch and hope that a restore from backup works fully this time around.

**Comment by TechPerplexed** [comment]
Oof, sorry about that... I don't really have any ideas either. So how exactly have you modified your system to create the 4 plex symlinks? Trying to understand what might have been happening here...

**Comment by mr-handerson** [comment]
I restored them in place from my last backup. I downloaded the backup from Google drive to the server, and then extracted the 4 missing symlinks from the tar into /var/local/Gooby/Docker/certs.

I have now also tried uninstalling plex and reinstalling to see if that would trigger recreating the missing symlinks. Instead, when I did a system cleanup it has now deleted most of the other symlinks, so I'm going backwards.

**Comment by TechPerplexed** [comment]
Well, you see, the reason I'm puzzled is that it doesn't really matter what is currently in the ../Docker/certs folder, because every time you reboot/perform a cleanup, your certs are recreated by LetsEncrypt anyway. In fact that is how you are basically ensured to always have a current certificate, valid 90 days from "now".

Restoring the backup doesn't have anything to do with it... wouldn't harm it but doesn't do any good either. At least that's my understanding - I'm not too familiar with the ins and outs of LE otherwise!

Still not sure what you mean by symlink?

**Comment by mr-handerson** [comment]
And that's why I was initially doing a reboot. I was down to 20 days left on the current certs, so I was just doing a reboot to refresh them.

From what I've gathered from troubleshooting in the past 24 hrs:
Within the certs folder, there is a subfolder for each site (plex, sonarr, radarr etc) that contains 4 files that comprise the actual certificates etc.
Then in the root of certs there are 4 symlinks created per site to the four files within the subfolder
Without the existence of these symlinks, the sites don't actually load securely. I'm not sure how/why, but that's how it works. If the symlinks exist, the site loads properly with the certificate. Without it, the certificate is not loaded (despite existing in the subfolder)

I've attached some screenshots that hopefully help illustrate what I'm saying.
Subfolders exist for all the containers I have installed, and they all have the files required.
However symlinks are missing for many of them from the root of certs
In the example I've attached, the symlinks exist for radarr4k, but not for radarr.
So radarr4k site loads properly, while radarr does not

![certs](https://user-images.githubusercontent.com/54524566/68091086-46218d00-fe30-11e9-9e87-89ce55345395.png)
![subfolder](https://user-images.githubusercontent.com/54524566/68091083-4588f680-fe30-11e9-8f57-467088eea217.png)
![radarr4k](https://user-images.githubusercontent.com/54524566/68091085-4588f680-fe30-11e9-8f74-944ce8f40b05.png)
![radarr](https://user-images.githubusercontent.com/54524566/68091084-4588f680-fe30-11e9-87cf-f48271d80e06.png)

**Comment by mr-handerson** [comment]
I think the underlying issue is related to the fact that in my env I now have a GROUPNAME and a USERNAME set (is set to my account).
In the env from last working backup, there is nothing set for these 2 items.
And it shows that all files are owned by user/group root/root
So I think there's perhaps a permissions something where it can't create the symlinks

**Comment by TechPerplexed** [comment]
Really your .env groupname and username shouldn't have anything to do with it (but eh, stranger things can happen). 

At a very careful guess, I think that with all your trying and tinkering, you might have triggered an "eh buddy, slow down a little" mode from LetsEncrypt and it might just sort itself in 24 hours or so... they do have a limit of the certificates they hand out on an account during a given time. 

On the other hand you could also force yourself to be the owner of the Gooby environment by typing `sudo chown -R $USER:$USER /var/local/Gooby/Docker` and see if that sorts some things.

Otherwise, I have no idea really!

**Comment by TechPerplexed** [comment]
Ok, you might have a point... I just renamed my certs folder and ran a system clean - and now I'm getting this error 500 as well. Let me try to troubleshoot this... I wonder if something may have changed with LetsEncrypt...

**Comment by TechPerplexed** [comment]
One question: are you using CloudFlare or do you manage your domain directly?

**Comment by mr-handerson** [comment]
Ah ok, it was something that had changed recently, and I wasn't sure if it had therefore resulted in a potential permissions related issue.

I was going to try a chown next, but I'll hold off on anything else for the time being since you were able to replicate the issue. Glad I hadn't proceeded with a server reinstall hah!

I have not configured Cloudflare on my setup, so it's currently being managed directly.

Thanks for taking the time to investigate. I was starting to feel like I was going in circles.

**Comment by TechPerplexed** [comment]
Yeah it's definitely reproducible but that doesn't mean I have an answer yet, unfortunately... will start digging vigorously though :)

**Comment by TechPerplexed** [comment]
After some testing with a fresh domain, this is what I get:

![Clipboard](https://user-images.githubusercontent.com/15312691/68136700-f0f28380-fee2-11e9-8339-efc5eb326f39.jpg)

The website (http) works. However https gives a 500 error. It looks as if the certificate is created, but the site just won't display at all.

I honestly have no idea what it can be and why it suddenly stopped working properly. I do know that the proxy docker (jwilder/nginx-proxy) was updated a few weeks ago. I'll keep searching for a solution, and as always, all suggestions are welcome in the meantime!

**Comment by mr-handerson** [comment]
I did find this on LetsEncrypt https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430/2

Under var\local\Gooby\Docker\certs\accounts it lists acme-v01, so perhaps related? Need to migrate to v02?

**Comment by TechPerplexed** [comment]
Good for you... that sounds like a very plausible reason. Looking at the proxy component: https://github.com/TechPerplexed/Gooby/blob/master/scripts/components/01-proxy.yaml

It definitely mentions `- ACME_CA_URI=https://acme-v01.api.letsencrypt.org/directory`. Now I'm not going to change anything before having tested this, so if you feel brave, you can manually change it on v02 and see if that sorts it.
I'll probably fire up a temp Hetzner again and try it with a "safe" domain, heh.

Thanks again for the heads up!

**Comment by bdschuster** [comment]
Confirmed working changing to v02 at least for me. Changing my prod machine and making sure it doesn't break, but my test worked fine and can now access securely.

**Comment by TechPerplexed** [comment]
Yahoooooooooooooooo!!! It seems you may have licked it - it's working for me too both on my test machine and my main one. Congrats and thanks to @mr-handerson - will include the patch in the upcoming release (which just gave me a reason to make more haste in testing our new backup procedure) :)

**Comment by bdschuster** [comment]
Just tested on all 3 of my prod hosts, all looks good. Thanks @mr-handerson ! Good catch! Will close once you confirm working.

**Comment by mr-handerson** [comment]
OK, now for my n00b question...
I've updated the proxy yaml
I did a docker-compose restart, but nothing seems to have changed.
What steps do I need to take to get the change to actually apply?

**Comment by bdschuster** [comment]
Do an rclean from terminal

**Comment by mr-handerson** [comment]
OK, that did it! Everything is back working as expected now, all sites secured. Glad it got figured out, thanks again!!

**Comment by christeasdale** [comment]
I seem to be have certificate issues.  Gooby can't seem to get a cert for my domain plexmovies.net, or any domain.  It doesn't even create a folder for the my domain name.  I have tried managing my domain and a few rcleans,  Plex works but I think this is the reason I have been having clients that run AndroidTV with the new player.  This I guess checks certificates and fails with a connection error.
Common Name: letsencrypt-nginx-proxy-companion is an self signed default cert. when I attempt to navigate to plex.plexmovies.net

I even attempted with a completely new clean Ubuntu server and fresh install of Gooby and still couldn't get it working to get a certificate.  I am pulling my hair out over here.  Mine is not the same error it is using V02.  I could really use some help.
