### ISSUE TITLE
rclone high memory usage

### ISSUE THREAD

**Issue by christeasdale** [TechPerplexed/Gooby#107]
Gooby running on DigitalOcean standard droplet with 4vcpus, 8gig, 160gig disk.  Only running stock install with all rclone (standard version), no advanced settings.   Seeing rclone using 75% of the memory (6gig) with one 1.8gig mp4 direct playing to a Roku client.  Seems odd on the Roku client the entire file seem to be downloaded to DO right away, where with other clients like FireTV I can slowly see it downloading as needed in the Gooby rclone transfer script.   Plex Beta install,  everything is up to date.  Ubuntu 18.04 LTS  Earler it also crashed and unmounted when 4 direct play files were playing.  I am guessing it finally ran out of memory.  Is rclone ready for primetime or should I go back to PlexDrive?

**Comment by christeasdale** [comment]
Okay so doing more research,  I modified the systemd "rclonefs.service" file to change --buffer-size 1G to --buffer-size 100M  and that seems to have resolved my high memory usage with rclone.  But I am sure this won't survive a new version of Gooby or a cleanup.  Is there a way for me to do this that will?  I pre-convert all my movie files down to an average file size of about 2gig with all subs burned and AAC audio, so in almost all cases the client can direct play/stream.  Any other flags in rclone that might be more ideal for me to set differently in addition to "--buffer-size 100M"  thanks

**Comment by bdschuster** [comment]
Forgot to change this on the new version. Rclone is fine, change to 0m buffer size, everything will be fine. will change on the master branch soon. had the same issue here when rclone changed something about 2 months ago, then I changed buffer to 0m and all my issues went away and I have 16G of RAM, it was using it all.

**Comment by TechPerplexed** [comment]
@christeasdale No worries about Gooby automatically updating your .service files - that won't happen. For the very reason that everyone has different RAM and other settings so there isn't really "one size fits all" here (though we try to be as optimized as possible).

We were only "forced" to change the file once, many moons ago, when we went with the updated syncmount procedure. Really I don't expect that'll have to be done any time soon again unless Rclone makes some drastic changes.

@bdschuster Updated buffer size is in place for future users :)

**Comment by chocolateshirt** [comment]
remove --buffer-size 100M will use rclone default buffer size, better for VPS use

**Comment by bdschuster** [comment]
@christeasdale everything working ok? May we close this issue?

**Comment by christeasdale** [comment]
Yes things are good.  Thanks all for the feedback/help.  Before we close is there a better venue for general discussion about Gooby for things that don't rise to the level of an "issue" here on Github?

**Comment by bdschuster** [comment]
Not really busy enough for that yet, but I might spin something up for general discussion in the future. I will talk it over with @TechPerplexed, but for now an issue is fine, or even commenting on this issue even after it's closed we still get notifications.
