### ISSUE TITLE
Remote Access Dropping

### ISSUE THREAD

**Issue by ASchluterman** [TechPerplexed/Gooby#109]
Hello TechPerplexed!

Thank you for everything you do for this project! I searched through closed issues and could not find related solutions, so decided to create a post.

Recently decided to nuke and rebuild my server as it seemed to be running into issues. Installation and entire process of Gooby went well working with Rclone and Plex. Everything is 98% there, but whenever I enable remote access, everything goes green and enables for ~6 seconds until it quickly drops and becomes inaccessible. Images below.

![Accessible](https://user-images.githubusercontent.com/51297624/68882306-8ad0e200-06d4-11ea-97f3-45d9bf2a4355.JPG)

![Not Accessible](https://user-images.githubusercontent.com/51297624/68882345-98866780-06d4-11ea-93c2-357e3a07d518.JPG)

Not sure if Gooby related, but I have run system clean and rebooted the server to no avail. Thought I would get your perspective on where I can begin troubleshooting this. 

Appreciate your time!

**Comment by bdschuster** [comment]
That port should be set to 8443 not 32400, internally that port is 32400, but from the outside, it's 8443.

**Comment by ASchluterman** [comment]
Had a feeling it would be a stupid easy solution.

Thank you!!

**Comment by bdschuster** [comment]
Glad it's working. And don't feel bad, before i started working on this project with @TechPerplexed , i didn't know that either 😆 .

**Comment by TechPerplexed** [comment]
It's a great question for newcomers though, so thanks for asking 😄
