### ISSUE TITLE
Rclone mount timing out/sleeping?

### ISSUE THREAD

**Issue by christeasdale** [TechPerplexed/Gooby#112]
Strange issue,  after a few hours (around 2-3hours) if no files are accessed by Plex (only item running on my server) then Rclone seems to timeout/sleep.   Then the first Plex client after this "sleep" has kicked in to access Plex, can access and navigate all normally but when a movie file is played it takes from 30 to 40secs for the movie to start when it normally takes under 5sec.  Tonight on Roku Player it actually never started and Plex failed with error something like "file not available, check hard drive".   But then as soon as I cancel and re-try playback of the same or any other file it works normally and starts in under 5secs.  My host OS is Ubuntu server 18.04 LTS on DigitalOcean droplet.  My Gooby settings are all stock except (--buffer-size 150M).  Ubuntu wouldn't be sleeping the drive? or as I suspect Rclone is somehow timing out or closing connections to Google?  Thoughts?

**Comment by christeasdale** [comment]
I checked Rclone log and it shows no errors for the time in question.  I attempted to look for error in the Plex log but it is so cryptic it was hard to narrow down a specific error in that log.

**Comment by bdschuster** [comment]
@christeasdale , i have never had this happen to be honest, nor have i heard it happen to anyone else. And to be honest, Plex is constantly looking at at those folders for changes, so it wouldn't be rclone "sleeping". My load time is anywhere from 10-20 seconds normally, and i have a 1GB up/down connection on a physical host. The only way i get a 4 second load time is the file is still locally stored on the host and not google, or maybe a very low quality SD show/movie, but normally 10-20 seconds.

**Comment by christeasdale** [comment]
While many others pay for high power servers really far from their client.  I pay for DigitalOcean only 100 miles from my closest client.  That user with a gigabit connection can nearly max out his connection with DigitalOcean Speedtest with ping under 20ms.  So when he tells me "I tried to play something and after nearly a minute of spinning it didn't play"  Very disappointing.  I also pre-convert all movies to small mp4 versions, so the file he was trying to play is 935mb.  With his connection he could have downloaded the entire file in less time than it took for my server to choke.  Then he tried another movie seconds later and it started nearly instantly.

I currently have all scanning and automatic library updates turned off in Plex.  I guess as a test I will turn on "Scan my library periodically" for every 30mins and see if this keeps things working correctly for my setup.  I will report back.

**Comment by TechPerplexed** [comment]
Could be DigitalOcean putting up some crippling throttling mechanism and not telling you about it... usually when you go with a VPS they want to make absolutely sure that their clients can't hog the entire bandwidth and/or resources, at least not for long.

To be specific, Gooby only facilitates, it doesn't throttle or hinders the performance. You might try to play some more with your Rclone settings, or have a good look at Digital Ocean and their terms of service. I'm afraid I don't have more advise to offer at this moment 😕
