### ISSUE TITLE
No docker/.config folder

### ISSUE THREAD

**Issue by dboobis** [TechPerplexed/Gooby#114]
I recently ran out of space on my server, so cleaned out my Downloads folder and rebooted. However, none of the Docker containers started so I tried to do a system cleanup through the Gooby menu as that usually sorts things.

This said that I needed to install and configure rclone first, which I've never seen before. Running the rclone install again (through the menu) gave an error:

`/opt/Gooby/install/apps/install-rclone.sh: line 31: /var/local/Gooby/Docker/.config/mergerfs: No such file or directory`

If I continue through the setup anyway, it lists my gdrive as a remote already. Quitting the config and accepting the defaults then throws these errors:

```
/opt/Gooby/install/apps/install-rclone.sh: line 64: /var/local/Gooby/Docker/.config/rcloneservice: No such file or directory
/opt/Gooby/install/apps/install-rclone.sh: line 65: /var/local/Gooby/Docker/.config/rclonefolder: No such file or directory
cat: /var/local/Gooby/Docker/.config/cf_email: No such file or directory
cat: /var/local/Gooby/Docker/.config/cf_key: No such file or directory
cat: /var/local/Gooby/Docker/.config/goobybranch: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0    118      0 --:--:-- --:--:-- --:--:--   119
cat: /var/local/Gooby/Docker/.config/mydomain: No such file or directory
cat: /var/local/Gooby/Docker/.config/myemail: No such file or directory
cat: /var/local/Gooby/Docker/.config/plexclaim: No such file or directory
cat: /var/local/Gooby/Docker/.config/proxyversion: No such file or directory
cat: /var/local/Gooby/Docker/.config/rclonefolder: No such file or directory
cat: /var/local/Gooby/Docker/.config/rcloneservice: No such file or directory
cat: /var/local/Gooby/Docker/.config/version: No such file or directory
done
chown: cannot access '/var/local/Gooby/Docker/.config': No such file or directory
0,15,30,45 * * * * /opt/Gooby/scripts/cron/syncmount.sh > /dev/null 2>&1

 Done!


--------------------------------------------------
 install Rclone completed
--------------------------------------------------

rm: cannot remove '/var/local/Gooby/Docker/.config/checkapp': No such file or directory

```
There is a folder in `/mnt/google` but it only has a Downloads folder, no path to my Drive. When I stop and start the rclone service manually this folder goes away until I "reinstall" rclone again.

I've checked `/var/local/Gooby/Docker` and there is no `.config` folder there. The `docker-compose.yml` file looks good though. `docker images` lists all the expected images but `docker ps` doesn't show anything.

Trying system cleanup again still says I need to install rclone. Updating gooby and running the gooby install doesn't do anything either.

Not sure what else to try, so any help would be greatly appreciated.

**Comment by dboobis** [comment]
Been trying some other things - `docker up` in the Docker folder does start some of the containers but fails when it tries to connect to the mounts.

rclone logs just keep repeating these lines:

`2019/11/29 00:53:24 INFO  : Using --user gooby --pass XXXX as authenticated user
2019/11/29 00:53:24 NOTICE: Serving remote control on http://127.0.0.1:5572/
2019/11/29 00:53:24 Failed to create file system for ":": config name contains invalid characters - may only contain 0-9, A-Z ,a-z ,_ , - and space`

I've tried deleting all my remote mounts and rebuilding but that didn't help.

**Comment by TechPerplexed** [comment]
Gooby recently had an upgrade, but it sounds that didn't go entirely well for you for some reason. Before you try anything else, could you please remove the version file in /var/local/Gooby/Docker/.config and run rclean again?

Commands to run:

```
rm /var/local/Gooby/Docker/.config/version
rclean
```

Do you still get errors?

**Comment by dboobis** [comment]
There is no .config folder (so no version file). rclean says it's already running.

**Comment by TechPerplexed** [comment]
Ok, let's kill that... Find the number of the process by typing rclean, then type

`kill -9 <numberoftheprocess>`

Then run rclean again...

**Comment by dboobis** [comment]
Took a while but all seems to be working again, thanks!

**Comment by TechPerplexed** [comment]
Yay!
