### ISSUE TITLE
Backup failing with Errors

### ISSUE THREAD

**Issue by christeasdale** [TechPerplexed/Gooby#116]
I migrated to a new server and have everything working except for the backup.

I did a "system cleanup" and it ran without errors.  But when I run backup I get the following:

Current backup schedule:
15 2 * * SUN /opt/Gooby/scripts/cron/backup.sh > /dev/null 2>&1

 The backup can take several hours
 Please don't exit the terminal until it's done!

Creating backup - please be patient...

/tmp/PlexMovies-backup.tar.gz --> /Backup/PlexMovies/PlexMovies-backup.tar.gz @ awk: /bin/sizer:8: fatal: division by zero attempted
/var/local/Gooby/Docker --> /Backup/PlexMovies/Gooby/Docker-diff.tar.gz @ awk: /bin/sizer:8: fatal: division by zero attempted
/var/local/Gooby/Plex -->

_

I then creates all the correct folders and backup files on Google Drive but they are all 0 bytes.
I am not sure what I am doing wrong.  Thinking it might have something to do with moving to a new server.  Any help would be appreciated.

**Comment by TechPerplexed** [comment]
Hmm strange indeed, what is your new server is called? `hostname` or `hostnamectl` should tell you...

**Comment by christeasdale** [comment]
"PlexMovies" it is the same as the past install.  I moved from DigitalOcean to Vultr.  I migrated using the backup and recovery with Gooby.  Are we thinking it might be something to do with the Machine ID changing but the hostname the same?  Like I said everything else seems to be working fine.

**Comment by TechPerplexed** [comment]
I was more thinking that perhaps the server name had some odd characters in it, but that's not it obviously. I have no idea what it could be...

What version of Linux are you running, same version that you had before? And what happens when you type something like `sizer 12345678`?

**Comment by christeasdale** [comment]
Ubuntu 18.04.3 LTS and yes same OS I was using on previous server.

sizer 12345678 returns 11.77 MB in any folder, I Googled and can't find this command.
My skill set on Linux isn't amazing, could this be a folder/file permissions issue?

**Comment by TechPerplexed** [comment]
Haha, that is an app that my friend kelinger wrote to make it easier to visualize the size of files. It appears to be working just fine... so that is not it either.

I'll ask him if he has idea idea what could be wrong, because frankly I have no idea!

As for the permission issue: you could try `sudo chown -R ${USER}:${USER} /tmp` but that is already included in the rclean command so I don't give that much chance...

When exactly do you get this error and does the script run for a while first?

`/tmp/PlexMovies-backup.tar.gz --> /Backup/PlexMovies/PlexMovies-backup.tar.gz @ awk: /bin/sizer:8: fatal: division by zero attempted`

**Comment by christeasdale** [comment]
Bellow is full output from terminal:

 Current backup schedule:
15 2 * * SUN /opt/Gooby/scripts/cron/backup.sh > /dev/null 2>&1

 The backup can take several hours
 Please don't exit the terminal until it's done!

Creating backup - please be patient...

/tmp/PlexMovies-backup.tar.gz --> /Backup/PlexMovies/PlexMovies-backup.tar.gz @ awk: /bin/sizer:8: fatal: division by zero attempted
/var/local/Gooby/Docker --> /Backup/PlexMovies/Gooby/Docker-diff.tar.gz @ awk: /bin/sizer:8: fatal: division by zero attempted
/var/local/Gooby/Plex -->


Weird when I first discovered this issue, it would create blank files on Google Drive,  but now that isn't happening.  I just attempted to run backup after deleting the folder on Google Drive.

It does create 
Docker-diff.tar.gz
Plex-diff.tar.gz
PlexMovies-backup.tar.gz

in the tmp folder.

The backup script does complete after about 10 seconds after the above errors, but clearly the backups aren't actually completed.

Writing to my Google drive mount works fine, I actually directed Plex's built in DB backup to a mounted folder and that is working without issue.


.env output if that helps any,  I redacted the sensitive bits, they were accurate:

###########################
#  Environment variables  #
#     for Gooby v2.2.1    #
###########################

APILOG=/home/chris/logs/api.log
CF_EMAIL=
CF_KEY=
CONFIGS=/var/local/Gooby
CONFIGVARS=/var/local/Gooby/Docker/.config
CURDIR=/var/local/Gooby/Docker
DOWNLOADS=/home/chris/Downloads
GOOBYBRANCH=master
GOOGLE=/mnt/google
GROUPID=1000
GROUPNAME=
HOMEDIR=/home/chris
IP=(REDACTED OK)
LOGS=/home/chris/logs
MEDIA=/mnt/google
ORGMENU=menu
MOUNTTO=/mnt/google
MYDOMAIN=plexmovies.net
MYEMAIL=(REDACTED OK)
PLEXCLAIM=(REDACTED OK)
PROXYVERSION=nginx
RCLONEFOLDER=
RCLONEHOME=/home/chris/.config/rclone
RCLONEMOUNT=/mnt/rclone
RCLONEPASSWORD=Go0by
RCLONESERVICE=Gdrive
RCLONEUSERNAME=gooby
SERVER=PlexMovies
TIMEZONE=US/Pacific
UNSYNCED=/mnt/local
UPLOADS=/mnt/uploads
USERID=1000
USERNAME=
VERSION=2.2.1

**Comment by TechPerplexed** [comment]
Ok, I just had a bit of a brainwave based on what you said there... can you please try this

`rm /var/local/Gooby/Docker/.config/snapshots/*`

Then try `gbackup` again, do you still get errors? If it is what I hope it is, then I think I know how to prevent this from future happenings... fingers crossed!

**Comment by christeasdale** [comment]
Current backup schedule:
15 2 * * SUN /opt/Gooby/scripts/cron/backup.sh > /dev/null 2>&1

 The backup can take several hours
 Please don't exit the terminal until it's done!

Creating backup - please be patient...

/tmp/PlexMovies-backup.tar.gz --> /Backup/PlexMovies/PlexMovies-backup.tar.gz @ awk: /bin/sizer:8: fatal: division by zero attempted
/var/local/Gooby/Docker --> Removing outdated DIFF for Docker --> /Backup/PlexMovies/Gooby/Docker-full.tar.gz @ awk: /bin/sizer:8: fatal: division by zero attempted
/var/local/Gooby/Plex -->


Variation on the same error.  But now like when I first attempted the backup it again creates new "\Backup\PlexMovies\Gooby" and files PlexMovies-backup.tar.gz, Docker-full.tar.gz and Plex-full.tar.gz on Google Drive that are all 0bytes. 

Also creates new empty version of the Docker.snar and Plex.snar in the snapshots folder
But this time no files are created in the tmp folder.

Again after errors it works for about another 10 seconds and completes the script with no other errors.

**Comment by TechPerplexed** [comment]
Oh blegh... I was hoping it would be something simple. I have asked the expert (kelinger), hope he has an answer. Hang tight :)

**Comment by TechPerplexed** [comment]
Unfortunately, he doesn't know what it could be either. However, he would like you to try with a modified version of sizer just to rule out any errors there...

`sudo nano /bin/sizer`

Then replace the entire content of the current file with

```
#!/bin/bash

numfmt --to=iec --format="%.2f" ${1}
```

Remove the snapshots file

`rm /var/local/Gooby/Docker/.config/snapshots/*`

And try `gbackup` again... does it still give errors? And more importantly, are the files in the Google backup still 0 bytes?

**Comment by mr-handerson** [comment]
JIC it helps narrow things down, I recently moved servers too. Did a backup on old then restore on new to get back up and running very quickly (so awesome!). My backups are working ok; my new server name is different to my old one. I also use client ID in rclone. Same OS as OP.

Apart from this info I don't think I'll be able to help with the troubleshooting, but GL!

**Comment by TechPerplexed** [comment]
Since it's been a week since I heard back, I'm closing the issue... as always, feel free to add if it hasn't been resolved :)
