### ISSUE TITLE
GPU transcoding for Emby

### ISSUE THREAD

**Issue by geelenbert** [TechPerplexed/Gooby#119]
Hello,

I would like to know what the best option is for adding GPU transcoding to my emby docker.

Here is a description of how it could/should be done:
https://emby.media/community/index.php?/topic/76937-docker-hwa-nvidia-instructions/

What is the best way to get this working ?

**Comment by TechPerplexed** [comment]
Luckily, this is super easy with Emby. All you need to edit your emby file (`nano /var/local/Gooby/Docker/components/22*`) and
change these two lines

```
#    devices:
#      - /dev/dri:/dev/dri

```
to 

```
    devices:
      - /dev/dri:/dev/dri
```

In other words, remove the # but make sure not to remove the space behind it.

Then run `rclean` and you should have your hardware version enabled!

**Comment by doob187** [comment]
1.) First question  NVIDIA  or Inteö IGPU *?*
For NVIDIA you you need more steps
For Intel IGPU not so much 

2) intel IGPU >

sudo usermod -a -G video ${USER}
ls -la /dev/dri
chmod -R 777 /dev/dri 

docker exec emby apt-get -y update
docker exec emby apt-get -y install i965-va-driver
docker restart emby

See post above add the ENV  to the yaml 

3.) Remote Server *?*  or.Local Server *?*

**Comment by geelenbert** [comment]
Thanks for the reply!

I have an Nvidia Quadro P2000 for transcoding.

It is running on a local server. Ubuntu 18.04 with the P2000 passed trough.

**Comment by TechPerplexed** [comment]
I'll close this issue for now, since I'm not sure what else can be said about it :) Feel free to continue the conversation though!
