### ISSUE TITLE
[Request] Ability to add apache http auth

### ISSUE THREAD

**Issue by deedeefink** [TechPerplexed/Gooby#12]
Thanks for v2. 

I would like the option to add Apache http auth to the domains as an extra layer of security. I would imagine that adding one auth for all the domains as part of the environment section would be the easiest.

However, I have a use-case where I would like to give access to ie. Ombi, but not the other URLs, therefore it would be good to either have an option to set the password per domain, or to enable/disable the auth per domain. This way I can either controll access with different passwords or i can disable authentication on OMBI.

Thanks

**Comment by TechPerplexed** [comment]
Thanks for the suggestion! In fact the base for this is already in place, it's just a matter of implementing this - stay tuned!

**Comment by TechPerplexed** [comment]
And... it's added. Go try it 😄

**Comment by deedeefink** [comment]
Tried, but not working :-(

I added a user to Sonarr, but no http auth is popping up when I access the URL. I tried a private session and also a different browser and I cleared my cache. No auth window.

<img width="489" alt="sonarr" src="https://user-images.githubusercontent.com/14345450/47600028-4daf8a00-d9c3-11e8-9749-893c6683306e.png">

**Comment by TechPerplexed** [comment]
Ahhhh.... Weird... it worked when I tested at first... Let me look into that!

**Comment by TechPerplexed** [comment]
Hmm yes definitely working correctly here... can you try this just to be sure:

1. Update Gooby to the latest version (option E - A in the menu)
2. Run a system cleanup (option E - C in the menu)
3. Wait till it's done... then try again...

Let me know if that sorted it!

**Comment by deedeefink** [comment]
Your steps worked, which is good but also strange.
Today I reinstalled my servers 3-4 times today Linux+Gooby and tested the hell out of it. I always used the `sudo wget http://bit.ly/GetGooby -O /tmp/install.sh && sudo bash /tmp/install.sh` to install.

I did not perform any update Gooby or System cleanup since his was a fresh server install and Gooby install. Therefore it's strange that this worked only after update (despite no new release) and system cleanup on a fresh install.

But hey, it works. 
Now I just need to figure out how Sonarr will talk to Jackett and the custom Torznab behind http auth :-)

**Comment by TechPerplexed** [comment]
There is one thing I can think of... you might have installed it right before I noticed that the "s" in "Security" wasn't capitalized. Check if you have two folders in /var/local/Gooby, 1 named security and 1 named Security. If so, you can remove the one named "security".

If that's not it, I blame it in Gremlins 😆
