### ISSUE TITLE
Feature Request: Addition of SyncLounge?

### ISSUE THREAD

**Issue by bifa2** [TechPerplexed/Gooby#123]
Hi,

I was wondering if it would be possible to add an additional tool, SyncLounge (https://github.com/samcm/SyncLounge) to Gooby?

In these times of staying at home for the good of the world (lol) I thought it'd be great to have a one-click install of the product so I can sync watching with friends!

Thank you.

**Comment by TechPerplexed** [comment]
Hi @bifa2 no plans yet to add this, but judging from the docker container you should probably be able to self install this. See https://github.com/TechPerplexed/Gooby/wiki/Custom-Containers for instructions how to go about this. Let us know if you get it going :)
