### ISSUE TITLE
Updating Plex

### ISSUE THREAD

**Issue by reapzyy** [TechPerplexed/Gooby#128]
Hey guys,

Complete noob here, I can't find the option to update Plex to the newest version.

Any help would be appreciated,

Thanks.

**Comment by mr-handerson** [comment]
Run rclean from cli or perform Cleanup from within Gooby menu

**Comment by TechPerplexed** [comment]
Did that answer your question, @reapzyy? If so, we'll close the thread :)

**Comment by reapzyy** [comment]
Yes! That did! Thank you so much :)
