### ISSUE TITLE
Second Rclone remote

### ISSUE THREAD

**Issue by Ninazuu** [TechPerplexed/Gooby#129]
Hi there,

Loving gooby, thanks again for all your hard work.

I want to add a second remote but not sure this is possible with the way Gooby is set up?

Any ideas? 

Thanks!

**Comment by mr-handerson** [comment]
What happens currently when you add the second remote? Is there something that isn't working?

**Comment by TechPerplexed** [comment]
It's been a week, I take it the problem is solved :) Again, thank you @mr-handerson for your continuing help, it's very much appreciated!
