### ISSUE TITLE
Feature Request: Cloud Commander Custom Container

### ISSUE THREAD

**Issue by elmerfreak** [TechPerplexed/Gooby#130]
Someone can help to adapt a container for Cloud Commander?

Thanks

`version: '2'
services:
  web:
    ports:
      - 8000:8000
    volumes:
      - ~:/root
      - /:/mnt/fs
    image: coderaiser/cloudcmd`

**Comment by mr-handerson** [comment]
What happened when you followed the wiki for Custom Containers?

https://github.com/TechPerplexed/Gooby/wiki/Custom-Containers

**Comment by elmerfreak** [comment]
Gooby no recognizing the container when Clean up. Actually I made it work with stack in Portainer, but the container is deleted when I do a reboot.

**Comment by TechPerplexed** [comment]
@mr-handerson thanks so much for all your help!!
@elmerfreak how exactly did you add the new container?

**Comment by elmerfreak** [comment]
As you see Cloud Commander don't have such parameters as Gooby containers, I cloned radarr4k container.

<img width="756" alt="Screen Shot 2020-06-05 at 11 43 48 AM" src="https://user-images.githubusercontent.com/5510709/83907006-d656e600-a721-11ea-9795-5127bc8425ce.png">

**Comment by TechPerplexed** [comment]
Sorry for the late reply. You say the container disappears at reboot, so my question was in what location did you add the file? What did you name it?

**Comment by elmerfreak** [comment]
Hi,
Container:
`/var/local/Gooby/Docker/components`
Name: 
`200-Cloudcmd`

**Comment by TechPerplexed** [comment]
O

**Comment by elmerfreak** [comment]
both, when run System Cleanup and reboot

**Comment by TechPerplexed** [comment]
What happens when you stop and start the service manually? (docker stop cloudcmd, then start it again). Do you get any errors when you run rclean?

**Comment by elmerfreak** [comment]
Now Cleanup no install the container, heres the code if you can try:

`#
# Cloudcmd - File manager for the web
#
  cloudcmd:
    restart: unless-stopped
    image: coderaiser/cloudcmd
    container_name: cloudcmd
    hostname: cloudcmd
    cpu_shares: 2048
    ports:
      - 7000:8000
    depends_on:
      nginx-proxy:
        condition: service_healthy
      letsencrypt-nginx-proxy-companion:
        condition: service_started
        #deluge:
        #condition: service_healthy
    volumes:
      - ~:/root
      - /:/mnt/fs
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/Cloudcmd:/config
      - ${HOME}/logs:/config/logs
      - ${MEDIA}:/Media
      - ${DOWNLOADS}:/Downloads
      - /bin/netstat:/bin/netstat:ro
      - /usr/bin/killall:/usr/bin/killall:ro
    environment:
      - PGID=${GROUPID}
      - PUID=${USERID}
      - TZ=${TIMEZONE}
      - VIRTUAL_HOST=cloudcmd.${MYDOMAIN}
      - VIRTUAL_PORT=7000
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=cloudcmd.${MYDOMAIN}
      - LETSENCRYPT_EMAIL=${MYEMAIL}
    healthcheck:
      test: ["CMD-SHELL", "netstat -ntlp | grep :8000 && mountpoint /Media"]
      interval: 10s
      timeout: 2s
      retries: 3`

**Comment by elmerfreak** [comment]
I think I figure it out, I change the number on name, and it work, tested on Cleanup and Reboot. 

New name:
`99-cloudcmd.yaml`

Thanks for patient, if you don't have anything else, you can close it.

**Comment by TechPerplexed** [comment]
Oh duh, I should have seen you named it 200 - yeah that wouldn't work :)

I would suggest you name it something like 95-cloudcmd.yaml instead of 99, since that is reserved for the final code (not applicable currently, but might at some future date).

I'll go ahead and close this now, glad you got it resolved!
