### ISSUE TITLE
Wiki - Deluge - seeding port settings

### ISSUE THREAD

**Issue by falcomm6** [TechPerplexed/Gooby#131]
Hi TechPerplexed,

First of all I want to thank you for creating such a wonderful package. It has become a new hobby of mine learning and maintaining this system - which overall is a very rewarding experience. I will make sure to buy you a coffee soon!

This isn't so much of an issue, but it's the last hurdle for me. I have issues uploading torrents in Deluge - the speeds are very slow. Sometimes I get some people downloading from me at slow speeds, but most the time its a flat 0%. I assume this is due to the inbound port configuration - but I think its beyond my expertise to work out how that routing works with Nginx.

I am using a sock 5 auth proxy, which also adds to the mix. If theres anything you can do to assist I'd be indebted.

With thanks,
Matt

**Comment by TechPerplexed** [comment]
Thank you, it's appreciated 😄 

As for the slow speeds at Deluge, I haven't noticed that myself and Gooby should never act as a bottleneck. Can you share screenshots of your network settings (in Deluge)? I assue you haven't altered any Gooby settings, right?

**Comment by falcomm6** [comment]
Thanks for your reply!

Here are my settings. I haven't altered any Gooby settings. I still upload, however its pretty slow. I was on a private tracker site with a freeleech file and had it seeding 48hrs - I saw multiple peers connect but they were all at 0%.

![deluge settings](https://user-images.githubusercontent.com/67247329/88603570-aa6c3700-d0b8-11ea-9fca-48436f76ebb9.jpg)

**Comment by TechPerplexed** [comment]
I notice one big difference: change your proxy to "none" and see if that makes a difference. Gooby looks after that :)

**Comment by TechPerplexed** [comment]
Edit: oh wait I guess you need the proxy to hide your actual IP... but still... try switching it off temporarily and see if that is the culprit!

**Comment by falcomm6** [comment]
Thanks! I tried that as a first point of test for 24hrs but had no real change. Trying not to get banned from a private tracker but my ratio is so bad at 0.0011 or something hahaha.

I assumed there was some kind of setting to optimise incoming port, but I could be mistaken. I'm somewhat glad it's not obvious. It could be to do with OVH blocking something somehow. If there's no further advice I understand and will close this ticket. I get good upload on my home connection, even with the sock5 - definitely a peculiar one.

Appreciate your time.

**Comment by falcomm6** [comment]
Many support pages Ive read suggest assigning an incoming port rather than random. Is there a chance that random is being blocked? I've turned off the proxy again for testing.

**Comment by falcomm6** [comment]
Murph's law, I found a solution after asking. I found a plugin named itConfig - it has helped DRAMATICALLY on high performance seed.

![image](https://user-images.githubusercontent.com/67247329/88609846-726cf000-d0c8-11ea-82c9-031026e96a58.png)

Appreciate your time.
