### ISSUE TITLE
Waiting on mounts to be created...

### ISSUE THREAD

**Issue by falcomm6** [TechPerplexed/Gooby#132]
Hi techperplexed.

While waiting for my provider to get back to me re: backups, I've had a serious issue and I cant seem to restore things.

System cleanup shows the below indefintiely:
![image](https://user-images.githubusercontent.com/67247329/88670271-31a4c380-d128-11ea-8be2-da1ebbe0e795.png)

I have tried a full backup through gooby (as i dont have a snap, sadly). I still get this error. Any clues?

I tried uninstalling then reinstalling rclone

**Comment by falcomm6** [comment]
I'll close this one too. Sorry for being eager. I went through the previous issue lists and honestly it looked like an nightmare. rclone does not play nice for me if I want to edit it. Its basically a one shot one opportunity gig

1. Reformatted PC with Ubuntu
2. installed gooby fresh
3. installed rclone - mounted drive and crypt
4. restored backup.

All working! I love your backup feature. It seems that rclone is the buggy part. It downloaded the backup file through crypt, but then for some reason wouldnt mount. Doesnt make sense when it had to be mounted to achieve that.

Any way. All ends well. I was able to work it out with what I learned over the past month reformatting over and over.

Cheers

**Comment by TechPerplexed** [comment]
Glad to hear it :) Usually, `rclean` solves just about any problem. 

If by any chance it remains stuck at the "Waiting on mounts to be created", make sure you check that there is no `/mnt/google` folder. If it does exist, it usually means that an upload to Gdrive didn't happen. The solution is to manually delete the contents of /mnt/google (making SURE there is nothing there that you need to keep), kill the rclean process and run it again.

That should tame even the most stubborn Rclone mount problems 😄
