### ISSUE TITLE
Can't reach remote sites

### ISSUE THREAD

**Issue by CrazyTacoDude22** [TechPerplexed/Gooby#133]
I cannot seem to reach any of my subdomains. I have added them as an A record in cloudflare and my domain but cannot seem to get it to connect. Deluge worked for a couple minutes then I was unable to access it. Plex I added the manual port and it will still not let me reach it remote neither only plex.domain.com:8443 can't really seem to figure this out.

**Comment by TechPerplexed** [comment]
You say Deluge worked for a couple of minutes, what error message are you getting now?

**Comment by CrazyTacoDude22** [comment]
> You say Deluge worked for a couple of minutes, what error message are you getting now?

Just a standard this page isn't working, too many redirects.

**Comment by TechPerplexed** [comment]
How have you set up cache settings in CloudFlare?

**Comment by CrazyTacoDude22** [comment]
> How have you set up cache settings in CloudFlare?

It's set to standard caching. 
![dns](https://user-images.githubusercontent.com/69659550/90280432-e9c8b080-de38-11ea-84a6-c6057732b2dd.PNG)
![cache](https://user-images.githubusercontent.com/69659550/90280433-e9c8b080-de38-11ea-87d9-200d8c769553.PNG)

**Comment by TechPerplexed** [comment]
Looking good :) And SSL/TLS settings?

**Comment by CrazyTacoDude22** [comment]
> Looking good :) And SSL/TLS settings? (just the overview is sufficient)
> 
> Edit: make sure it's set to either Full or Full (strict).

It's on flexible, which one would you suggest I change to? Full or Full (strict)?
![ssl](https://user-images.githubusercontent.com/69659550/90283217-ca805200-de3d-11ea-9c32-537ea420f230.PNG)

**Comment by TechPerplexed** [comment]
I would suggest you try strict first, it's the safest. If you experience issues with non Gooby sites, you can always go back to just full.

Make sure you purge all cache after you change the setting, I'm pretty sure that will sort you out 😊

**Comment by CrazyTacoDude22** [comment]
> I would suggest you try strict first, it's the safest. If you experience issues with non Gooby sites, you can always go back to just full.
> 
> Make sure you purge all cache after you change the setting, I'm pretty sure that will sort you out 😊

I get this error now when I switched it to Full (strict) and purged all caching 
![image](https://user-images.githubusercontent.com/69659550/90285101-34e6c180-de41-11ea-8002-923308b5dd3d.png)

**Comment by TechPerplexed** [comment]
Looking good! 👍 Give it half an hour or so to allow the certificate to come through.

You can also try `rclean` to trigger the certificate, bit you should be good to go soon!
