### ISSUE TITLE
Issue with rclean after installing Portainer

### ISSUE THREAD

**Issue by falcomm6** [TechPerplexed/Gooby#138]
Hi guys,

Ive reformatted my machine since my last post. Now I can install portainer, but _after_ installing - I only then start to get issues with other parts. Im going to leave portainer out of the mix for now.

Screenshot attached during rclean.

![image](https://user-images.githubusercontent.com/67247329/92852108-a9f1ea80-f431-11ea-93ef-660efd3778ef.png)

**Comment by falcomm6** [comment]
I now just went to uninstall portainer but it says its not installed. very odd

**Comment by bdschuster** [comment]
yeah, this doesn't seem like a Gooby issue, this seems like a backend issue somewhere. @TechPerplexed would you agree? @falcomm6 , what flavor and version of linux are you using?

**Comment by falcomm6** [comment]
Thank you for looking.

Ubuntu Server 20.04 Focal Fossa. If there is a suggested build I am all ears.

Thank you

**Comment by bdschuster** [comment]
@falcomm6 , yeah, I haven't had a chance to test a lot with 20, and to be honest, I left Ubuntu a while ago cause they keep making changes that break sh** all the time, especially docker. I've always had good luck with Debian. I'm using 9, no issues at all.

**Comment by TechPerplexed** [comment]
Same here, all the issues I ever had disappeared like snow in a hot sun after moving to Debian. Never looked back!

**Comment by falcomm6** [comment]
Thank you!! I thought I was going crazy with the amount of mount errors I've been having. I'll move to Debian.

Can I take my backup with me, or at least the config?

Appreciate your time.

**Comment by bdschuster** [comment]
@falcomm6 I don't think there should be any issues restoring on Debian from Ubuntu, agree @TechPerplexed ?

**Comment by TechPerplexed** [comment]
Shouldn't make any difference!

**Comment by falcomm6** [comment]
Cool. Love both of your work. I'm a linux and command line newbie so Gooby has been a great learning experience for me

Have a nice one.
