### ISSUE TITLE
Downloading directly to Media

### ISSUE THREAD

**Issue by roubachof** [TechPerplexed/Gooby#139]
Ty so much for your works, it's effin amazing 👍 

Now, I have a gdrive: remote which has 3 folders:

* Movies
* Music
* TVShows

How can I configure nzbget to download directly to say, the Movies folder?

![image](https://user-images.githubusercontent.com/596903/97806105-32cf1a80-1c5a-11eb-8e95-bf34f4bc3989.png)

What should I put in the DestDir field?
Since those are Docker containers I'm a bit lost about how to access the host files...

**Comment by roubachof** [comment]
Ok I finally understood that in fact the managers like sonarr or radarr will interact with nzbget to retrieve the downloaded files.
However it seems there is an issue with the default config.
NZBGet download files in the "/downloads" folder. But it seems to be a folder local to the nzbget container.
The "/Downloads" folder seems to be shared. So you need to point to the one with the uppercase to make it work.

**Comment by TechPerplexed** [comment]
Great :) Sorry, I haven't been able to answer earlier. I'll mark this as solved (closed) then. It'll be a good first issue for people with the same question, so thanks for that!
