### ISSUE TITLE
Docker pull limit

### ISSUE THREAD

**Issue by thunderstorm654** [TechPerplexed/Gooby#140]
Hi there, I ran a system cleanup today and got a bunch of errors pulling the latest Docker stuff e.g.

ERROR: for plex  toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

Everything still seemed to come back up thankfully, but not sure how this impacts things going forward? Found an article about Docker making some changes but I don't know if this means I need to pay for a Docker sub or not :) apppreciate anyone's thoughts!

**Comment by Adoruta** [comment]
Register for a free account docker if you don't already have one, then whilst you're logged in with your Gooby account, run `docker login` and authenticate there. I had the same problem and this appeared to resolve it for me.

**Comment by thunderstorm654** [comment]
Excellent thank you @Adoruta that worked :)
