### ISSUE TITLE
How do you create your first backup?

### ISSUE THREAD

**Issue by billrunge** [TechPerplexed/Gooby#141]
I am trying to back up Gooby for the first time and when I do, it says "Please make _**sure**_ that you restore an existing backup first". However, I don't have an existing backup as this is the first time backing up and I'm not sure what to do.

**Comment by Adoruta** [comment]
To set up the first backup, don't be in the gooby app, instead, from the bash prompt execute `gbackup`. It'll set you up from that point onwards.

**Comment by TechPerplexed** [comment]
Right, the message is just a heads up to restore before you create a backup. If you don't have a backup, you can safely ignore that message. We should probably change the wording a little to make that less confusing...

As @Adoruta said you can also use the `gbackup` command directly and avoid the confusion 😄

**Comment by billrunge** [comment]
Excellent. Thank you!
