### ISSUE TITLE
Odd Behavior With Accessing subdomains

### ISSUE THREAD

**Issue by Misterobots** [TechPerplexed/Gooby#143]
Currently I have Plex, Radarr, Sonarr, Deluge, and Ombi installed. When accessing different subdomains(ex. sonarr.domain.com), I get "500 Internal Server Error" depending on whether my SSL mode (in cloudflare) is set to "Full" or "Flexible". When set to "Full", I can access Radarr, deluge, and Ombi but not Sonarr. When set to "Flexible", I can access Sonarr but I cannot access Radarr, deluge, or Ombi. SSL is not enabled within any of the above apps. Everything is currently at "default" settings applied by Gooby.

**Comment by TechPerplexed** [comment]
I usually get the 500 internal server error for about 5 to 10 minutes, then everything should work properly... how long ago did you install this on your subdomain?

**Comment by Misterobots** [comment]
I've deleted cache. I set all of them up at the same time, around 24 hours ago. I did notice that the culprits (sonarr and jackett) do not have entries here for crt,key,dhparam, or chain. Would this cause the behavior? I'm sorry if I'm way off base, I'm still fairly new and just happen to see this.
![image](https://user-images.githubusercontent.com/9805557/100913342-a6558900-349f-11eb-8330-e711ae332be1.png)

**Comment by TechPerplexed** [comment]
Yeah I just checked mine and it did create an entry for every domain. Can you run `rclean` and see if it gets created then?

**Comment by Misterobots** [comment]
Thank you for the verification. I have run rclean and it did NOT create the "missing" files. Where (or what script) creates these? Can I check it for missing info? Or should I be able to create them myself? Thanks again for the help!

**Comment by TechPerplexed** [comment]
Normally Gooby takes care of the SSL certificate all by itself. I have never encountered it intermittently creating some certs and not others. Absolutely silly question, but can you check if you created the same A-record for sonarr and jackett and the rest of your subdomains? Just covering all bases here... I'm sure you did :)

**Comment by Misterobots** [comment]
You are correct. the A-records were all setup and the same (minus being for different subs). I did a re-install and the presented again. If I go in and create those two files, all works. Odd behavior indeed, but I am up and running and I have made a backup of the working config. Question: will the backup also restore those files / config?

**Comment by Misterobots** [comment]
Also, to add onto the behavior. I just installed (for the first time) NetData. Same behavior, those cert files were not created, but the folder was. If you could help me narrow down where that "creation" action happens on install, I'd be happy to look at it and see if we can pinpoint what might be causing it.

**Comment by TechPerplexed** [comment]
Hmm, I'm wondering if your issue is related to #144 - not sure what it could be but I'm wondering if something changed with the way certificates are created.

**Comment by TechPerplexed** [comment]
Sorry missed your question: yes, a backup will restore everything including the files config files (if you restore all).

**Comment by Misterobots** [comment]
Thank you for all of the help. I would say that I have a "work around" at least, BUT when I looked into the certs directory and within the directories for the above mentioned new installs, this time there are no files at all. Previously, the folders (sonarr, radarr, etc.) would at least have the requisite files within the folder. I'm so confused by this behavior. I could copy + rename the files appropriately with the previous domains, but with NetData(and Tautulli) there is just a blank directory (ex.
 netdata.domain.com)

**Comment by Misterobots** [comment]
So, the update/fix added by Adoruta seems to have fixed my issues. I was in a "ban" from LetsEncrypt. After updating and waiting out the rolling ban, certs pulled just fine and working as intended.

**Comment by TechPerplexed** [comment]
Great, thanks for letting us know, @Misterobots 

I too have had no issues any longer. Even after pulling new containers, it just skips the certificate creation which is exactly what we want!

**Comment by TechPerplexed** [comment]
I'll close this issue for now, and will probably create a minor release in a few weeks to pull the new files for all users. Thanks for reporting the issue and verifying it's working now :)
