### ISSUE TITLE
Media Server Wiped

### ISSUE THREAD

**Issue by Otunga** [TechPerplexed/Gooby#145]
Hi, I followed the custom container tutorial to a tee, was trying to install SABNZB from the containers list. I did the settings, copied it over yada yada and when I went to clean system, it threw a message at some point about docker rate limiting and now it looks like it has wiped my who setup :(

You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limits is the message I get on cleanup and then when I go to check installed containers it's empty but they still exist in the system if that makes sense, can't reach them on the browser now though.

**Comment by Adoruta** [comment]
Part of the process on Gooby is to clear out the containers on the expectation new versions will come down automatically, however Docker Hub (web) is blocking that for you. Create a free account on hub.docker.com and then use those credentials to log in your Gooby server using the command `docker login` and then you should have more success. Only the container has been temporarily lost, not the data that goes with it.

**Comment by Otunga** [comment]
> Part of the process on Gooby is to clear out the containers on the expectation new versions will come down automatically, however Docker Hub (web) is blocking that for you. Create a free account on hub.docker.com and then use those credentials to log in your Gooby server using the command `docker login` and then you should have more success. Only the container has been temporarily lost, not the data that goes with it.

Thank you so much, I'm a noob with docker containers and this really did the trick!
