### ISSUE TITLE
Sabnzbd cert issue

### ISSUE THREAD

**Issue by Otunga** [TechPerplexed/Gooby#146]
Hi, another issue, when I install sab via the custom docker container tutorial it installs fine but when I go to my domain sabnzbd. it shows as unsecured with no option to skip this screen in google, I figured it's a letsencrypt cert issue but idk how to fix it.

**Comment by TechPerplexed** [comment]
I think your issue might be related to #143 and #144 
Unfortunately I (we) don't have a solution for that just yet... it appears that Let's Encrypt has changed something and we're still trying to find out what... and how to solve that!

**Comment by Otunga** [comment]
so what's my recourse @TechPerplexed ? I tried NZBGet but if I remember it said something about empty pathing for /downloads/

**Comment by Otunga** [comment]
UPDATE: Now when using another browser I get this with SABNZBD "Access denied - Hostname verification failed: https://sabnzbd.org/hostname-check"

**Comment by TechPerplexed** [comment]
Are you still experiencing issues @Otunga or was it all related to the recent changes Let's Encrypt made?

**Comment by TechPerplexed** [comment]
It's been 10 days since you replied last, so I'll close this issue for now :) Feel free to reopen if you still experience problems!
