### ISSUE TITLE
IP Whitelist for containers

### ISSUE THREAD

**Issue by falcomm6** [TechPerplexed/Gooby#148]
Hi there,

This isn't an issue; just wondering if there's a resource or way you know of to whitelist an IP for certain containers? I'd like to make most containers whitelisted to my static IP.

I've tried some things on my own, but admittedly the reverse proxy setup is initidating haha

Thank you
Matt

**Comment by TechPerplexed** [comment]
I'm not sure what you mean? The internal IP address of containers is dynamic and changes with every reboot/rclean. They are actually never used except internally, so can you explain what you are trying to accomplish?

**Comment by falcomm6** [comment]
Hi there,

Sorry - I should have explained better. What I'm trying to achieve is to whitelist my personal static IP to be able to access certain subdomains/containers instead of them being public.

ie: Netdata - instead of this subdomain being accessible to everyone, I would like to restrict access to only my IP address.
I dont want to do this for all containers as obviously organizr and emby need to be public.

Cheers!

**Comment by TechPerplexed** [comment]
Oh I see, well the easier work around to that is use the "secure app" feature from the menu. That way you can password protect any of your containers that you don't want the world to see. I agree Netdata can display some sensitive information, it's one of the first apps I protected 😸

**Comment by falcomm6** [comment]
Clever, never noticed that option. Thanks, that'll do it. I guess I was aiming to prevent any brute force attempts on most the containers - but tbh the risk is very low.

Cheers
