### ISSUE TITLE
Support Dropbox on Gooby

### ISSUE THREAD

**Issue by Adoruta** [TechPerplexed/Gooby#154]
I have a few patches to better support other cloud storage providers (specifically Dropbox) whilst hopefully still supporting Google Drive!. Interested?

**Comment by TechPerplexed** [comment]
Haha, well, the "hopefully" is making me slightly reluctant... @bdschuster thoughts? 😄

**Comment by bdschuster** [comment]
I believe the true heart of Gooby was to be used with Google Drive, so we prob wouldn't want to break that...lol

**Comment by Adoruta** [comment]
Absolutely. In fact, I've just tested my Dropbox compatibility patch with Google Drive and it was fine.  The only real change is to remove the first "/" in the rclone sync command so files go into the individual's folder. That's how it was on Google Drive anyhow, but the first "/" on Dropbox implies the Team drive. I know we can't test every cloud storage provider, but to provide support for Dropbox when Google is becoming more restrictive could be considered.

**Comment by bdschuster** [comment]
@TechPerplexed , back at you, thoughts? lol

**Comment by TechPerplexed** [comment]
Agree that the future seems a bit shaky with Google. So of course we'd like to support Dropbox as well... but only if the edit doesn't break Google. I agree that it is the basis on which Gooby was built so yeah... don't want to ruin that 😄
