### ISSUE TITLE
Sonarr/Radarr Cannont Read property 'map'

### ISSUE THREAD

**Issue by BrennanFlory** [TechPerplexed/Gooby#161]
When attempting to add preexisting movies or tv shows I receive this error.
`TypeError: Cannot read property 'map' of undefined

    in r
    in T
    in div
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in r
    in oI
    in r
    in r
    in T
    in t
    in t
    in r
    in r
    in t
    in t
    in r
    in h7
    in div
    in div
    in r
    in r
    in T
    in withRouter(Connect(r))
    in t
    in n
    in i
    in T
    in c
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in e`

**Comment by TechPerplexed** [comment]
Not sure what you mean, where do you get the error and what are you trying to do exactly?

**Comment by DrSpeedy** [comment]
@TechPerplexed it's an issue with sonarr/radarr. I found my way here trying to google it after trying to import my library into radarr v3.

**Comment by TechPerplexed** [comment]
I see, well I guess you will need to ask Sonarr/Radarr in that case :) Hope you find a solution!
