### ISSUE TITLE
Strange behaviour Mount and Rclone config

### ISSUE THREAD

**Issue by Pabers** [TechPerplexed/Gooby#162]
Appologioes for the noobie questions:

I seem to have an issue with mounting my Rclone G Drive, It will NOT be mounted on boot, and I can not seem to run rclone outside of gooby (rclone config command does not work)
so my fix is to the the following every time I reaboot:
- Gooby
- uninstall Rclone (which actually does not really do much as all my configs ect still stay there)
- Install Rclone (My previous config is there) and run through the config without changes
- quick Rclone config and gooby will ask what the name of my rclone config is called, it will then ask what drive folder and then mount it.

If I try and just install it (without uninstall) it shows the following.
![image](https://user-images.githubusercontent.com/77447505/104604612-717b4b00-5675-11eb-86c4-b924b5dc8983.png)

after uninstalling and reinstalling it shows the following (local seems to get automatically added)
![image](https://user-images.githubusercontent.com/77447505/104604961-d3d44b80-5675-11eb-99c7-b342d0be54f5.png)
and now it all seems to work fine.

Strangly there is also a local mount in the config I did not place there, I have removed it and seems to work fine.
I tried to run the clean E C
and it goes into an endless loop which I need to restart the server to stop
waiting for mount...
waiting for mount... 
Or something like that..

Also I noteided that checkapp.txt has rclone listed as in /usr/bin/rclone but its not in that folder.

Bascially, what is not happening now is:
- Rclone is not mounting my Gdrive at boot
- I am unable to write to the Gdrive as the premissions are not set properly (but I can not see it in fstab or where it is listed to mount to fix that).

any help?

**Comment by TechPerplexed** [comment]
So first the local mount is needed for uploads, if you use that. So don't delete it.

Not sure what's up with rclone uninstalling itself, I have never seen that. What type of server are you using and what Linux version?

**Comment by Pabers** [comment]
ah! I did not realise that was used for uploads, so how would I go about uploading files in that case? as I get permissions denied when I copy files to the mounted drive.

well its not "uninstalling itself" I do not think, i belive its just not seeing the current install of rclone if I navigate manually I can see the rclonefs.servicein the folder: /etc/systemd/system

Ubuntu version is:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy
its running on a 64bit arm pi

I tried running `See "systemctl etc`
it shows nothing, but when I click crt D it shows the follwoing:

`-bash: unexpected EOF while looking for matching `"'
-bash: syntax error: unexpected end of file`

seem to going deeper into the rabbit hole...

**Comment by TechPerplexed** [comment]
Ok, so let's try to break this down for troubleshooting.

First, try `sudo systemctl stop mergerfs` and see what you see when you type `ls /mnt` (which folders?)
Then `sudo systemctl stop rclonefs` and same question, which folders are left?

There shouldn't be a folder /mnt/google or /mnt/rclone
There should be two folders /mnt/local and /mnt/uploads

If that is correct, try `rclean` once more, otherwise report back here :)

**Comment by Pabers** [comment]
Great, thanks for the help!
stopped mergerfs
results for ls /mnt are:
`google  HomeShare  local  rclone  uploads`
Ignore HomeShare (I added them myself with a line item to the Fstab, its my network share at home).
Stopped Rclonefs and results are:
`google  HomeShare  local  uploads`

I did not try rclean and it looks wrong...
Do you also want me to try it after a reboot (thats when rclone is not mounted and I have to install with gooby to get it working again).

**Comment by TechPerplexed** [comment]
Ahh yes if the /mnt/google folder can't be deleted, that means the mount can't be placed back (as a safety measure). Can you check what is in the /mnt/google folder? If it's not important, please deleted the folder `sudo rm -r /mnt/google` and run `rclean` again... fingers crossed :)

**Comment by Pabers** [comment]
oh ok, glad it seemed onvious,
There is nothing in that mount so i will delete it.
once deleting it I run:
sudo rclean and it says the following:
`1127
Already running!`

Opend up gooby did option E then cleanup.
it then runs and goes into an endless loop again:
`/usr/local/bin/docker-compose: line 1: Not: command not found

Updating Rclone if possible

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4436  100  4436    0     0  36065      0 --:--:-- --:--:-- --:--:-- 36360
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0    121      0 --:--:-- --:--:-- --:--:--   121

The latest version of rclone rclone v1.53.3 is already installed.


Cleaning mount leftovers

mountpoint: /mnt/rclone: No such file or directory
mountpoint: /mnt/google: No such file or directory

Calling on Upgrade Service

Your system has already been upgraded to v2.2.2... skipping upgrade

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     81      0 --:--:-- --:--:-- --:--:--    81
done
Job for mergerfs.service failed because the control process exited with error code.
See "systemctl status mergerfs.service" and "journalctl -xe" for details.
Waiting on mounts to be created...
Waiting on mounts to be created...`

![image](https://user-images.githubusercontent.com/77447505/104791650-5ef73380-5793-11eb-8314-73470d9a3786.png)
I have to reboot to fix.

**Comment by TechPerplexed** [comment]
Ok, you can stop that process by Ctrl-C. Then try `kill -9 1127` and try again... if you still get the message "already running" kill that too. We'll get this licked I hope 😄

**Comment by TechPerplexed** [comment]
Also, you say you get `/usr/local/bin/docker-compose: line 1: Not: command not found`

What output do you get when you type `which compose`?

**Comment by Pabers** [comment]
so when we get that "Waiting on mounts to be created...." while I am connected through SHH I am no able to escape it at all I have tried ctrl+c. crtl+d, q, but none work, I end up RDPing in and restarting from the UI.

I ran `which compose` and the output was:
/usr/bin/compose

I must warn you, I am now an unknown realm so I am rather blindly following you instructions (but learning I like to think).

**Comment by TechPerplexed** [comment]
Well at this point I'm not sure what it could be. Would it be possible for you to rebuild your server with Debian 9 or 10? It does seem a lot more friendly towards Docker and prevents a lot of problems. If not, we'll wind back to troubleshooting your wonky MergerFS...

**Comment by Pabers** [comment]
yer its a little confusing, I dont mind re running the install for rclone on gooby each time I restart, it took like 2 days to scan my liburary files. perhaps I should look at keep a backup of plex lib.
The reason for going ubutnu was because I wanted a desktop UI for remote in and run apps that wont run on my chrombook very well, also it supports 64bit Arm (taking advantage of the 8Gb ram on the new Pi, is there a Debian with a good UI and 64bit ARM?

**Comment by TechPerplexed** [comment]
Gooby has a built in backup, which would restore everything including what you scanned. However I don't understand why you need to reinstall rclone after every restart, that just doesn't make sense... 

So let's pick up the troubleshooting once more...

We left it at quitting the mount: 
First  `sudo systemctl stop mergerfs`  
and then `sudo systemctl stop rclonefs`. 
Make SURE you don't have a /mnt/google or /mnt/rclone. 

Then, one by one, bring them backup:

`sudo systemctl start rclonefs`
and
`sudo systemctl start mergerfs`

What messages/errors are you getting?

**Comment by Pabers** [comment]
Ah thats awesome I will attempt to use the backup restore in Gooby, would that work for a plex that is not installed with Gooby?

i did the stop mergerfs and stop rclonefs
I then did ls /mnt  and this is what showed up:
google  HomeShare  local  uploads

looks like Google is not unmounting...

**Comment by TechPerplexed** [comment]
No, the backup will only include Gooby items, so no Plex outside of Gooby.

So yeah we're back to checking what those errors are... what do you get when you type "systemctl status mergerfs.service" and "journalctl -xe"? 😄

**Comment by Pabers** [comment]
Ah ok, I think I will need to check how to back it up anyway at some point.

Ran
`systemctl status mergerfs.service`
![image](https://user-images.githubusercontent.com/77447505/104970522-b095fd00-59e3-11eb-8540-8930b5e604bc.png)
`● mergerfs.service - MergerFS overlay writable storage and local mount
     Loaded: loaded (/etc/systemd/system/mergerfs.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2021-01-18 09:51:52 GMT; 13h ago
    Process: 149983 ExecStartPre=/bin/mkdir -p ${UPLOADS} ${MOUNTTO} ${UNSYNCED} (code=exited, status=0/SUCCESS)
    Process: 149984 ExecStart=/usr/bin/mergerfs -o use_ino,hard_remove,auto_cache,sync_read,allow_other,category.action=all,category.create=ff ${UPLOADS}:${UNSYNCED}:$>

Jan 18 09:51:52 PiServer systemd[1]: mergerfs.service: Scheduled restart job, restart counter is at 5.
Jan 18 09:51:52 PiServer systemd[1]: Stopped MergerFS overlay writable storage and local mount.
Jan 18 09:51:52 PiServer systemd[1]: mergerfs.service: Start request repeated too quickly.
Jan 18 09:51:52 PiServer systemd[1]: mergerfs.service: Failed with result 'exit-code'.
Jan 18 09:51:52 PiServer systemd[1]: Failed to start MergerFS overlay writable storage and local mount.
~`

And then running `journalctl -xe`
![image](https://user-images.githubusercontent.com/77447505/104970615-04084b00-59e4-11eb-8eb7-b9276efc80b4.png)

**Comment by TechPerplexed** [comment]
Hmm and you haven't changed any of the service files, right? It's a long shot but can you try and set the permissions on the /mnt folder to your user? Easiest way is `sudo chown -R ${USER}:${USER} /mnt`. Make sure you run this command only after stopping the services first... or you'll be a waiting a looong time haha!

**Comment by Pabers** [comment]
Morning!
I ran:
sudo systemctl stop mergerfs
sudo systemctl stop rclonefs

Then I restarted
Runing: systemctl status mergerfs.service
provides exacty the same output as above

journalctl -xe shows nothing of interest, just that gnome could not create system prompt becase I am SSHd in.

**Comment by TechPerplexed** [comment]
Darn! I'm out of my league here... it seems that the rclone service is starting just fine (you DO see your content in /mnt/rclone, right?) 

It's just MergerFS that seems to be stubborn here... let me ask advice from a kellinger, the brain behind Gooby :)

**Comment by Pabers** [comment]
Ah I should have clarified that, the rclone folder is empty, no Google drive content int here (unless I to the gobby rclone song and dance).

**Comment by TechPerplexed** [comment]
Ahhhh sorry my bad, that changes things. If it's Rclone that is the culprit, naturally MergerFS can't be mounted and errors out. Now we need to troubleshoot why your Rclone errors out instead. Perhaps a really dumb question and one I should have asked right from the start, but are you sure FUSE is installed and enabled on your system?

**Comment by Pabers** [comment]
That is most certainly not a dumb quesation and might actually be the right one to ask.
I did not install fuse (unless it installs as part of gooby) as it was not in the tutorial I followed from your site. shoud I install it? and if so how do I check if it is already installed and if its not (stupid question) how do I install it, I ask because I don't want to install it in such a way that rclone installed by Gooby does not see it.

**Comment by TechPerplexed** [comment]
Well FUSE is usually not something you need to install yourself, it's the server provider who needs to enable it for you. You would probably need to send a ticket asking them to enable it.

**Comment by Pabers** [comment]
oh wait... what... ok this is new to me, I do not think we have that in the UK (Or need to have it enabled).
Can you point me to some reading material?

**Comment by TechPerplexed** [comment]
Who is your provider for the server? Or are you hosting at home? In that case, all you will probably need to do is
`sudo apt-get update -y` and then
`sudo apt-get install -y fuse`

**Comment by Pabers** [comment]
done but looks like fuse was already installed:
fuse is already the newest version (2.9.9-3).

**Comment by TechPerplexed** [comment]
Blegh, we're running out of options here...

So I'm trying to pinpoint what exactly goes wrong and where. You are saying that the commands above (just concentrating on Rclone for now):
`sudo systemctl stop rclonefs` and then `sudo systemctl start rclonefs` doesnt mount your Google files in `/mnt/rclone`?

**Comment by Pabers** [comment]
It this is the circle I was going arround aswell :(
ls /mnt before funning `sudo systemctl stop rclonefs` shows:
`google  HomeShare  local  rclone  uploads`
ls /mnt after running `sudo systemctl stop rclonefs` shows:
google  HomeShare  local  uploads

Then listing ls /mnt after running `sudo systemctl start rclonefs` shows:
`google  HomeShare  local  rclone  uploads`
and if I ls /mnt/rclone it does show the contence of my Google drive.

===== Now I restart the system, full reboot ====
If I restart (Like I had to above in this thread) and DO NOT runny Gooby at all.
`ls /mnt/rclone` shows nothing, none of my Google drive contense is there.
`ls /mnt` shows the following:
`google  HomeShare  local  rclone  uploads`

Now I run `ls /mnt` after running `sudo systemctl stop rclonefs` shows:
`google  HomeShare  local  rclone  uploads` (which is not what I expected)
`ls /mnt/rclone` at this point still shows nothing.

Now I run `ls /mnt` after running `sudo systemctl start rclonefs` shows:
`google  HomeShare  local  rclone  uploads`
`ls /mnt/rclone` now shows all my google drive content.

something at boot is not working.

**Comment by TechPerplexed** [comment]
Right, when you stop rclone the /mnt/rclone folder should disappear. If it doesn't, the system is not able to bring it back again (failsafe).

Make double sure the /mnt/rclone folder is empty, then are you able to delete it? If not, try `/bin/fusermount -uz /mnt/rclone` and try again... there must be some light at the end of this tunnel sometime 😄

**Comment by Pabers** [comment]
so "Right, when you stop rclone the /mnt/rclone folder should disappear. If it doesn't, the system is not able to bring it back again (failsafe)." that is happening.
The only way I can replicate the rclone folder being empty is by rebooting, NOT restarting rclonefs or running any commands.
if I mannually restart the rcloneFS it seems to be working fine.

Do you want me to reboot, check the rclone folder and if it is truly empty and not loading Google drive data, delete it?

**Comment by TechPerplexed** [comment]
No need to reboot, just check if it is empty and if it wants to delete. If not, run the command I posted above :) I think we're getting somewhere!

**Comment by Pabers** [comment]
Sorry I just want to tripple check (dont want to delete TBs of data):
"Make double sure the /mnt/rclone folder is empty, then are you able to delete it? If not..."
Its not empty, wo with rclone folder NOT being empty and having my Gdrive files listed in it, I shold run the following command?:
`/bin/fusermount -uz /mnt/rclone`

**Comment by TechPerplexed** [comment]
Right, exactly. If you just delete it while your content is mounted, then you remove everything on your Google drive. You definitely don't want to do that...

The fusermount -uz command forces the drive to be disconnected. After that it should be safe to delete the /mnt/rclone folder (though if you are paranoid like me, you should still check if it's really empty)

**Comment by Pabers** [comment]
Ok, very interesting... 
`/bin/fusermount -uz /mnt/rclone`  Does nothing...
Also tried `sudo /bin/fusermount -uz /mnt/rclone` with no difference
the rclone mount is still there and still have all the google content in it.

strange...

**Comment by TechPerplexed** [comment]
That IS strange... what do you get when you type `which fusermount`?

**Comment by Pabers** [comment]
`/usr/bin/fusermount`

Thats it.

**Comment by TechPerplexed** [comment]
Ok, try this: `/usr/bin/fusermount -uz /mnt/rclone` - does that unmount your drive?

**Comment by Pabers** [comment]
I ran `/usr/bin/fusermount -uz /mnt/rclone` but I am still seeing all my rclone Google drive files when I run `ls /mnt/rclone/`

**Comment by TechPerplexed** [comment]
What if you uninstall Rclone from the Gooby menu first? It's it gone then?

**Comment by Pabers** [comment]
Ok so I ran the Gooby command and uninstalled rclone successfully.
I then quit Gooby and ran the following (copied from terminal):

**user@Server:~$** ls /mnt/rclone/
ls: cannot access '/mnt/rclone/': No such file or directory
**user@Server:~$** ls /mnt
**HomeShare  local  uploads**
**user@Server:~$** /usr/bin/fusermount -uz /mnt/rclone
/usr/bin/fusermount: entry for /mnt/rclone not found in /etc/mtab

**Comment by TechPerplexed** [comment]
Ok, good, at least we got rid of the mount from hell, haha. Now if you install Rclone from the Gooby menu again, I would imagine you'll get your mounts back, right? Can you verify this by checking if both /mnt/rclone and /mnt/google show your Gdrive files? (after installing, don't do anything else just yet)

**Comment by Pabers** [comment]
ok installed Rclone with Gooby and that has brought back the rclone folder and all the files from google within that.
ls /mnt/google shows nothing.  its empty.

**Comment by TechPerplexed** [comment]
Yikes, I'm so sorry @Pabers - I don't have a solution. It seems as if your server is somehow rejecting the MergerFS installation, but it's also being stubborn with both Rclone and MergerFS. I guess you are still having trouble unmounting Rclone with `sudo systemctl stop rclonefs`? (folder /mnt/rclone won't disappear?)

**Comment by Pabers** [comment]
no problem, its not the end of the world, I just have to do a few steps every time I restart the device.
I am glad it was not just me doing somthing stupid.

Thank you very much for all the help!

**Comment by TechPerplexed** [comment]
You're very welcome... I just wish I could have been of more help. I'll close this issue now, but if something springs to mind still, I'll be sure to post it!
