### ISSUE TITLE
Docker container Failures during System Cleanup feature

### ISSUE THREAD

**Issue by meharrington90** [TechPerplexed/Gooby#163]
I love your Gooby software. I have been using it for over a year to run a cloud-based Plex server using 2 VPS'es (one in Oregon for hosting the Plex Server, and another in Germany for downloading files). Throughout the use of your software though, I have noticed a major flaw. The Download server tends to fail and break often (at least 4-6 times a year, link with images below) but the Media Server remains stable. I figured this was due to the large amount of I/O operations in the Download Server Docker containers when curating and managing media.

After a couple months of use, the Download Server will begin acting inconsistent and wonky. Hanging processes, subdomains inaccessible, failed upgrades, SSH timeouts, etc. Usually a "System Cleanup" in Gooby will resolve the issue. However, sometimes when initiating a "System Cleanup" to upgrade Gooby and reinstall containers, the Docker process will encounter HTTP errors and unsuccessfully spin down/uninstall/reinstall/spin up the containers themselves. This causes the system to be completely unusable because Docker will not function as expected. 

Initially, I thought this was due to a bug in the software and only a full backup/reinstall of the OS would resolve the issue. However, after some troubleshooting, I realized that I could achieve the same fix WITHOUT reinstalling the OS, and instead just completely removing Docker and reinstalling it on the host system. This includes uninstalling Docker, reinstalling it, and then modifying the new docker group to allow sudo privileges. This resolves any errors during the "System Cleanup" process in your Gooby menu. An example of these errors can be found in the images below. I am using Ubuntu 1804 as a server OS (if CentOS is better, please let me know and I will migrate).

I propose adding the above described uninstall/reinstall of Docker in the "System Cleanup" process (before Docker begins the shutdown/recreation process) would fix this issue for other users. I can provide more information if you wish, but overall, great job with the software!!! Super user friendly and useful.

https://imgur.com/a/BWDgp83

**Comment by TechPerplexed** [comment]
My apologies for this very late reply... some family health issues kept me off the street and away from Gooby 😄 

First, I moved away from Ubuntu and I have been using Debian ever since, never have any issues with it. You might want to try that rather than trying to troubleshoot your disappearing Docker installation. Ubuntu had more issues like if you ran a container for a few days, it would just "hang".  I would really highly recommend moving over to Debian.

Again apologies for the late reply!
