### ISSUE TITLE
Does not work with Ubuntu 20.10, works with Debian 10

### ISSUE THREAD

**Issue by pmaxwellward** [TechPerplexed/Gooby#164]
This is not an issue I need help with, but more of a suggestion to update the tutorial and docs to recommend Debian over Ubuntu. When I was using Ubuntu, I followed the tutorial and I was encountering problems that I saw many others describing in the closed issues section of this project, such as:

- Running rclean would show me the error "Job for mergerfs.service failed" and an endless loop of "Waiting on mounts to be created..."
- I had a unique issue that I didn't see elsewhere*. Rmount was working fine, and the contents of my drive would appear in the directory /mnt/rclone, but the directory /mnt/google was empty and my /Media folder in Plex was empty as well. I should mention that I am using Dropbox, and not Gdrive.

In one of the closed issues, TechPerplexed suggested to someone with a similar problem to switch to Debian, because Ubuntu seems to be screwing with the permissions, or something. I followed that advice, and following the tutorial using Debian works perfectly for me.

Might be beneficial to others to encourage Debian over Ubuntu in the tutorial.

*Edit: I found someone with the same issue towards the end of this thread (https://github.com/TechPerplexed/Gooby/issues/162)

**Comment by meharrington90** [comment]
That was me who had problems on Ubuntu, related to Docker issues.. I would agree with this ticket to change the guide to recommend Debian over Ubuntu.

**Comment by TechPerplexed** [comment]
I'd more than happy to edit the guide, are you talking about the Blogger site or here in this hub?

**Comment by pmaxwellward** [comment]
I discovered Gooby through the blogger site, but in my opinion it would be beneficial to have a brief editor's note on the blogger site and GitHub readme stating that Debian is the preferred OS.

**Comment by TechPerplexed** [comment]
Finally updated the tutorial, took me long enough but was just one of those things that kept falling through the cracks :)
