### ISSUE TITLE
Sonarr outdated docker image tag

### ISSUE THREAD

**Issue by mahogl** [TechPerplexed/Gooby#166]
Small issue has occurred, with Sonarr

Sonarr is reporting the following health message:
You are running an outdated docker image tag, please refer to the linuxserver/sonarr readme for valid tags

Looks like https://hub.docker.com/r/linuxserver/sonarr have updated the versions tags to use develop and stable.

Thank you for you excellent work, and dedication to this project!

**Comment by bdschuster** [comment]
@mahogl , thanks for the heads up! I actually updated the yaml file for sonarr the other day to reflect the new tag, but will not reflect anyone's own yaml as to not mess with users custom configs. This will only reflect new installs. If you need help updating the yaml, please let me know.

**Comment by mahogl** [comment]
@bdschuster No problem, did not noticed that you already updated the script. I would appreciate if you could give some information on how to update an existing installation, not only for me but for other with and older installation. 

Tried to update the /var/local/Gooby/Docker/docker-compose.yaml but after a server restart it was back to the old tag, so there are probably something simple i am missing.

**Comment by bdschuster** [comment]
the location of the file is ` /var/local/Gooby/Docker/components/52-sonarr-beta.yaml` change the line `image: linuxserver/sonarr:preview` to `image: linuxserver/sonarr:develop`, save and exit, run rclean, and you are good to go!

Let me know if any issues.

**Comment by mahogl** [comment]
Worked like a charm, only change from my installation was that the file was named 52-sonarr.yamel.
After the rclean it startet up correctly and it also was there after i booted the server. 

Thanks again for the help.

**Comment by bdschuster** [comment]
@mahogl , glad to hear it worked! Yeah, i wasn't sure how old of an install you had. I'll go ahead and close this out. Have a good week!
