### ISSUE TITLE
Cloudflare 526 invalid SSL cert on strict, HTTP 500 from nginx when on full 

### ISSUE THREAD

**Issue by thunderstorm654** [TechPerplexed/Gooby#167]
Hey, I seem to have got in a total mess and hoping someone can assist!

I tried setting up a custom container this morning for Overseerr. It didn't seem to work so I just deleted the additional yaml component file and went back to what I had before without it. Since doing a few system cleanups, server reboot while everything looks okay from the Gooby output I can no longer access any of my subdomains. I am using Cloudflare and every one reports 526 invalid SSL cert. 

I tried switching the SSL mode to "Full" (not "Full (strict)") on Cloudflare and that just changes the error to 500 internal server error with nginx/1.19.3 underneath. 

I checked the certificates folder on the server and they are all still there as far as I can see. Tried a purge on Cloudflare but no joy. At a bit of a loose end now! Plex is still working via app.plex.tv, I still get Tautulli discord notifications so I know everything is running, just not accessible anymore via the domains.

I'm not an expert in DNS so any hints will be amazing!! Is there anything else I can do to force Gooby to recreate any certs or check the nginx stuff?

Thanks!

**Comment by thunderstorm654** [comment]
Hmm I thought the certificates were there but I think I'm missing a bunch of stuff. In the Docker/certs folder while I still have subfolders per subdomain/app, there's no files like the .crt, .chain.pem, .dhparam.pem, .key in the root of the "certs" folder for each subdomain. All that's there is the default.cert, default.key and dhpaeam.pem. 

Is there a way to get these back for each subdomain?

**Comment by thunderstorm654** [comment]
![Screenshot_20210403-100021~2](https://user-images.githubusercontent.com/16837607/113473820-ecc5ef00-9463-11eb-86d9-a19ec67beb7d.png)

**Comment by TechPerplexed** [comment]
When did you install Gooby? You might want to make sure you are using the latest version of the 03-proxy file: https://github.com/TechPerplexed/Gooby/blob/master/scripts/nginx/03-proxy.yaml (copy that to your /var/local/Gooby/Docker/components folder)

**Comment by thunderstorm654** [comment]
Hi @TechPerplexed, thanks. I found I was having the same issue as the one here https://github.com/TechPerplexed/Gooby/issues/144 and discovered the cert renewal had happened too many times so I'm blocked out til tomorrow I assume. I had the old version of the proxy yaml so I've updated that, fingers crossed from tomorrow all will be well! Does that update stop it renewing on every reboot/system cleanup?

Thanks and happy Easter! :)

**Comment by TechPerplexed** [comment]
Great, glad you found it. Yes the new code will prevent LetsEncrypt from requesting the same certificate over and over again (and risk being locked out, as happened to you). I'm still planning on a release where everyone will be updated to this new code automatically, but life's been a bit hectic lately so I haven't gotten around it yet :)

I'll close this issue for now, feel free to post further information though if you still experience problems!
