### ISSUE TITLE
Not able to connect to Jellyfin nor any other application 

### ISSUE THREAD

**Issue by GOODBOIXD** [TechPerplexed/Gooby#171]
I tried my level best to follow through your (absolutely great i must say) guide, but I seem to have run into a problem. After getting rclone and jellyfin installed, I tried opening jellyfin interface through my domain name. But it doesn't seem to work. ex.tech is assumed to be my server name. So I tried running jellyfin.ex.tech and also jellyfin.ex.tech:8096 but none worked. `DNS_PROBE_FINISHED_NXDOMAIN` is the error that returns. I tried doing the A list thing also. Also, if I only search for my ip address, it returns a `503 Service Temporarily Unavailable` error. I am not sure if I have set the dns incorrectly or need to do something else. Any help would be appreciated.  

Update: was able to get Deluge opening on my dns, but jellyfin still not working. Also, my plugins list is empty when I try setting up deluge for the first time. I have found a fix, but I am not sure how do I implement it here. Here is the link to the fix - https://github.com/linuxserver/docker-deluge/issues/84#issuecomment-594014715

I am running a vps off digital ocean w Debian distro.

**Comment by TechPerplexed** [comment]
Before I go into troubleshooting your Jellyfin, does Gooby work with any of the standard containers? Plex, Emby etc?

**Comment by GOODBOIXD** [comment]
Just checked by installing emby, doesn't seem to work - shows the same error DNS_PROBE_FINISHED_NXDOMAIN

**Comment by TechPerplexed** [comment]
Right, well in that case I would suggest you try a vanilla installation and and don't change any parameters just yet :) Gooby is designed to work ootb (with tweaks possible afterwards), so... tell me where in the process you're getting errors and we'll take it from there!

**Comment by GOODBOIXD** [comment]
That worked, I did a vanilla install and everything seemed to work until a few hours ago. I woke up to check this again, and found that something is wrong with jackett. Its docker container status in portainer was showing as unhealthy, so I restarted it. Now it keeps looping to starting. Also, Failure count shows as 1. And last output -`/bin/sh: 1: netstat: not found`

Should I reinstall jackett?

**Comment by GOODBOIXD** [comment]
update; Jackett docke showed as unhealthy but when i clicked on it, it showed as starting. However, sonarr and radarr connected to jackett seem to be working. Although, sonarr not so efficiently. it automatically returns errors such as All indexers are unavailable due to failures but when I test all, it stops returning the error. Sometimes the shows are searched and downloaded, sometimes not. Is this normal? I am using the told indexer url http://jackett:9117/api/v2.0/indexers/torrentleech/results/torznab/ (changed torrentleech to public torrent sites)

**Comment by TechPerplexed** [comment]
Glad it's behaving better now! Let's go for the full 100% 😆 

I don't use Jackett, but I believe @bdschuster has some experience with that, so perhaps he might be able to answer how to set that up properly...

**Comment by TechPerplexed** [comment]
You're very welcome 😸 Sorry I couldn't be of more help with Jacket though!

**Comment by GOODBOIXD** [comment]
No worries. Also, one last thing, Gooby first downloads the files locally and then copies them to the drive right? It doesn't automatically delete the local files after the transfer is done? Can we automate this if so?

**Comment by GOODBOIXD** [comment]
Yeah, the files in my Downloads folder does get transferred to the rclone mount, but it doesn't delete the files afterwards. I have a folder in my drive called Jellyfin inside which there are folders - Films, Series. I have set the sonarr and radarr root media as `/Media/Series` and `/Media/Films` respectively. And in my deluge settings, I have my Downloads to: set as /Downloads, the Move Completed to and Copy of .torrent files to: are empty. Do I perhaps need to do something with the Move Completed to?

**Comment by TechPerplexed** [comment]
Ok, try to set /Downloads to /Media/Downloads, which will prevent it from copying to the server (it will move the files instead and will definitely be faster). The rest of your settings sound okay, that's how I set it up too. If that doesn't solve it, holler and I'll share my settings in *arr.

**Comment by GOODBOIXD** [comment]
set the /Downloads in deluge to /Media/Downloads. I think this created a dir called Films in my mnt/uploads dir where previously only Downloads dir was in which the movies were downloaded locally. So after uploading the files, I could see that `mnt/uploads/Films` was removed completely but the movie files were still there in `mnt/uploads/Downloads`

**Comment by GOODBOIXD** [comment]
```
root@goodflix:/mnt/uploads# ls 
Downloads
root@goodflix:/mnt/uploads# cd ..
root@goodflix:/mnt# ls
google  local  rclone  uploads
root@goodflix:/mnt# 
```
My directories. I tried removing the torrent file from deluge, and it seemed to remove the files from the Downloads folder too. I think this is alright too.

**Comment by TechPerplexed** [comment]
Yes, that looks correct. I did notice you're logged in as root though - that could pose no end of troubles not least of all security issues. If you can, I would really suggest you run Gooby as a user - it is designed for that :) That might solve your upload issues too - it really should run "as is" without having to tinker with anything.

**Comment by GOODBOIXD** [comment]
Ah no, I do run gooby as a user.

**Comment by TechPerplexed** [comment]
Oh good 😄 Keep an eye on your uploads for a little while with your new settings. It is normal for those folders to be created during the upload, then it should clean after itself when that is done, usually within half an hour or so. If that still doesn't happen, well dig a little deeper!

**Comment by GOODBOIXD** [comment]
Almost got it closed lmao, sorry to keep bothering you with this. But perhaps this will be the last of help that I will be needing. I have been using a few private trackers for a while in deluge, and I am not able to seed these torrents from the private trackers? It asks me to port forward. Do you have any idea how do I get this fixed?

**Comment by GOODBOIXD** [comment]
Nevermind, it works the way its supposed to. Just have this problem w this one particular site. Also, I fixed the issue with jackett. The image needed to be rebuild through portainer w the added volume of netstat. It was missing. Thank you for all the help, I will be closing this now.
