### ISSUE TITLE
Menu duplication

### ISSUE THREAD

**Issue by bifa2** [TechPerplexed/Gooby#173]
The menu seems to be duplicating when started:

![image](https://user-images.githubusercontent.com/54040596/119321847-fa823e80-bc74-11eb-90bb-66c76ad35e34.png)

Any ideas on how to resolve this?

Thank you.

**Comment by bifa2** [comment]
Hmmm. Rebooted and it's now showing as:

![image](https://user-images.githubusercontent.com/54040596/119352786-0502ff00-bc9a-11eb-95a6-abed7e3cbcae.png)

However, logging in from another system, the extra `-------------------` line isn't there:

![image](https://user-images.githubusercontent.com/54040596/119352896-2368fa80-bc9a-11eb-891f-7bb00735515a.png)

Not really an big deal, but odd.

**Comment by TechPerplexed** [comment]
Gremlins, I'm sure!!! Thanks for letting us know. I'll keep an eye on this too but if it doesn't affect anything more than just cosmetics, I will close this now. But feel free to add to this if it keeps on happening :)
