### ISSUE TITLE
502 error 

### ISSUE THREAD

**Issue by mr-handerson** [TechPerplexed/Gooby#174]
In trying to troubleshoot #172 I seem to have caused an issue with a single container, but I don't know how, and I don't know how to fix. Hoping someone has some ideas? Has been working without issue up until this point. 

When I try and access Radarr4K using my URL, I get a 502 error.
Container is up and healthy, nothing amiss indicated in the portainer logs
I can access it using IP and virtual port, so can confirm the container is actually working ok. It's just something to do with nginx.
Everything else is working and accessible.

I have tried an rclean, which completes successfully but doesn't fix anything
Server reboot - no change

UPDATE: I have since also tried to restore the radarr4k backup, and the Docker backup
They seemed to complete, although with numerous errors and it took a server reboot and a few rcleans to get everything to come back up eventually. It did not fix the 502 issue though.

**Comment by bdschuster** [comment]
@mr-handerson you didn't cause it, i'm not exactly sure what changed on this, but I ran into the same issue as well. The only way I as able to get around this and make it work was to change the port from 7878 to 7879 (<Port>7879</Port>) in the config.xml file in the folder where your Radarr4K config is. Then, comment out the ports lines in the YAML file. :
#    ports:
#      - 7879:7878
After that, run an rclean, should be back to normal. I cannot pinpoint if this is a Radarr issue, or nginx, or it even could be something docker changed, but it doesn't seem to be translating the ports in the same way it used to.

As for the disappearing containers, i'm not seeing that issue at all. I'm willing to try and look into it, but at this time, i'm extremely busy at work. Hopefully I'll have a break soon and can dig in deeper.

Let me know if the above fix works for you as well.

**Comment by mr-handerson** [comment]
@bdschuster It was a relief to find out it wasn't just me hah. Thanks for the info! 

I was in the middle of looking into this further and was looking into ports myself. I had wondered if perhaps it was a coincidence that it happened while I am trying to troubleshoot my other issue. Especially since it occurred after an update was pushed for nginx-proxy.

So I went and checked the recent commits and found https://github.com/nginx-proxy/nginx-proxy/commit/49b2b5cd9798582b1d64e9a6b00f72ff712c72c0

Of note:
```
###Virtual Ports
When your container exposes only one port, nginx-proxy will default to this port, else to port 80.
If you need to specify a different port, you can set a `VIRTUAL_PORT` env var to select a different one. This variable cannot be set to more than one port.
For each host defined into `VIRTUAL_HOST`, the associated virtual port is retrieved by order of precedence:
1. From the `VIRTUAL_PORT` environment variable
1. From the container's exposed port if there is only one
1. From the default port 80 when none of the above methods apply```

So I commented out just the VIRTUAL_PORT line in the YAML, ran rclean and lo-and-behold I think I managed to solve this one myself at about the same time you posted your solution. I think mine may be a little neater, as it does not require manual change of the config.xml? Just the removal of a single line from the YAML. Please take a look and let me know what you think.

I would very much appreciate any assistance I can get with trying to figure out why the companion container keeps disappearing, if/when you have time. Thanks in advance.

I will go ahead and close this issue though, since there are 2 solutions that work.

**Comment by bdschuster** [comment]
@mr-handerson , Good catch! I like your find better! I changed mine to match what you did, and confirmed it's working. I will change in the master branch. Thanks! 

As far as the container disappearing ..i'm going to have to deep dive..and with this being a short week at work, and i'm out of town next weekend, it may be hard for me to get some time, but I will try my best.

**Comment by mr-handerson** [comment]
Appreciate it, and there's definitely no real urgency.
For starters, can only test each time nginx-proxy is updated since that seems to be the trigger. So there's indeterminate waiting between occurrences.
Also, as it is only the companion container and certificates should only be getting renewed every 90 days if things are working properly, it's not really system breaking. There's ample time to manually correct, or I guess I could just cron an rclean to occur prior to my cert renewal date.
It's just vexing that it is occurring, since it should not be.
