### ISSUE TITLE
Can I use something else that Google Drive?

### ISSUE THREAD

**Issue by Jalict** [TechPerplexed/Gooby#175]
Hi,

So I worked a little with this now and tried to make Rclone use Backblaze B2 instead. 
But it seems like gooby expects me to use Gdrive, is that correct?

If so, would it be difficult to use something like Backblaze instead?

I setup everything through Backblaze with correct Application Key and Secret. But after I do a System Cleanup it looks like it expects `/mnt/google` (which I am not interested in) and then I get a lot of `Waiting on mounts to be created...`

**Comment by TechPerplexed** [comment]
I see you closed the issue, is it resolved? You could probably adapt Gooby to use Backblaze, but rather a lot of tweaking would be involved... plus you'd have to make sure that Gooby doesn't update itself after a reboot/rclean. But it's open source and freely tweakable, so if that's what you want, go for it 😄
