### ISSUE TITLE
Newer Portainer? (current is deprecated)

### ISSUE THREAD

**Issue by bifa2** [TechPerplexed/Gooby#176]
Hi,

Would it be possible to get the newer version of Portainer with Gooby? It's at 2.6.0 now and the one that runs as part of Gooby is 1.24.2. The docker note says:

`NOTE, This repo, portainer/portainer is the home of Portainer v1.24.x, and is now deprecated; all new releases for Portainer 2.0 will be published in portainer/portainer-ce`

Thoughts? I'd like to run non-deprecated versions if possible :) If I could understand how to tweak and mod the Gooby files to do this, I would, but I'm never quite sure which to edit (or whether they'll get overwritten when I update Gooby).

Thanks!

**Comment by bdschuster** [comment]
@bifa2 This has been changed on our end, but it will have to manually updated on your end as it will not pull new docker files unless there is a major update.

The file you need to update is: `/var/local/Gooby/Docker/components/14-portainer.yaml`
Change the image line to `image: portainer/portainer-ce` (really just adding -ce to the end).
Run `rclean`, and you should be good to go.

Let us know if you have any other issues.

**Comment by bifa2** [comment]
Right ok, I'll let you merge into master when suits you, and manually do this myself.

Out of curiosity, what does rclean do? Why wouldn't I for example, use docker commands to stop and restart all containers based on the compose file?

Thanks.

**Comment by bdschuster** [comment]
@bifa2 , i already updated master.

Rclean does pretty much the same thing, except it makes sure everything is up to date, and cleans stale docker volumes as well...just a convenient and faster way to do what you are explaining.

**Comment by bifa2** [comment]
Right, got it :) From the output I'm pretty sure it's that which is being called when you select the 'System Cleanup' option in the menu. 

Anyway done! Oddly even after running `rclean`, visiting the URL associated with Portainer showed the old version which was odd (I didn't force refresh the browser cache though but did check portainer-ce was running as per `docker ps`), but I gave the server a reboot for good measure and it's showing 2.6.0. Everything looks good.

Thanks for the rapid help

**Comment by bdschuster** [comment]
@bifa2 glad i could help! Have a good rest of your week!
