### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by falcomm6** [TechPerplexed/Gooby#177]
Hi Gooby team,
Its been some time since ive had an issue (Debian helped a LOT vs Ubuntu).

Ive tried multiple reformats and restores, but I cant get my subdomains to work

website uses an invalid security certificate.
The certificate is not trusted because it is self-signed.
Error code: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT

I tried searching old issues but couldnt find a clear answer which assisted. Can you advise which steps I can take? Rclean completes but nothing gets fixed.

Thank you

**Comment by mr-handerson** [comment]
What do your letsencrypt logs say? It's possible you're rate limited now if you have done a lot of restores.

If you're running Portainer you can check them in there, otherwise `docker logs letsencrypt -f` via CLI will also work.

**Comment by bdschuster** [comment]
Yeah, i just hit my limit the other day, had to wait it out about 3-4 hours, and i finally wasn't banned anymore and it updated the cert.

**Comment by falcomm6** [comment]
Thank you all. I only made a ticket as it was down for multiple days. It's now seemed to have fixed itself day 3. I know now for the future. 

Appreciate your time and response. Appreciate the tip to check in portainer next time!
