### ISSUE TITLE
After disabling Cloudflare proxy (switch to DNS only), other apps cannot see Plex

### ISSUE THREAD

**Issue by thunderstorm654** [TechPerplexed/Gooby#179]
I've been having a lot of trouble with Plex buffering recently and there are a few discussions on Reddit that Cloudflare proxying is causing issues. So I tried disabling it (switching from "proxied" which is the orange cloud under the DNS config in Cloudflare, to "DNS only" (grey cloud)). This has made an instant improvement. 
However it's caused some weird knock on effects on other apps. I removed the origin certificate references in the Plex settings, since wondered if that was causing trouble. Emby didn't work at all until I removed it from there.

However Tautulli cannot see Plex on the hostname anymore, only via local IP (which sucks if server is rebooted for updates). I also cannot use Plex Meta Manager either which also tries to connect via the hostname and port 8443. I don't get it though since I can use the plex.mydomain.co.uk:8443 in the browser and it still works (guessing this is behaving differently some way).

Any idea what other steps I need to do to back out of using Cloudflare for anything other than DNS, but my apps still be able to see each other via their hostnames?

I'm not sure what the rest of the Gooby config is doing. Since disabling Cloudflare proxy I can see that it's reverted to using the letsencrypt certs when accessing those subdomains. 

Apologies for the long-winded post, banging my head against the wall against stuff I don't fully understand..! Hopefully someone knows what I'm talking about haha.
As far as I could understand it reading around, switching to DNS only shouldn't really have messed anything up, so assuming there's some other setting I need to change?
Many thanks for any hints.

**Comment by thunderstorm654** [comment]
So it seems to be something wrong within the networking on the server. Tautulli installed on a different server can see my Plex instance fine with the full "hostnamed" URL, but the Tautulli instance on the server still can't. It seems like apps on the same server as Plex cannot see each other via public URLs.  
I did have some invalid SSL cert errors and saw the advice about creating a private key cert on one of the other issues here, so I did that, which solved a few weird certificate complaints in the browser but hasn't helped otherwise. Gah! Just stumped as to why the docker containers don't seem to be able to see each other via hostname URLs but those URLs are working from different servers.

**Comment by TechPerplexed** [comment]
I'm not entirely sure what you're trying to do, but if you want to access containers from within the Gooby environment, you would need to use the internal referral. For example, to access Deluge from Sonarr, you'd use "deluge" as the Host name, rather than the full external URL (or, heaven forbid, the internal IP address) :) 

Does that answer your question somewhat?

**Comment by thunderstorm654** [comment]
> I'm not entirely sure what you're trying to do, but if you want to access containers from within the Gooby environment, you would need to use the internal referral. For example, to access Deluge from Sonarr, you'd use "deluge" as the Host name, rather than the full external URL (or, heaven forbid, the internal IP address) :)
> 
> Does that answer your question somewhat?

Thanks for replying! Not really, but I understand what you mean.

I'm having trouble accessing Plex by its publicly accessible URL in other things that could previously do so.
E.g. In Tautulli it used to work to add my full Plex URL in the settings. 
I also use Plex Meta Manager to manage collections, and this is a python script that connects to Plex via URL and token. This now hangs for a while before saying "Plex URL is invalid". Previously I would have https://plex.mydomain.co.uk:8443 and a Plex Auth token and all was good.
However both Tautulli and Plex Meta Manager work fine if I run them somewhere else, not on the Gooby-configured server hosting Plex. So I know my URLs are good, there's just something weird on the Gooby server where Plex is. Not sure if that explains it better.
I didn't change any proxy config for nginx, literally all I did was turn off proxying in Cloudflare and then removed the origin cert and switched to a standard one. Wondering if I need to blow everything away and start again. Plex is accessible fine outside the server though so I don't get it :(

**Comment by thunderstorm654** [comment]
Huh well it's fixed, by simply running "sudo ufw allow 8443". Begs the question how did it ever work before ...!! God knows. Anyway all works fine now, think I'll stop asking why or how!

**Comment by TechPerplexed** [comment]
Thanks :) I'm so pleased it works... even if we don't know how :)
