### ISSUE TITLE
Unhealthy Containers

### ISSUE THREAD

**Issue by ploquets** [TechPerplexed/Gooby#181]
I'm getting a lot of containers restarts because of this:
`Output /bin/sh: 1: netstat: Permission denied`

Is there something I can do to solve it ?

![image](https://user-images.githubusercontent.com/5149178/135008204-a1a4326d-8b23-4640-a15b-1fd4996394b1.png)

**Comment by ploquets** [comment]
Why not use curl in healthcheck instead of netstat, as netstat needs to run with priviledge flag ?

**Comment by TechPerplexed** [comment]
Not sure what you mean, I'm not getting any such errors. Have you made any modifications?

**Comment by ploquets** [comment]
No. Not at all. But I'm seeing this unhealthy containers and I had to remove the line to use healthy checker with netstat, otherwise the container wont stop to restart. So, my suggestion is to not use netstat as a healthy checker, because seems to need the privilege flag, otherwise it wont execute the command to test the container's healthy.

**Comment by TechPerplexed** [comment]
Thanks for the clarification 😄 I'm not getting any unhealthy containers myself, so can you elaborate a little which ones are unhealthy for you?

**Comment by ploquets** [comment]
plex and deluge.. those are always unhealthy and restarted every few seconds. So, I had to change YAMLs to not check healthy with netstat.

**Comment by TechPerplexed** [comment]
Weird. It works fine for me. But I'm glad you got it resolved... I'll close this issue for now - but we can reopen it if others have the same issue :)
