### ISSUE TITLE
Installer doesn't work with latest docker-compose release

### ISSUE THREAD

**Issue by dboobis** [TechPerplexed/Gooby#183]
My previous VPS imploded so I'm having to do a complete reinstall, and am having some issues.

As of 28/09/21, the latest version of docker-compose returned by `COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4)` is v2.0.0.

This is a complete rethink of how docker-compose should work (it is now a CLI plugin for Docker itself) and so the installation and usage instructions have changed. The gooby installer as is no longer is able to install docker-compose but fails silently, as does any attempt to install a container.

I have tried hard-coding the previous version number into `docker-install.sh` which allows it to install, but any containers I start through the gooby menu end up constantly restarting - I can't even get into the Plex UI and Deluge disconnects every 30 seconds as the container reboots.

I'm not sure if the two issues are related - I have tried installing across multiple versions of Ubuntu and Debian without any success, so any help would be greatly appreciated.

**Comment by TechPerplexed** [comment]
Ugh, I haven't reinstalled in ages... I'd need to set up a test server to try this out. Give me a few days to troubleshoot :)

**Comment by dboobis** [comment]
I've made some progress on the container issue - it seems the Debian distros my VPS provider uses don't include net-tools in the initial setup, so the containers were restarting due to healthcheck fails because netstat didn't exist. Manually installing net-tools fixed that issue. I'm now trying to contend with rclone not behaving and mounting everything to the rclone directory instead of google where I want it.

Docker have also already released a fix for the asset naming issue so the executable can now at least be found but I think the install method has changed enough that a rewrite of `docker-install.sh` may be needed.
