### ISSUE TITLE
Update no containers running

### ISSUE THREAD

**Issue by christeasdale** [TechPerplexed/Gooby#185]
I had no idea there was a major Gooby update.  I reboot my server for a new version of Plex server and my Gooby updates to 2.2.3 and none of my containers are running.

**Comment by TechPerplexed** [comment]
Oh I'm sorry to hear it... that should not have happened obviously :) Can you please remove the file `version` from `/var/local/Gooby/Docker/.config` (`rm /var/local/Gooby/Docker/.config/version`) and run rclean again? Does that bring your containers back up?

**Comment by bdschuster** [comment]
@TechPerplexed `Updating and starting containers

WARN[0000] The "GOOGLE" variable is not set. Defaulting to a blank string.
1 error(s) decoding:

* error decoding 'Volumes[4]': invalid spec: :/Media: empty section between colons
WARN[0000] The "GOOGLE" variable is not set. Defaulting to a blank string.
1 error(s) decoding:

* error decoding 'Volumes[4]': invalid spec: :/Media: empty section between colons
`
When running rclean...no containers come up. If i try to add `GOOGLE=` to `/var/local/Gooby/Docker/.env` , it get's removed with another rclean and same error as above. Anyway to roll back?

**Comment by TechPerplexed** [comment]
Hmm, that variable should have been obsolete for a long time now... I'll add it back for now but would love to know what's still using it!

**Comment by bdschuster** [comment]
Working now! Thank you!

**Comment by bdschuster** [comment]
@christeasdale , can you run rclean again and try again?

**Comment by christeasdale** [comment]
Deleting "version" and running rclean seemed to fix my issue.  I do have a question.  If you recall I modify the 21-plex-beta.yaml file in /var/local/Gooby/Docker/components to remove the port number.  So this - "ADVERTISE_IP=https://plex.${MYDOMAIN}:8443" to this "- ADVERTISE_IP=https://plex.${MYDOMAIN}" and then on my Vultr Firewall I close all ports except 80 and 443.  And then it routes all Plex traffic through port 443.  If I do it the other way I get Plex clients that fail with connection not secure error.  With these changes in v2.3.3 should that still be okay?  I mean it is currently working but don't know if this will botch my certificate update from LetsEncrypt?  Thanks TechPerplexed especially for getting back to me so fast.  My users are asking where is Plex?!  I still think most of my family still thinks my Plex server is like sharing your Netflix password.  They ask how can I get my own Plex server full of content.

**Comment by TechPerplexed** [comment]
Right, so you should be absolutely fine with your settings 😊

As upgrades are concerned this is truly a minor one. It updated Docker compose to version 2, which should make your server slightly snappier. We also formalized the unnecessary pulling of certificates, a change we made many months ago but that never made it into a release yet.

And finally the Mount drives are now parameterized, which currently is rather semantic/theoretical, but paves the way for an even more flexible setup.

Plus, finally, I liked into some ugly code cleanups left over from the early days.

I'm sorry you guys ran into a little snag. With all my testing it never dawned on me that this also meant that truly old installations still make use of that one tag... It's added back and tomorrow I'll parameterize it properly 😁

**Comment by TechPerplexed** [comment]
And... done. Assuming everything is working now, I'll close this now. Fingers crossed!

**Comment by bdschuster** [comment]
@TechPerplexed , just an FYI, when running rclean to upgrade, you get this:
```
Job for mergerfs.service failed because the control process exited with error code.
See "systemctl status mergerfs.service" and "journalctl -xe" for details.
Waiting on mounts to be created...
Waiting on mounts to be created...
Waiting on mounts to be created...
Waiting on mounts to be created...
Waiting on mounts to be created...
Waiting on mounts to be created...
```
You can ctrl-c out, and try again, with same results. 
The only way i have found to get around it is to go to gooby menu, uninstall rclone, and re-install, then run rclean again. All is good after that.

**Comment by TechPerplexed** [comment]
Oof... okay, strange... but glad that resolved it. Installations are funny things... no idea what could have caused it!
