### ISSUE TITLE
GPUIDS variable is not set warning.

### ISSUE THREAD

**Issue by shadowsbane0** [TechPerplexed/Gooby#190]
Problem: The new Emby and Jellyfin .yamls now look for a GPU variable called ${GPUIDPS}. Specific line is GIDLIST=${GPUIDS}. When the .yamls are run they throw an error msg:

WARN[0000] The "GPUIDS" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GPUIDS" variable is not set. Defaulting to a blank string. 

Partial Solution: environment-build.sh in /opt/Gooby/install/misc/ appears to incorrectly set the variable to GIDLIST and not GPUIDS. Specific line is under the #Apps section and calls GIDLIST=$(getent group video | cut -d: -f3). Should this not be GPUIDS=$(getent group video | cut -d: -f3)?

The reason I call it a partial solution is because I haven't found where else this variable is incorrectly listed or stored from the initial install. I do know that when I re-run System Cleanup. The variable in the script gets changed back and the error is thrown. 

I understand this variable is there for those who are using hw transcoding - I'm one of them. I currently work around it by manually inputting the choice the variable is designed to set in the yaml file.

**Comment by TechPerplexed** [comment]
You are absolutely correct! It's been changed. Let me know if that sorted it for you :)

**Comment by shadowsbane0** [comment]
That solved the error message issue. Thanks much. I’m working through other issues resulting from my switch to Debian. Their stable version is 11 which is what I pulled and installed but I’m getting the sense that 10 may be a better option.

One issue I noticed right off the bat was the use of tempfs for the /tmp file when I tried to restore my backup. It tanked running out of RAM trying to pull it back down. That wouldn’t have mattered much since apparently the backup never uploaded to GDrive and went into the bit bucket when I reformatted and installed Debian. I’ve adjusted the script to use a different location and saved it. I’ll have to overwrite the two scripts each time Gooby updates in the mean time. It’s my stupid fault for not verifying the backup on GDrive before I switched. Now it’s all the tedious work of getting everything back the way it was and the sadness that I finally had everything working the way I wanted.

Such is life in the IT world. If you don’t have a good backup you at least need to have a good resume. Fortunately, I have one of the two at the moment.

I’m also getting boot loops on multiple vanilla installs that I haven’t even configured yet.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by shadowsbane0** [comment]
Issue #180 can be closed.

Sent from my iPhone

On Jan 5, 2022, at 10:45 AM, Tech Perplexed ***@***.***> wrote:

﻿

You are absolutely correct! It's been changed. Let me know if that sorted it for you :)

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTechPerplexed%2FGooby%2Fissues%2F190%23issuecomment-1005840140&data=04%7C01%7C%7Cd719eedcb1394afd000308d9d0625b88%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769943126415049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=D2O0k8CHoVAtWCAXpznJJoPcVV%2BCdzIAp85nqn%2FzkXs%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGWGOGEHGFFIF7BO3QKKMPDUURRQNANCNFSM5LJV6MWQ&data=04%7C01%7C%7Cd719eedcb1394afd000308d9d0625b88%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769943126415049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CFjdvJDK1H82ah5SG%2BLVkxlqajaaJYCCPx9krTOjV5M%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cd719eedcb1394afd000308d9d0625b88%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769943126415049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iardBzm8vdzJJU57QjShUp%2F9w1KAmAWze%2F0g%2BXIJ12k%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cd719eedcb1394afd000308d9d0625b88%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769943126415049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=X7TsD1mkof8NdO3iLucwDk1NtcHM5Yqa49eDYkdnV6w%3D&reserved=0>.

**Comment by shadowsbane0** [comment]
Sorry that was supposed to be #190

Sent from my iPhone

On Jan 5, 2022, at 10:45 AM, Tech Perplexed ***@***.***> wrote:

﻿

You are absolutely correct! It's been changed. Let me know if that sorted it for you :)

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTechPerplexed%2FGooby%2Fissues%2F190%23issuecomment-1005840140&data=04%7C01%7C%7Cd719eedcb1394afd000308d9d0625b88%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769943126415049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=D2O0k8CHoVAtWCAXpznJJoPcVV%2BCdzIAp85nqn%2FzkXs%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGWGOGEHGFFIF7BO3QKKMPDUURRQNANCNFSM5LJV6MWQ&data=04%7C01%7C%7Cd719eedcb1394afd000308d9d0625b88%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769943126415049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CFjdvJDK1H82ah5SG%2BLVkxlqajaaJYCCPx9krTOjV5M%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cd719eedcb1394afd000308d9d0625b88%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769943126415049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iardBzm8vdzJJU57QjShUp%2F9w1KAmAWze%2F0g%2BXIJ12k%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cd719eedcb1394afd000308d9d0625b88%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769943126415049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=X7TsD1mkof8NdO3iLucwDk1NtcHM5Yqa49eDYkdnV6w%3D&reserved=0>.

**Comment by TechPerplexed** [comment]
Done :)
