### ISSUE TITLE
Implant AutoRclone into Rclone

### ISSUE THREAD

**Issue by Deadly-Ghost** [TechPerplexed/Gooby#191]
Hey 

first thing i wanne say amazing scripts and love the outlays of everything keep up the good work 👍👍

my request goes to implant AutoRclone to use services account and bypass the 750 Gb limit into the Rclone there already are implanted into that amazing script 

let me know if you’re need anything else to get this resolved 👍😎

**Comment by Deadly-Ghost** [comment]
Ups it should have been in pull Request instead sry about that 🙈

**Comment by TechPerplexed** [comment]
Thanks for the suggestion 😃 I can't say I know anything about AutoRclone, is it an alternative to Rclone? I'm not so very keen on adding a service that bypasses Google's API limits, but that is the beauty of our system - you can adapt it to your needs and bypass what we supply in any way you see fit 😄

**Comment by Deadly-Ghost** [comment]
AutoRclone are a addon to Rclone to use SA insted of the original Rclone 

Here are some information about AutoRclone https://github.com/williamjohnstone/AutoRclone-Rewrite

I don't know how to implant that scripts into gobby 🥲 so it works with it in you script

**Comment by TechPerplexed** [comment]
Thanks :) And not knowing how to implement that script in Gooby: that makes two of us 😆 
Right now I feel it's outside the scope of what Gooby is about, so I'll close this for now... but willing to reopen if new insights occur :)
