### ISSUE TITLE
Mergerfs failure

### ISSUE THREAD

**Issue by shadowsbane0** [TechPerplexed/Gooby#192]
Can I ask how you are getting mergerfs to work on anything above version 2.28? When I install Rclone on a vanilla installation of Debian 11 mergerfs fails to start. Installed version is mergerfs version: 2.31.0. I had the same issue on Ubuntu. I can work around it by getting the 2.28 deb and mark it hold but that shouldn't be required. Can you verify any depreciated options in your script and/or add a version check with corrected options for mergerfs >2.28?

● mergerfs.service - MergerFS overlay writable storage and local mount

     Loaded: loaded (/etc/systemd/system/mergerfs.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-01-06 08:37:27 EST; 11min ago
    Process: 43379 ExecStartPre=/bin/mkdir -p ${UPLOADS} ${MEDIA} ${LOCALFILES} (code=exited, status=0/SUCCESS)
    Process: 43380 ExecStart=/usr/bin/mergerfs -o use_ino,hard_remove,auto_cache,sync_read,allow_other,category.action=all,category.create=ff ${UPLOADS}:${LOCALFILES}:${RCLONEMOUNT} ${MEDIA} (code=exited, status=1/FAILURE)
        CPU: 9ms

Jan 06 08:37:27  systemd[1]: mergerfs.service: Scheduled restart job, restart counter is at 5.
Jan 06 08:37:27  systemd[1]: Stopped MergerFS overlay writable storage and local mount.
Jan 06 08:37:27  systemd[1]: mergerfs.service: Start request repeated too quickly.
Jan 06 08:37:27  systemd[1]: mergerfs.service: Failed with result 'exit-code'.
Jan 06 08:37:27  systemd[1]: Failed to start MergerFS overlay writable storage and local mount.
~

**Comment by Deadly-Ghost** [comment]
You can try 

sudo systemctl daemon-reload
sudo systemctl stop mergerfs
sudo systemctl stop rclonefs
/bin/fusermount -uz /mnt/rclone
/bin/fusermount -uz /mnt/google

and after that try run rclean and see it’s help with your problem

**Comment by shadowsbane0** [comment]
It does this on the initial install. I’ve also used that work around before and again. Same result.

Reading the man for this version I see auto_cache and sync_read are depreciated options. I don’t know if they were completely killed in the higher versions or they conflict with fuser now. I’m still digging.

I mostly wanted to see if others had this issue and/or how they fixed it.

Sent from my iPhone

On Jan 6, 2022, at 9:14 AM, Deadly-Ghost ***@***.***> wrote:

﻿

You can try

sudo systemctl daemon-reload
sudo systemctl stop mergerfs
sudo systemctl stop rclonefs
/bin/fusermount -uz /mnt/rclone
/bin/fusermount -uz /mnt/google

and after that try run rclean and see it’s help with your problem

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTechPerplexed%2FGooby%2Fissues%2F192%23issuecomment-1006622896&data=04%7C01%7C%7C8c930e95417a4c5949f508d9d11ecc68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770752478126517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vDaA%2BkIvsp6Q8t8RuefoF4xrZrcpIrYvHfkxouXpcTs%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGWGOGD5QFOWZPWBOJGXGLTUUWPS3ANCNFSM5LMNACWA&data=04%7C01%7C%7C8c930e95417a4c5949f508d9d11ecc68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770752478126517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=isaS1fOhdurtlS%2FAvb726qexvnbVqpLcc3EGaK7zlUY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C8c930e95417a4c5949f508d9d11ecc68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770752478126517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OPoDmqgyggQ9iRtEtZkvTcqNLGn8%2FEwiSz%2BztIpnrh0%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C8c930e95417a4c5949f508d9d11ecc68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770752478126517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7ZledFHpjrFNkvsGbv2OaOSgQqRwU7lms%2BmMJyL9lEg%3D&reserved=0>.

**Comment by TechPerplexed** [comment]
I've had little luck with Debian 11 myself... but in my case MergerFS croaked out on permissions. Could you try to comment out the 

User=<you>
Group=<you>

lines and see if that brings it up without issues?

**Comment by shadowsbane0** [comment]
The only other piece of information to factor as a possible culprit is how my filesystem is configured. My host system has three 1TB m2 SSDs and another 1TB SATA SSD.

I’ve configured them the m2s with btrfs striped raid0 on this Debian install. My previous Ubuntu install I used LVM and the onboard raid controller which I later found out wasn’t truely a hardware raid option.

Because it wasn’t I decided I wanted to use btrfs this go round for the dedupe and snapshot capability. I also have the SATA as a standard NTFS drive for critical files onboard backup.

Btrfs provides the ability to quickly add additional drives if I want to - I’m preparing to go back to bare metal when big-g decides to force me into their new tiered business plan model. I can easily add a JOBD array and use btrfs for my raid options without braking the bank.

On the Ubuntu build there wasn’t an issue until I updated the distro from 20.04 to 21.10 and a newer version of mergrfs was installed. Debian 11 is my current OS and suffers from the same issue of newer mergerfs version.

Sent from my iPhone

On Jan 6, 2022, at 10:30 AM, Brian Curry ***@***.***> wrote:

﻿ It does this on the initial install. I’ve also used that work around before and again. Same result.

Reading the man for this version I see auto_cache and sync_read are depreciated options. I don’t know if they were completely killed in the higher versions or they conflict with fuser now. I’m still digging.

I mostly wanted to see if others had this issue and/or how they fixed it.

Sent from my iPhone

On Jan 6, 2022, at 9:14 AM, Deadly-Ghost ***@***.***> wrote:

﻿

You can try

sudo systemctl daemon-reload
sudo systemctl stop mergerfs
sudo systemctl stop rclonefs
/bin/fusermount -uz /mnt/rclone
/bin/fusermount -uz /mnt/google

and after that try run rclean and see it’s help with your problem

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTechPerplexed%2FGooby%2Fissues%2F192%23issuecomment-1006622896&data=04%7C01%7C%7C8c930e95417a4c5949f508d9d11ecc68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770752478126517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vDaA%2BkIvsp6Q8t8RuefoF4xrZrcpIrYvHfkxouXpcTs%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGWGOGD5QFOWZPWBOJGXGLTUUWPS3ANCNFSM5LMNACWA&data=04%7C01%7C%7C8c930e95417a4c5949f508d9d11ecc68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770752478126517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=isaS1fOhdurtlS%2FAvb726qexvnbVqpLcc3EGaK7zlUY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C8c930e95417a4c5949f508d9d11ecc68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770752478126517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OPoDmqgyggQ9iRtEtZkvTcqNLGn8%2FEwiSz%2BztIpnrh0%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C8c930e95417a4c5949f508d9d11ecc68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770752478126517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7ZledFHpjrFNkvsGbv2OaOSgQqRwU7lms%2BmMJyL9lEg%3D&reserved=0>.

**Comment by shadowsbane0** [comment]
That did bring it up.

Sent from my iPhone

On Jan 6, 2022, at 11:15 AM, Brian Curry ***@***.***> wrote:

﻿ The only other piece of information to factor as a possible culprit is how my filesystem is configured. My host system has three 1TB m2 SSDs and another 1TB SATA SSD.

I’ve configured them the m2s with btrfs striped raid0 on this Debian install. My previous Ubuntu install I used LVM and the onboard raid controller which I later found out wasn’t truely a hardware raid option.

Because it wasn’t I decided I wanted to use btrfs this go round for the dedupe and snapshot capability. I also have the SATA as a standard NTFS drive for critical files onboard backup.

Btrfs provides the ability to quickly add additional drives if I want to - I’m preparing to go back to bare metal when big-g decides to force me into their new tiered business plan model. I can easily add a JOBD array and use btrfs for my raid options without braking the bank.

On the Ubuntu build there wasn’t an issue until I updated the distro from 20.04 to 21.10 and a newer version of mergrfs was installed. Debian 11 is my current OS and suffers from the same issue of newer mergerfs version.

Sent from my iPhone

On Jan 6, 2022, at 10:30 AM, Brian Curry ***@***.***> wrote:

﻿ It does this on the initial install. I’ve also used that work around before and again. Same result.

Reading the man for this version I see auto_cache and sync_read are depreciated options. I don’t know if they were completely killed in the higher versions or they conflict with fuser now. I’m still digging.

I mostly wanted to see if others had this issue and/or how they fixed it.

Sent from my iPhone

On Jan 6, 2022, at 9:14 AM, Deadly-Ghost ***@***.***> wrote:

﻿

You can try

sudo systemctl daemon-reload
sudo systemctl stop mergerfs
sudo systemctl stop rclonefs
/bin/fusermount -uz /mnt/rclone
/bin/fusermount -uz /mnt/google

and after that try run rclean and see it’s help with your problem

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTechPerplexed%2FGooby%2Fissues%2F192%23issuecomment-1006622896&data=04%7C01%7C%7C8c930e95417a4c5949f508d9d11ecc68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770752478126517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vDaA%2BkIvsp6Q8t8RuefoF4xrZrcpIrYvHfkxouXpcTs%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGWGOGD5QFOWZPWBOJGXGLTUUWPS3ANCNFSM5LMNACWA&data=04%7C01%7C%7C8c930e95417a4c5949f508d9d11ecc68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770752478126517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=isaS1fOhdurtlS%2FAvb726qexvnbVqpLcc3EGaK7zlUY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C8c930e95417a4c5949f508d9d11ecc68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770752478126517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OPoDmqgyggQ9iRtEtZkvTcqNLGn8%2FEwiSz%2BztIpnrh0%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C8c930e95417a4c5949f508d9d11ecc68%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770752478126517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7ZledFHpjrFNkvsGbv2OaOSgQqRwU7lms%2BmMJyL9lEg%3D&reserved=0>.

**Comment by TechPerplexed** [comment]
Right, I'm reluctant to change that permanently just yet, because I'm not sure what the implications are for older/other installations. I'm hoping that at least for now that solves your issue :)

**Comment by shadowsbane0** [comment]
I don’t get what’s going on. It’s a clean build of Debian 11, Gooby installed vanilla, and some containers are stable and some are bootlooping.

In no order other than docker ps output.

Autoheal, watchtower, jellyfin, NGINX, letsencrypt, netdata, organizr, tautulli, and emby are all stable.

Sonarr, Radarr, Portainer, jackett, deluge, Ombi, and Plex are all bouncing about every 30 sec and rebooting.

What would be different about Debian than Ubuntu? These are all vanilla Gooby installs.

I looked through the .yaml’s and couldn’t see anything that would cause this.

Sent from my iPhone

On Jan 6, 2022, at 11:21 AM, Tech Perplexed ***@***.***> wrote:

﻿

Right, I'm reluctant to change that permanently just yet, because I'm not sure what the implications are for older/other installations. I'm hoping that at least for now that solves your issue :)

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTechPerplexed%2FGooby%2Fissues%2F192%23issuecomment-1006720936&data=04%7C01%7C%7Cc163161553db478fbe6808d9d130a549%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770829130274350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bg3emttcBGlta392U73%2Bw4JPNIq9bDCGa%2F2wVHk%2FBWw%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGWGOGGDK6TTJD5D3XMU5DDUUW6R5ANCNFSM5LMNACWA&data=04%7C01%7C%7Cc163161553db478fbe6808d9d130a549%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770829130274350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UAjJdyJDt%2FjJDlUxhBMDX0UiOW5HIR9RG5HSk1mzpc4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cc163161553db478fbe6808d9d130a549%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770829130274350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4lKABpPizhy78Z5bq7Bn7L5zLw5jNoEKU5aKX2zTiBA%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cc163161553db478fbe6808d9d130a549%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770829130274350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9kHp0Z%2F97QRUWq1Pxi0AbfbbFp9ZjDYCE9uhNvFrnw0%3D&reserved=0>.

**Comment by shadowsbane0** [comment]
Sorry Emby is also bouncing.

Sent from my iPhone

On Jan 6, 2022, at 2:20 PM, Brian Curry ***@***.***> wrote:

﻿ I don’t get what’s going on. It’s a clean build of Debian 11, Gooby installed vanilla, and some containers are stable and some are bootlooping.

In no order other than docker ps output.

Autoheal, watchtower, jellyfin, NGINX, letsencrypt, netdata, organizr, tautulli, and emby are all stable.

Sonarr, Radarr, Portainer, jackett, deluge, Ombi, and Plex are all bouncing about every 30 sec and rebooting.

What would be different about Debian than Ubuntu? These are all vanilla Gooby installs.

I looked through the .yaml’s and couldn’t see anything that would cause this.

Sent from my iPhone

On Jan 6, 2022, at 11:21 AM, Tech Perplexed ***@***.***> wrote:

﻿

Right, I'm reluctant to change that permanently just yet, because I'm not sure what the implications are for older/other installations. I'm hoping that at least for now that solves your issue :)

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTechPerplexed%2FGooby%2Fissues%2F192%23issuecomment-1006720936&data=04%7C01%7C%7Cc163161553db478fbe6808d9d130a549%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770829130274350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bg3emttcBGlta392U73%2Bw4JPNIq9bDCGa%2F2wVHk%2FBWw%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGWGOGGDK6TTJD5D3XMU5DDUUW6R5ANCNFSM5LMNACWA&data=04%7C01%7C%7Cc163161553db478fbe6808d9d130a549%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770829130274350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UAjJdyJDt%2FjJDlUxhBMDX0UiOW5HIR9RG5HSk1mzpc4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cc163161553db478fbe6808d9d130a549%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770829130274350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4lKABpPizhy78Z5bq7Bn7L5zLw5jNoEKU5aKX2zTiBA%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cc163161553db478fbe6808d9d130a549%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770829130274350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9kHp0Z%2F97QRUWq1Pxi0AbfbbFp9ZjDYCE9uhNvFrnw0%3D&reserved=0>.

**Comment by TechPerplexed** [comment]
Wow, that's very strange indeed. I didn't have that on Debian 11. However, for now, I'd probably suggest you go with Debian 10... I don't think you'll have any of those issues.

In time Debian 11 will be fully supported (stay tuned for some exciting future updates, she said mysteriously...) but for now Debian 10 is probably your best bet!

**Comment by shadowsbane0** [comment]
I have no idea what was causing the containers to bounce but the good news is I found my backup. It was in the root of my GDrive even though I don’t have rclone set to mount it. It wouldn’t restore automatically after downloading - I got a no backup error at the end. I manually restored it and everything’s seems to be back up and running now. I don’t know if rolling down to Debian 10 helped but I’m satisfied for now since it saved me a LOT of tedious configuration tasks.

I guess I don’t need that resume after all.

I only have to wait for everything to finish indexing again. It was only partial from the previous permission issues I had.

Sent from my iPad

On Jan 6, 2022, at 14:27, Tech Perplexed ***@***.***> wrote:

﻿

Wow, that's very strange indeed. I didn't have that on Debian 11. However, for now, I'd probably suggest you go with Debian 10... I don't think you'll have any of those issues.

In time Debian 11 will be fully supported (stay tuned for some exciting future updates, she said mysteriously...) but for now Debian 10 is probably your best bet!

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTechPerplexed%2FGooby%2Fissues%2F192%23issuecomment-1006872871&data=04%7C01%7C%7C1e1a99689e344906518908d9d14a8b95%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770940375414591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9ulxO0VQPDjMFRdl5IvJbdoM%2FaoODp3X6FwjvV1660Q%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGWGOGEMTBLVIXE737QIEZTUUXUJDANCNFSM5LMNACWA&data=04%7C01%7C%7C1e1a99689e344906518908d9d14a8b95%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770940375414591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6Uw4vASe01BGuldXSIioUmndaD1ghDtC6R1LG9M8IFY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C1e1a99689e344906518908d9d14a8b95%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770940375414591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Bk8%2Bk%2BHF5wp2Kr8iqJSO1J7rVWIQ648L%2Bcrpvp2jJSM%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C1e1a99689e344906518908d9d14a8b95%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637770940375414591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3boxNJoX2D11z3FikFJ04UxgwrF68xxb4ihnmpk1kKs%3D&reserved=0>.

**Comment by TechPerplexed** [comment]
So it's been resolved now? At least in a fashion?

**Comment by shadowsbane0** [comment]
Completely on my end, though I feel it had more to do with the restoration of the backup. So thumbs up for the backup script. It really saved my spouse a lot of grief with me spending too much time reconfiguring.

Sent from my iPad

On Jan 8, 2022, at 19:24, Tech Perplexed ***@***.***> wrote:

﻿

So it's been resolved now? At least in a fashion?

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTechPerplexed%2FGooby%2Fissues%2F192%23issuecomment-1008194998&data=04%7C01%7C%7Cfe370c6a08284bec262908d9d306577b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637772846455744614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BUI6%2FjbX576aK76OjMtBQaWRxrPqm5MMkvFJG%2FcwENE%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGWGOGDUX7TTQ3X4QSSNRTTUVDISHANCNFSM5LMNACWA&data=04%7C01%7C%7Cfe370c6a08284bec262908d9d306577b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637772846455744614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zKTqz1v72mKC%2BsRd2Xg%2Fjsc75GrS8e2o1J9EplxQfPw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cfe370c6a08284bec262908d9d306577b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637772846455744614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6TEWecJBljtnLaXEK72rLrwA02QBamxDFBfnW7GbQ98%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cfe370c6a08284bec262908d9d306577b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637772846455744614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=A22qoX3n8AO5pAS6YbCXeQEqgAyoL77WL916esUKcj0%3D&reserved=0>.

**Comment by TechPerplexed** [comment]
Happy to hear it 😸
