### ISSUE TITLE
How to upoad once a day on Gdrive

### ISSUE THREAD

**Issue by Mrpommes** [TechPerplexed/Gooby#193]
Hi mate, thanks for your work !
Everything work perfectly.
i'm searching to upload only once a day on gdrive at 3A.M for exemple, can you help me please ?

Thanks

**Comment by TechPerplexed** [comment]
Sure, that's easy... edit your crontab with `crontab -e`, then change this line 

`0,15,30,45 * * * * /opt/Gooby/scripts/cron/syncmount.sh > /dev/null 2>&1`

to

`0 3 * * * /opt/Gooby/scripts/cron/syncmount.sh > /dev/null 2>&1`

This runs the cron once a day at 3AM sharp. 

Edit: sorry, edited to run at 3AM sharp and not every minute!

**Comment by Mrpommes** [comment]
Thanks a lot mate !
