### ISSUE TITLE
crypt rclone

### ISSUE THREAD

**Issue by Mrpommes** [TechPerplexed/Gooby#194]
Sorry for another easy question, i'm learning from 0 and asking obvious questions...
i have create a new remote to encrypt my files in Drive, but i don't understand what should i change to use it
Can you help me one more time please ?

thanks

**Comment by TechPerplexed** [comment]
Sorry, I don't encryption myself... perhaps someone who does can help you there :)

**Comment by Deadly-Ghost** [comment]
Did you also create a crypt Remote ?
