### ISSUE TITLE
plex  / portainer / organizr gives me NET::ERR_CERT_AUTHORITY_INVALID 

### ISSUE THREAD

**Issue by Deadly-Ghost** [TechPerplexed/Gooby#196]
hey 

i have a questioin about NET::ERR_CERT_AUTHORITY_INVALID

plex  / portainer / organizr gives me this error all the time but sonarr / radarr works perfect 

what i have did to troubleshoot

checked : reinstalled gooby 
checked : made a rclean system
checked : UFW for missing open port and all port are open like they should 
checked : container logs nothing 
have oldmost read all post about gooby to see if i can see a comparisons with mine but no luck 

hope your have the magic answer  so i can get it up and running ASAP :)

let me know if your need more informations so i can salt my problem :)

**Comment by TechPerplexed** [comment]
Ok a few things here... :)

First, never open ports on the UFW for apps that go through Gooby. Seriously, Gooby takes care of the ports so that you won't have to. Opening them manually potentially sets you up for all kinds of trouble..

Second, Plex is an odd duck, and it's hard to get the domain to work. If you can access it through https://app.plex.tv you won't have to worry about it.

Organizr: are you sure you're accessing it though menu.yourdomain instead of organizr.yourdomain?

As for Portainer, I wouldn't know really...  could it be that you have exceeded the 50 certificates per week and are in a temporary lockdown at Let's Encrypt? How long have you had this issue?

**Comment by Deadly-Ghost** [comment]
Thanks for you replay :)

So i can remove port 443 / 8443 from  ufw I have tryed to use to get access Plex and so on 

About Plex access when i log on to Plex.tv and enter settings I can see Plex new user but it says unable to connect to server 

When i try enter organizr.mydomain I can't get access to site 

Does it work if i do menu.mydomain? Haven't tryed that command b4 

The issue have been around for a week now

**Comment by TechPerplexed** [comment]
Yes don't add those ports to the UFW, it won't make a difference for Plex anyway. Did you follow the steps to get your token for Plex when you first installed Plex?

And you are correct, change organizr in your DNS settings to menu and you should be able to access your site. Alternatively, you can edit the yaml file in `/var/opt/Gooby/Docker/components` and change menu.${DOMAIN} to organizr.${DOMAIN}

**Comment by Deadly-Ghost** [comment]
Yes i have followed the guide you made but nothing happens when i try Plex.mydomain.com:8443 like the guide says 

But I can see new Plex server but i can't connect to it and i things it should be walk the line but no luck 🥲😎

Ahh dident know i should change from org to menu nice to know mate 👌👍

**Comment by TechPerplexed** [comment]
Right, but you you did get your token from plex.tv/claim right? Did Plex work on your server before?

**Comment by Deadly-Ghost** [comment]
> Right, but you you did get your token from plex.tv/claim right? Did Plex work on your server before?

Yeah got the link from token and use it in goby like normal but when i enter Plex app linket it can see the server but spinning around and try connect to it with no luck I can use it and setup up my library and so on

**Comment by Deadly-Ghost** [comment]
yeah got the link from token and use it in gooby like normal but when i enter Plex app linket it can see the server but spinning around and try connect to it with no luck I cant use it and setup up my library and so on

it keeps saying Unable to connect to "myplexserver (not real name)" securely.

**Comment by TechPerplexed** [comment]
Strange. You might try and enable remote access in Plex. Make sure you manually specify the port as 8443!

![Screenshot 2022-01-17 15 14 03](https://user-images.githubusercontent.com/15312691/149842710-c4714356-5be8-4dd0-9d35-a5f67b998af2.jpg)

Does that make a difference for you? You're not behind a double firewall are you (is your server in house or external?)

**Comment by Deadly-Ghost** [comment]
I can't even get to manual set port 8443 it keeps failing on connection on indirect connection

Any solution what i can try?

It a home server with buyed domain and dns are forwarding to my server and works 

My local router have open ports for plex 32400 / 8443 and rest container installed dockers

**Comment by Deadly-Ghost** [comment]
Will it help to try switch proxy?

**Comment by TechPerplexed** [comment]
Well, I have bad news and "not so good" news there.

The bad news: unfortunately I too had the same issue with Plex in house... it does indeed seem that you have a problem there. Hoping there are some Gooby users who managed to work around this issue... fingers crossed!

The not so good news: unfortunately there is no other proxy yet. We are working very hard behind the scenes on an updated version of Gooby (and in top secret too, so if you tell anyone we may have to silence you)🤣 but... no expected delivery date I'm afraid. These things take as long as they take 😞

**Comment by Deadly-Ghost** [comment]
got it solved by trying one of my other domains now I have access via https (probably some rate limit from letsencrypt) dosent matter got it working :)

then i have another problem it still gets indirect to direct but loses connection often so can't scan my libraries
any solutions for that ?

**Comment by TechPerplexed** [comment]
Sorry I was leaving this open hoping someone would know what to do... perhaps you could try the Plex forums to see how to handle a double firewall?
