### ISSUE TITLE
Gooby won't update (because master branch has been removed?)

### ISSUE THREAD

**Issue by bifa2** [TechPerplexed/Gooby#197]
Hi,

I decided to do some server maintenance today including updating Gooby and it appears the `master` branch no longer exists for this repo:

```
Updating Gooby to master

Cloning into '/opt/.Gooby'...
fatal: Remote branch master not found in upstream origin
```

What should our local installations be tracking now?

Cheers!

**Comment by TechPerplexed** [comment]
Haha oh wow, you must have not run the cleanup for several months 😆 The solution is super simple: just run
`echo "v2" > /var/local/Gooby/Docker/.config/goobybranch` and then `rclean`.

That should sort it :)

**Comment by bifa2** [comment]
That worked, thanks @TechPerplexed :)
