### ISSUE TITLE
Ombi yaml file correction

### ISSUE THREAD

**Issue by shadowsbane0** [TechPerplexed/Gooby#198]
The yaml file for Ombi has an error in the volume line. It is cross linked to Organizr currently reads ${ORGANIZRNAME} as opposed to ${OMBINAME}.

**Comment by TechPerplexed** [comment]
Thanks so much for being a tester for our brand new OmniStream 😁

I see that you opened a ticket on that GitHub as well, so I'll close this one. Please please post any issues with Omni over there... It is maintained by @kelinger and myself. He's the one with all the brains 🤣

And it gets confusing to try and sort issues with Omni over here. Thanks! 💖
