### ISSUE TITLE
NetData DOA

### ISSUE THREAD

**Issue by shadowsbane0** [TechPerplexed/Gooby#199]
NetData is DOA for me. Logs producing “ standard_init_linux.go:228: exec user process caused: no such file or directory” error. Was working on Gooby. Not working on Omni clean install.

**Comment by TechPerplexed** [comment]
Thanks for the report, @shadowsbane0 
It's so great to finally have someone to sneakily find OmniStream and test the waters 😁

As I said in the other issue, would you please mind reposting this on the proper GitHub project? Then @kelinger and myself can address it there.

I'll close all your tickets here and even if you don't want to repost, I promise we'll still try to sort them all the same!
