### ISSUE TITLE
Ombi DOA

### ISSUE THREAD

**Issue by shadowsbane0** [TechPerplexed/Gooby#200]
Ombi is also DOA. It is stuck in a restart loop.

Log as follows:

Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
Ombi - Patreon: https://patreon.com/tidusjar
Ombi - PayPal: https://paypal.me/PlexRequestsNet
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Hello, welcome to Ombi
Valid options are:
Ombi 4.10.2
Copyright (C) 2022 Ombi
  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
               URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "localhost" to indicate that the server
               should listen for requests on any IP address or hostname using
               the specified port and protocol (for example,
               http://localhost:5000). The protocol (http:// or https://) must
               be included with each URL. Supported formats vary between
               servers.
  --storage    Storage path, where we save the logs and database
  --baseurl    The base URL for reverse proxy scenarios
  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...
  --migrate    Will run the migrations then exit the application
  --help       Display this help screen.
  --version    Display version information.
Wrote new baseurl at /opt/ombi/ClientApp/dist/index.html
We are running on http://*:3579

i
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by TechPerplexed** [comment]
Issue with OmniStream 🙂
