### ISSUE TITLE
Portainer correction

### ISSUE THREAD

**Issue by shadowsbane0** [TechPerplexed/Gooby#201]
The image line fails to pull Portainer. Corrected to “portainer/portainer-ce”. Works now.

**Comment by TechPerplexed** [comment]
It's that a Gooby issue?

**Comment by shadowsbane0** [comment]
No these are all Omni issues that I posted on the Omni branch but somehow all posted to the Gooby branch.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by TechPerplexed** [comment]
Ok then, I'll close this one and inform @kelinger 🙂

**Comment by shadowsbane0** [comment]
Sorry, I forgot the section of meet us on the OmniStream Github. Mea culpa.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by TechPerplexed** [comment]
Absolutely no worries!!! This is new to all of us 😊
