### ISSUE TITLE
Media variable

### ISSUE THREAD

**Issue by shadowsbane0** [TechPerplexed/Gooby#203]
During setup when offered to set the media folder for the ${Media} variable it doesn’t keep the change. It still mounts as /cloud/Media instead of the location I set. I can’t rename my file structure at this time because I’m in the process of pulling 45TB off of GSuite to bare metal. I got tired of bumping into the new file access rules they’ve put in. In another week I’ll have it done and can rename my top folder and make things easier for myself. In the mean time I’ve had to do some creative mount options with rclone and rsync options. To keep access to my media content while I wait for everything to synch up to local storage. I’ve left deluge un-configured to prevent new content from being uploaded.

**Comment by TechPerplexed** [comment]
Definitely a bug that should be sorted, thanks!! You should not need to rename your folder. Your report had been sent to @kelinger 😊
