### ISSUE TITLE
Issue with Deluge

### ISSUE THREAD

**Issue by GOODBOIXD** [TechPerplexed/Gooby#205]
My previous setup with gooby worked flawlessly. However, I tried setting it up on a new vps, and deluge seems to not work properly. 

"Last output	OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: no such file or directory: unknown" is the error that I get on Portainer, the container just keeps restarting itself. 

Using Debian GNU/Linux 10 (buster)

**Comment by TechPerplexed** [comment]
Hmm, so just Deluge is being difficult on your server?

**Comment by TechPerplexed** [comment]
I can confirm that Deluge wasn't working properly. I have updated the image link and disabled the health check, can you please uninstall and reinstall Deluge and see if it works now?

**Comment by GOODBOIXD** [comment]
> I can confirm that Deluge wasn't working properly. I have updated the image link and disabled the health check, can you please uninstall and reinstall Deluge and see if it works now?

Yes, updated gooby and seems to work now. Thank you for the quick fix.
