### ISSUE TITLE
Everything seams gone after server reboot

### ISSUE THREAD

**Issue by ivankozlik** [TechPerplexed/Gooby#206]
Hi, I'm new to gooby but I like ti very much. I don't understand why after server reboot there seams nothing is installed or running and in the gooby menus there are no easy way of "get back to running mode after server reboot". 

How to get everything running easily without a need of installing everything again?

**Comment by TechPerplexed** [comment]
Well, first we need to establish what exactly goes wrong :) Can you run `rclean` and report back on what happens?

**Comment by ivankozlik** [comment]
Hi, let me elaborate more. I upgraded server to v4 cores. When that was done there is a server reboot happening. After it came alive I SSH to it and saw that again there seams like no rclone and plex were installed. I did run rclone installation and it immediately found previous Mounts and same with the Plex. But my question is - after the server reboots what one needs to do to get everything running again since it seams that system does not start it self?

I did run rclean and there are no errors, everything stops, updates and runs again.

**Comment by TechPerplexed** [comment]
How did you create your user? Through Gooby? Did rclean ask for a password somewhere?

**Comment by ivankozlik** [comment]
Yes, I created the user trough gooby. No, the rclean did not ask for any passwords.

**Comment by TechPerplexed** [comment]
Hmm, so rclean runs without issues, right? No waiting for mounts etc, but it doesn't run after a reboot? Can you check if the cron exists to run rclean after a reboot?

**Comment by ivankozlik** [comment]
How can I check if that cron exists? :)

**Comment by TechPerplexed** [comment]
Type `crontab -e` and see what it lists on the line that mentions @reboot.
If you pick nano as your editor, you can exit it with Ctrl-X.

**Comment by ivankozlik** [comment]
```
@reboot /opt/Gooby/scripts/cron/rclean.sh > /dev/null 2>&1
0,15,30,45 * * * * /opt/Gooby/scripts/cron/syncmount.sh > /dev/null 2>&1
15 2 * * SUN /opt/Gooby/scripts/cron/backup.sh > /dev/null 2>&1
10 2 1 * * /bin/resetbackup > /dev/null 2>&1
```


I'm again in process of scanning the library files. After it completes I can do testing of rebooting the server again to see if the rclean will run and if everything will be normal.

**Comment by TechPerplexed** [comment]
Right, let me know. At boot it runs the exact same rclean that you just ran manually, so if that goes without a hitch, really it should work with a reboot as well. If not, we'll continue the troubleshooting :)
