### ISSUE TITLE
Radarr errors and healthcheck failures

### ISSUE THREAD

**Issue by mr-handerson** [TechPerplexed/Gooby#207]
Just noticed that my Radarr is unhappy. It is failing healthcheck and continually restarting. When I can get in there is a System message 

" This image is now based on Alpine. Custom scripts using apt-get will need to be updated to use apk"

I am assuming related?

I am going to try temporarily disabling the healthcheck to stop them from restarting at least.

**Comment by TechPerplexed** [comment]
Thanks for the heads up, let me look into this :)

**Comment by mr-handerson** [comment]
NVM. Looks like it is just related to the warning message itself, and there is a pull in the image to remove said message.

https://github.com/linuxserver/docker-radarr/pull/178

I'll wait for it to come through and confirm the healthcheck resolves and then I'll close this up.

Sorry, I was at work so didn't have time to check thoroughly before posting.

**Comment by TechPerplexed** [comment]
No worries, let me know how it goes. I'm sure it will help others :)

Heads up: at some point in a not overly distant future, Gooby will be superseded (not replaced) by a very much updated and improved version: https://github.com/kelinger/OmniStream

More here :) https://github.com/TechPerplexed/Gooby/tree/omni

**Comment by mr-handerson** [comment]
Thanks. Now just impatiently waiting for the new release and image update haha.

Yes, I have been following along, but am hesitant to dive in until Omni is declared as ready for prime time, and when I have sufficient time available in case things go wrong. Up until this issue, everything has been humming along wonderfully and I am very much of the 'if it ain't broke' attitude given my previous adventure when I decided to poke at things just because. So at some point I will probably take the plunge, but for now Gooby is perfectly adequate.

**Comment by TechPerplexed** [comment]
Haha no worries, is not going to disappear. If it works for you, by all means keep using it indefinitely!

**Comment by mr-handerson** [comment]
Hmm. So the image updated, and the in app message has been removed per the update. However, radarr is still marked as unhealthy.

Turns out I was still on Gooby 2.2.2 hah, that's how long since I've last touched anything because it's been working so well. 
Anyway; first thing I did was to resolve that. Had to refer to some previous threads to get that all fixed and working
https://github.com/TechPerplexed/Gooby/issues/197
https://github.com/TechPerplexed/Gooby/issues/185 (including the remove and re-install rclone step)
That all finally succeeded and I was able to run rclean
I also rebooted my server for good measure

However, Radarr is still unhealthy.
The error message in Portainer is 
"OCI runtime exec failed: exec failed: unable to start container process: exec /bin/sh: no such file or directory: unknown"

At this point I am now stuck. I've tried to do some research and compare to working containers but I haven't been able to make any headway. So hoping for some assistance at this point, thanks in advance.

EDIT: I should add that Radarr seems to be actually running and working. However, I had to stop autoheal, otherwise it kept just restarting the container. So, neither part is optimal. I'd like to try and get everything back to running and Healthy.

EDIT2: So it is related to the healthcheck, which is 
_test: ["CMD-SHELL", "netstat -ntlp | grep :7878 && mountpoint /Media"]_
Which is the same format as the other containers, so I'm not sure why there is an issue for Radarr
I temporarily commented out the healthcheck to stop it from constantly restarting the container

**Comment by ffwjb** [comment]
@mr-handerson @TechPerplexed I don't want hijack your issue but I think we have the same issue.

I also have an issue with Radarr not starting. When I run a cleanup it doesnt start at all and when I run it through the menu it creates a container, 
I get the following error: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/usr/bin/killall" to rootfs at "/usr/bin/killall": mount /usr/bin/killall:/usr/bin/killall (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by TechPerplexed** [comment]
@mr-handerson I have disabled the health check for new installations until we know what's causing this :)

@ffwjb try to reinstall Radarr with the updated yaml version (or manually comment out the health check) and see if that sorts things for you...

**Comment by ffwjb** [comment]
@TechPerplexed I've tried that but the issue is still the same...

**Comment by TechPerplexed** [comment]
@ffwjb Do you just get this error with Radarr? Have you tried a vanilla installation and do you still get this error then?

**Comment by ffwjb** [comment]
@TechPerplexed yes only with Radarr, it started around two weeks ago. I've changed nothing on my installation. I've tried the updated yaml version, a new install through Gooby. But the error stays the same

**Comment by TechPerplexed** [comment]
Sorry about the late reply... weird! I can't say I have experienced (or seen) that error before... have you tried the Radarr community to see if they have any ideas?

**Comment by ffwjb** [comment]
@TechPerplexed I don't know what the line: - /usr/bin/killall:/usr/bin/killall:ro does but i've comment it out and know Radarr is running again. Problem solved

**Comment by TechPerplexed** [comment]
Glad to hear it :)
