### ISSUE TITLE
Radarr DOA

### ISSUE THREAD

**Issue by mr-handerson** [TechPerplexed/Gooby#209]
Further Radarr issues.

Now it does not seem to start / stay up at all

Repeated error that shows in the log

exec /init: no such file or directory

Tried an rclean. Same result.
Have not tried removing and reinstalling yet

EDIT: It is something to do with the most recent image. I used old 4.1.0.6175-ls145 and it works fine

@bdschuster I noticed you were/are experiencing the same per the linuxserver.io discord. Did you manage to get it figured out?

**Comment by bdschuster** [comment]
@mr-handerson , i have no figured it out yet. I'm still rolled back. Are you still on Gooby, or did you move on to OMNI?

**Comment by TechPerplexed** [comment]
Could you try commenting out the line like this:

`# - /usr/bin/killall:/usr/bin/killall:ro`

And see if that solves the issue? If so, I'll update the yaml file once more...

**Comment by mr-handerson** [comment]
@bdschuster I'm still on Gooby. I've been waiting for Omni to considered more RTM I guess, and Gooby has been trucking along until the recent Radarr issues

@TechPerplexed no dice unfortunately. I commented out the line, did a full rclean but the same issue and error remains.

**Comment by TechPerplexed** [comment]
Wow, that's odd... just to verify, you did comment it out in the Radarr yaml file in components, right? Because if you comment out the assembled file, it gets overwritten with an rclean...

**Comment by mr-handerson** [comment]
Correct, from /var/local/Gooby/Docker/components/. And the volume no longer shows in the new container, so I'm pretty sure I did it correctly, and the change applied.

```
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/Radarr4K:/config
      - ${HOME}/logs:/config/logs
      - ${MEDIA}:/Media
      - ${DOWNLOADS}:/Downloads
      - /bin/netstat:/bin/netstat:ro
#      - /usr/bin/killall:/usr/bin/killall:ro
```

**Comment by TechPerplexed** [comment]
Hmm, it did sort the issue in Omni. Just for testing purposes, can you comment the line above it (/bin/netstat etc) as well?

**Comment by mr-handerson** [comment]
Huzzah!

That sorted it. Seems like it's running ok using the latest tag now.

Thanks as always! I'll leave you to update the yaml and then can close this out.

**Comment by TechPerplexed** [comment]
Done and done :)
