### ISSUE TITLE
[suggestion] Documentation wiki

### ISSUE THREAD

**Issue by deedeefink** [TechPerplexed/Gooby#21]
Since v2 now offers more or less the infinite Plex automation server I'm switching to Gooby instead of manual installing these apps :-)

However it's not always intuitive how to setup the different applications since they're running in Docker. Therefore I suggest to setup a Wiki here on GitHub to write-up a series of how-too's. I'll be happy to help :-)

As an example I've been struggling with:
- Connecting apps to apps where I would need to use the [APPNAME] instead of the URL. This applies for some, but not all (See Jackett below)
- Connecting Sonarr/Radarr to Jackett. Works now with a URL as I'm not using http auth, but I would foresee problems with http auth as one would need to add unique urls to the Torznab feed
- Plex Plugin folder is moved from it's standard location to a specific Gooby folder. So how to install plugins

And I'm sure there are others.

Let me know what you think

**Comment by deedeefink** [comment]
I was thinking to write up "How to setup [APP]". Not how to install but how to setup the apps for usages especially on how to connect internally. Ie. Sonarr to Jackett, Ombi to Radarr, Tautulli to plex etc.

The ones I'm using my self are:
- Rclone
- Plex
- Sonarr
- Radarr
- Jackett
- Ombi
- Netdata
- Tautulli

Later there could be a Troubleshooting and Tip&Tricks section for Gooby

Just some thoughts to begin with.

Or you want that on techperplexed.ga instead?

**Comment by TechPerplexed** [comment]
I'm open for suggestions, @deedeefink. We can start a wiki here, or add the to the site - it's all the same to me. It might be a good idea to leave the "basic" instructions on the site, such as how to set up a VPS and install Gooby, then move the specific instructions as you outlined above to the wiki here. What would you suggest?

**Comment by TechPerplexed** [comment]
Ok, as a test, I have opened up the wiki... go wild with it 😃 

If I notice that there are too many changes that are unwanted (talking about spam or pranks), I will confine the wiki editing to just you and myself.

Have fun and thanks for your help!!! I appreciate it.

**Comment by deedeefink** [comment]
Thanks, I'll give it a go during the week

**Comment by TechPerplexed** [comment]
Absolutely marvellous job, @deedeefink - I'm highly impressed. In fact I learned a few things I didn't know yet 😸 I can't thank you enough for putting that together, can't wait to see more of your articles appear. 

Cheers, Sophia

**Comment by deedeefink** [comment]
You're most welcome and thank you for the kind words. 
I'll add more information as I go through the different applications that I'm using.

**Comment by TechPerplexed** [comment]
I have added an article to the Wiki - see if you approve (since it's basically your baby, haha)

**Comment by deedeefink** [comment]
Very well done. I like it and I will definitely give it a go as I learned something with this advanced tutorial.  Thank you

**Comment by deedeefink** [comment]
> Nice additions to the Wiki, thank you!

Thanks
