### ISSUE TITLE
Unable to install Deluge Docker container

### ISSUE THREAD

**Issue by meharrington90** [TechPerplexed/Gooby#212]
Hey there!

For some reason I am unable to install the Deluge Docker container within my instance. I have tried a full reinstall, a restore, and even deleting the container/Deluge files in `/varl/local/Gooby/Deluge` completely , as well as removing `/var/local/Gooby/Docker/components/41-Deluge.yaml` and attempting to pull the container again from scratch. It still does not seem to load, and I am getting the following error:

`Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/bin/netstat" to rootfs at "/bin/netstat": mount /bin/netstat:/bin/netstat (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

This happened before I did the reinstall (I assume watchtower added an updated container) which caused it to break since the container never fully starts up no matter what. Every other container is running fine.

Thanks for any input!

**Comment by mr-handerson** [comment]
Assuming it is the same issue that arose with Radarr

Comment out line 16 in the volumes section of the yaml

      - /bin/netstat:/bin/netstat:ro

That should work, but leave this open so @TechPerplexed can update the repo version before closing

**Comment by TechPerplexed** [comment]
Whoops, sorry, somehow this post completely slipped by my "Radarr"! File has been updated, thanks @mr-handerson :)
