### ISSUE TITLE
Ombi, Sonarr, Jackett constantly restarting

### ISSUE THREAD

**Issue by meharrington90** [TechPerplexed/Gooby#213]
Hey there!

I noticed the Ombi, Sonarr, and Jackett containers are constantly restarting, while the others remain active. I have done multiple reinstalls on multiple distros, and it still happens regardless. Not sure why, and the docker logs seem to be very unhelpful.

In addition, I noticed this was happening with Deluge initially, which is why I did a reinstall in the first place. Additionally, I have noticed NZBGet randomly crashes when downloading content.

Any help would be great. Thank you!

**Comment by TechPerplexed** [comment]
Oh I'm not sure what that could be, What distro are you using?

**Comment by meharrington90** [comment]
I tried Debian 10, Debian 11 (which seems to have issues with Gooby in general, I need to do more testing), Ubuntu 20.04 and 18.04. Currently on 18.04 now and it seems to still be happening.

I made sure to comment out healthchecks in all the yaml files, as well as adding `- /usr/bin/killall:/usr/bin/killall:ro` to the affected containers with no success. The **rutorrent** container is affected as well. After a while of continuously rebooting, the containers just stop attempting to start entirely when I check `docker ps`.

I'm not sure if it is related, but I believe it is also causing the VM to crash entirely after some time. Contabo is my provider.

**Comment by TechPerplexed** [comment]
I see... well I would need to set up a test server to try and replicate it. I'll try to get around that soon :)

Alternatively, if you have some testing to spare, you can try our brand new project (in working order, but still a wip): https://github.com/kelinger/OmniStream

**Comment by meharrington90** [comment]
No worries! The issue still seems to be occurring with the following containers after a clean install: `netdata, jackett, rutorrent, ombi, sonarr`

I am very excited to test out this new software. I will set it up now and update this ticket with any related info.

**Comment by meharrington90** [comment]
Hey I was wondering if there was any progress on this issue?

**Comment by TechPerplexed** [comment]
Unfortunately I'm no able to reproduce your issues :( Have you tried Omni yet? I suggest a test server just in case, but it should be pretty straight forward if you follow the instructions :)

**Comment by meharrington90** [comment]
Yep! I am using it now. Much more polished and user friendly. I like it a lot. One recommendation, allow the Basic Auth to be optional. I manually turned it off for my containers in the yaml files.

You can close this ticket!

**Comment by TechPerplexed** [comment]
Great, thanks for the feedback :)
