### ISSUE TITLE
[Question] Connecting apps behind http auth

### ISSUE THREAD

**Issue by deedeefink** [TechPerplexed/Gooby#23]
How would you connect Sonarr/Radarr to Jacket when Jackett is behind http auth?

I tired connecting Sonarr/Radarr to Jacket _when_ Jacket is behind a http auth.  Both Sonarr and Radarr requires a unique URL per indexer from Jackett/Torznab. I.e. `https://jackett.domain.com/api/v2.0/indexers/[NAME OF INDEXER]/results/torznab/` Therefore I would not be able to use the docker container name.

I used the command `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' jackett` to get the local IP of Jackett. It returned 172.18.0.4.

I then changed the indexer URL to `https://172.18.0.4:9117/api/v2.0/indexers/[NAME OF INDEXER]/results/torznab/` in anticipation that it would work (I used http, not https). Before copying the URL to Radarr, I checked if I could curl it and got this response: 

```
<?xml version="1.0" encoding="UTF-8"?>
<error code="100" description="Invalid API Key"
```
This would indicate that it works (Given that Radarr would use the right API key :-)) as I allowed through the http auth. 

But, it did not :-(
`Unable to connect to indexer: Error getting response stream (ReadDoneAsync2): ReceiveFailure: Error getting response stream (ReadDoneAsync2): ReceiveFailure` This might be a problem os Radarr, but we should in any case be able to use an IP instead of a domain. 

This also impacts OMBI as it no longer accepts the docker container name "plex" as we discussed here: [https://github.com/TechPerplexed/Gooby/issues/19](https://github.com/TechPerplexed/Gooby/issues/19 )

All in all I'm stuck as I thought using the container local IP would just work. Did you manage to connect Jackett vi IP? Also behind http auth?

EDIT:
I see that the IPs are changing  each time the container is spun up - So this is an issue :-)

**Comment by TechPerplexed** [comment]
Ok, I did notice one error in the yaml script... (port check was wrong both with Jackett and Omni). Would you please uninstall and reinstall both, then check if that solved it? If not, I'll go back to the drawing board... thanks for your patience!

**Comment by deedeefink** [comment]
Yes you're right, it works with Radarr/Sonarr and Jackett. Thank you.

OMBI is not playing nice to this tune though. 
Where I used to have [problems with Sonarr/Radarr](https://github.com/TechPerplexed/Gooby/issues/19), I now have problems with Plex  after one of the updates.

I'm entering:
- Hostname or IP: plex
- Port: 32400

I tried to enter a various combination of IPs and Host names with and without SSL, but no luck. I searched OMBI for resolution and it might relate to docker and permissions depending on what image you are using: https://github.com/tidusjar/Ombi/issues/1538

But that's only one thing :-)
When enabling http auth on Ombi it constantly ask for auth with our working (I tripple checked that I'm using the right credentials). It's like OMBI is only serving some of the traffic through the http auth. Did you succeed?

**Comment by deedeefink** [comment]
I got half-way and successfully connected OMBI to Plex. I had to update the Plex Auth Token by grabbing the token from the web interface and copying it into OMBI instead of the one I got when signing in. So far soo good and I'll add this to the wiki - Just incase others have same problem.

But, 
When I activate the http auth on OMBI, I still have problems loading the site as described above

**Comment by TechPerplexed** [comment]
I don't know if this will help, but the outside port that Plex uses is 8443, not 32400. This is so that Plex will work natively with CloudFlare if needed. Have you tried it with that port yet?

**Comment by deedeefink** [comment]
Thank, the issue is no longer Plex. That's all good.

But try and Secure OMBI and access the domain. In my case  it does not work. OMBI does not load and there is an endless loop of http auth windows. 

It seems like the http auth are causing problems

**Comment by deedeefink** [comment]
Just had the same experience with Portainer. behind httpd auth the page only loads partially and then end up in an endless http auth loop.

**Comment by TechPerplexed** [comment]
Thanks for the heads up, let me look into this :)

**Comment by TechPerplexed** [comment]
Hmm... no sorry not able to find any cause. Luckily Ombi and Portainer both have a rather robust native login facility. Is it absolutely vital for you to have this function?

**Comment by deedeefink** [comment]
Not vital, just annoying that it does not work as intended :-)

**Comment by TechPerplexed** [comment]
Will definitely keep an eye open for further developments on this subject :)
