### ISSUE TITLE
Portainer not being installed?

### ISSUE THREAD

**Issue by deedeefink** [TechPerplexed/Gooby#24]
I have an issue with Portainer not being installed despite Gooby "installing" the app. I choose D, D, I and Gooby goes through the installation and comes up with a-okay message.

But the domain is not accessible (portainer.my-domain.com) - Basically the sub-domains is not responding. When I try to remove Portainer, Gooby reports that the app is not installed???

Gooby v2.0.1

**Comment by TechPerplexed** [comment]
Ackpfffffff, that was just sloppy on my side... 

Note to self: when copying code, make sure you actually update the copy. Portainer should work now!

**Comment by deedeefink** [comment]
Works now. Thanks
