### ISSUE TITLE
What's the correct way to install an update?

### ISSUE THREAD

**Issue by deedeefink** [TechPerplexed/Gooby#25]
Netdata can be updated according to this message:
<img width="597" alt="screenshot 2018-10-30 at 19 56 12" src="https://user-images.githubusercontent.com/14345450/47739470-1caeae00-dc7e-11e8-8566-63eedb776413.png">

Since everything is in docker I would assume that the container needs an update first, but how fast does that typically happen? Should I proactively do something or should I just try updating via Gooby until the container is released?

And what about apps (Sonarr/Radarr/Tautulli) that has a built in update-engine, will that work in docker?

**Comment by TechPerplexed** [comment]
When you update an app using the Gooby, all that it does is stop the app, check for a new version, install it if available, then start it again. Did the creators of Netdata make their update available on Docker yet?

**Comment by deedeefink** [comment]
Okay thanks now I understand the mechanics behind it.
Don't know if Netdata people made the update available on Docker. I'll wait.
