### ISSUE TITLE
[REQUEST] Any chance for SABnzbd support?

### ISSUE THREAD

**Issue by pmscloudeu** [TechPerplexed/Gooby#27]
Would you be able to add SABnzbd?

**Comment by deedeefink** [comment]
I see that linuxserver is offering a [docker container](https://hub.docker.com/r/linuxserver/sabnzbd/), so I guess it would be possible to add SABnzbd [following this guide ](https://github.com/TechPerplexed/Gooby/wiki/Custom-Containers). At least until @TechPerplexed add it natively. Or would that guide not help? (haven't tested it myself yet)

**Comment by pmscloudeu** [comment]
Will test and feedback. Much appreciated.

I am also struggling to get nextcloud + mariadb working in Docker, but I missed the custom containers page so will give that a try.

**Comment by TechPerplexed** [comment]
Yeah no plans to add either of them (yet)... But if you succeed to make them work, I'd love for you to post the working container here. Then I'll add it to the components repository for others who may have the same question :)

**Comment by TechPerplexed** [comment]
Ok, I'm going to close this thread now... SABnzbd has been added through self installation - just copy it to your components folder:

`rsync -a /opt/Gooby/scripts/components/33-sabnzbd.yaml /var/local/Gooby/Docker/components/`

Then start Gooby and run a System Clean from the menu (option E - choice C). 

SABnzbd should now be installed - make sure you create an A record with your domain registrar and point sabnzbd to the IP address of your VPS.
