### ISSUE TITLE
Slow Speeds within Container?

### ISSUE THREAD

**Issue by bdschuster** [TechPerplexed/Gooby#30]
Hi Again!
Is there anything that would be throttling the speeds of the nzbget container? I have a 1GB up/down, and usually download arounf 800mb/s, i seem to be getting throttled around 100mb/s download.

Thanks in advance,
-Brian

**Comment by TechPerplexed** [comment]
No, there is definitely nothing in place to throttle any of the speeds... In fact everything should be set up for maximum performance :)

**Comment by bdschuster** [comment]
Lies! Lol...it's really strange...wondering why I'm throttling...I thought I saw something in the container configs that has a write/read speed. Anyways, I'll see what I can figure out...oh, also found something else, your variables...you have DOWNLOADS mounting to /home/user/Downloads on containers, it doesn't like it because of it being a link to /mnt/google/uploads/downloads...I changed it to that and no issues.

**Comment by TechPerplexed** [comment]
Lol! So it's sorted for you?

**Comment by bdschuster** [comment]
I had to change the variable for DOWNLOADS from /home/me/Downloads to /mnt/google/uploads/Downloads but yeah 😊 thanks for your help. I wouldnt mind helping when I can...I believe my email is on my profile, if not, I would like to help outside of here, so please get in touch.

**Comment by TechPerplexed** [comment]
You're awesome, thanks so much! I can use all the help I can get (hubby says I'm beyond help, lol!)

**Comment by TechPerplexed** [comment]
Could you share your exact settings  of your variables please that fixed your slow downloads/processing?

**Comment by bdschuster** [comment]
I haven't quite been able to narrow it down yet ...it may be my VSP..even outside the container I'm havingsllower than normal speeds.
