### ISSUE TITLE
Organizr not installing

### ISSUE THREAD

**Issue by bdschuster** [TechPerplexed/Gooby#31]
Hello again :-)

Orginizr dosn't appear to be installing, stable or beta. It says install complete, but doesn't create the container.

Thanks in advance!

**Comment by TechPerplexed** [comment]
Oops... I believe it's sorted. Can you update Gooby please and try again?

**Comment by bdschuster** [comment]
Looks like it working now! :-) There is one thing I can't figure out, how can I add another subdomain a container? Like i would like to add requests.mydomain.com to ombi.

Thanks :-)

**Comment by TechPerplexed** [comment]
You will need to edit the component, then rebuild Gooby (heads up: this will break Deluge... see https://forum.openmediavault.org/index.php/Thread/24796-Deluge-Plugin-Failing-to-install/ - yes, I found that out the hard way)

I'm not sure how to add ANOTHER domain to, but you can sure change the location of the current domain.

Open `nano /var/local/Gooby/Docker/components/60-ombi.yaml`
Change line 19 from `      - VIRTUAL_HOST=ombi.${MYDOMAIN}` to `      - VIRTUAL_HOST=requests.${MYDOMAIN}`

Done...

**Comment by bdschuster** [comment]
rebuild Gooby or just rebuild the container? And as far as Deluge, do you mean if I change the subdomain for it only? or any?

**Comment by TechPerplexed** [comment]
Oops I meant system cleanup from the menu (option E-C). Sorry :)

**Comment by TechPerplexed** [comment]
Awesome, good to know!
