### ISSUE TITLE
[Request] Lidarr

### ISSUE THREAD

**Issue by bdschuster** [TechPerplexed/Gooby#32]
Any chance of getting Lidarr since ombi supports it now?

Thanks ;-)

**Comment by TechPerplexed** [comment]
I'll see what I can do :)

**Comment by bdschuster** [comment]
If i haven't told you already, you're the best 😄

**Comment by bdschuster** [comment]
Sent you a pull request for this. It seems you accidently copied in the same docker file for Sonarr. it overwrote my Sonarr with the stable Sonarr...lol...no worries. Fixed and tested.

**Comment by TechPerplexed** [comment]
Omg... What a nut lol. I tested it too then forgot to actually copy in the changes. Thanks!

**Comment by TechPerplexed** [comment]
Ok closing this request for now... but I will monitor the amount of people who would use Lidarr - with enough interest, I'll add it to the menu 😄
