### ISSUE TITLE
[security suggestion] Limit container access to Google drive specific folders 

### ISSUE THREAD

**Issue by nesbcn** [TechPerplexed/Gooby#38]
Hello,

This is more of a security issue, not a current error. The thing is, with the configuration as set by Gooby, **all containers have full access to the whole Google Drive**, because they're mounted with direct access to the root of the user's Drive. This is an important security problem, if a container app gets hacked (and this could conceivably happen, since they're exposed to the internet) then **the attacker would gain access to the whole drive** instead of a subset of folders. This is something that makes me uncomfortable...

I.e. containers such as Plex, Deluge, Sonarr, Radarr, etc. are **inherently exposed to the world and therefore hackable**. These **containers  should only have access to media related folders** that contain movies, tv shows, and so on, but **not access to other unrelated folders which may contain sensitive personal information**, if the user has stored it in his/her drive, which I guess is a usual occurrence. 

I know I can change this by manually editing the Docker Composer yaml scripts in _/opt/Gooby/scripts/components_  and changing the following line in section _volumes:_

For instance, `- ${GOOGLE}:/Media` -> `- ${GOOGLE}/Media:/Media`

My guess is that this change would not survive an update and much less a reinstall. 

I strongly recommend to make this the default mounting option, to limit any potential breach and to increase the user's personal files safety. It also means that **current users would have to make a one-time folder change** **in order to adapt to the new structure**, i.e. create a folder named 'Media' at the root of their Drive, and subsequently moving all movie, tv shows, etc. folders into this new folder, then restarting the containers so that they point to the right folder.

Any thoughts?

**Comment by deedeefink** [comment]
I'm no expert, but when setting up Rclone I specify a root folder. This folder equals my media folder in my Google Drive. Would that not be enough if each user did this? Or would it not matter since Rclone already have a Google Drive authentication token?

**Comment by nesbcn** [comment]
Yes you are right, I hadn't thought of this one. Will the rclone config survive an update?

I still would suggest to inform the user of this possibility, so that the default option doesn't leave his/her drive all exposed.

**Comment by nesbcn** [comment]
I can't seem to make it work, I mean I'm editing the remote in `rclone config` to enter the root folder ID following the instructions in [https://rclone.org/drive/#root-folder-id](url) but then the mount still shows all folders from the root of the google drive. Can you share how you did it?

**Comment by nesbcn** [comment]
It seems to only work when creating a new remote, not editing it....

**Comment by nesbcn** [comment]
I can't seem to make it work. I edited the remote with` rclone config` according to instructions in [https://rclone.org/drive/#root-folder-id](https://rclone.org/drive/#root-folder-id) but when I check the contents of `/mnt/google`, it still shows the full structure from the root of the drive. I tried rebooting and flushing the cache using ` rclone rc vfs/forget`, same result...

**Comment by deedeefink** [comment]
I also had problems updating my Rclone mount previously and I ended up making a fresh install. However, you could try to:

1. Run a system clean - E, C
2. Remove Rclone - B, A, R
3. Install Rclone again and add new remote - B, A, I

Also, @TechPerplexed will wake up in a few hours to hopefully chip in.

**Comment by nesbcn** [comment]
I've removed rclone and reinstall it again. I should note that the configuration survived so the remote was still there, so I deleted and created it again, this time with the proper info. 

What is really interesting is that after I quit the configuration, I was asked for the name of the mount and the media folder:
```
Confirm that this is what you named your mount: Gdrive

What is your media folder in Gdrive? (leave empty for root): Video

```
So it seems that this was already foreseen, although I don't really remember if I saw it the first time. 

Nevertheless, I would recommend to highlight this choice and explain the implications of leaving open the root of the drive.

Thanks for your support!

**Comment by deedeefink** [comment]
Happy that it worked out :-)

**Comment by TechPerplexed** [comment]
Yes, this feature was introduced with version 2.1. I'll add a message that using root is not recommended. Thanks for the suggestion!

**Comment by TechPerplexed** [comment]
Implemented - and thanks again :)
