### ISSUE TITLE
"Spring clean" might break write access of other containers to their volume paths

### ISSUE THREAD

**Issue by Coxeroni** [TechPerplexed/Gooby#39]
The spring clean from inside Gooby resets permissions on the /var/Gooby/Docker folder to be owned by the Gooby user after doing it's "cleaning".

This works for all dockers, which are composed with UID and GID of the Gooby user, like it works for Plex, Emby and the like which come with Gooby.

There are containers, which I manually added, like [nextcloud](https://hub.docker.com/r/linuxserver/nextcloud/) and [mariadb](https://hub.docker.com/_/mariadb/), which don't use the UID and GID option and therefore run with different users. nextcloud uses www-data user, while mariadb seems to run as root. 

When chowning the Docker-Folder this breaks write permissions of these specific containers, which has to be reverted manually or prevented for the future. Since I am not a docker master, the problem could also lie in my compose file for the respective containers, but frankly I was not able to get both containers up and running with the UID & GID options.

Possible solutions might involve:

- adapting the spring clean script to not chown the whole folder
- put the volumes of the respective containers to another folder where permissions stay as they are
- write another script which runs after yours and chowns the respective folders with the correct user

Interested in seeing your viewpoint, since again I am no docker master ;)

Edit: I just realised nextcloud might work with UID and GID of the Gooby user, but haven't tested it.

**Comment by TechPerplexed** [comment]
Thanks Coxeroni! Well obviously adding the spring clean script not to chown everything would be the easiest to implement...

Or I could also just chown the containers that need it. Which would be opposite of excepting the ones that don't (^_^)

So that would be your first suggestion (adapt the script not to chown down the whole folder).

Let me mull this over :)

**Comment by TechPerplexed** [comment]
@Coxeroni, I believe that you are quite right and that the rigorous forcing of permissions is, in fact, not needed. I am going to remove this altogether in an upcoming version of the "system clean" command - I believe that is actually the best solution :) Unless you have a different/better idea... What do you think?

**Comment by Coxeroni** [comment]
I mean it serves a purpose, if a user messed up the permissions, which you know is a common problem with PMS on Linux, this helps. Same with the whole docker-compose rebuild that the script does. 
The longer I think about it, the better I find to simply store the affected volumes in another folder, it also seems as the majority of containers can bei run as a specific UID. But that can be probably better answers by someone with more docker experience.

**Comment by TechPerplexed** [comment]
If it only happens to containers you add manually (and only a few at that), then yes it would make sense to adapt them to use another folder.

Interestingly our initial script didn't set permissions at all - which would work in most normal circumstances.

The alternative might be a separate script/menu option just to set permissions... though I'd prefer the Gooby menu to be as simple as possible for regular use and leave all the exceptions/extras for personal tinkering haha.

As I said in the forum, interesting question and discussion!

**Comment by TechPerplexed** [comment]
For the last little while I have been testing a simplified permission "fixer" for just the "native" Docker folders and it seems to be behaving fine. It will be pushed to the main repository within the next few days.

So for now I'll close this topic (not lock it, feel free to add more information!) and I promise to revisit if any troubles arise out of this and we'll need to reconsider :) Thanks again for the heads up!
