### ISSUE TITLE
Deluge 2.0 beta

### ISSUE THREAD

**Issue by deedeefink** [TechPerplexed/Gooby#44]
Saw here that Deluge has a beta available. 
https://hub.docker.com/r/sinaptika/deluge/
Would be great to get that added :-)

**Comment by deedeefink** [comment]
Thanks but I think you're using the "latest" Docker tag to install the image. This will only give us the current version. You should be using "dev" to get the beta version:

`Docker tags: latest(0.7, 1.3.15), dev (2.0b1)`

**Comment by deedeefink** [comment]
So I updated my local yaml file and installed the beta version. I would  suggest to remove it again as it has some issues connection to Sonarr and Radarr. So it seems to be a bit premature

**Comment by TechPerplexed** [comment]
Awwwwww ok, thanks for testing this! I was confused exactly what image to use. I'll remove the beta version altogether.

Question: do you guys still experience problems with the regular version? I'm still using 145 because it seems like Deluge:latest is just not stable yet - at least not when they first updated it. Are you using latest?

**Comment by deedeefink** [comment]
> Question: do you guys still experience problems with the regular version? I'm still using 145 because it seems like Deluge:latest is just not stable yet - at least not when they first updated it. Are you using latest?

Yes, but too early to say.  Deluge Latest acting up was one of the reasons why I wanted to test the beta. I'm now doing a clean install of ubuntu and I'll let you know if I run into issues with Latest again.

**Comment by deedeefink** [comment]
Btw, how would I downgrade Deluge to an earlier version? I.E. 145 as you mention

**Comment by TechPerplexed** [comment]
The way Gooby works is that each time you perform a system clean or reboot, the file `docker-compose.yaml` is rebuilt from the individual components.

So this means that if you just want to temporarily change one container, you can edit the file `/var/local/Gooby/Docker/docker-compose.yaml` - but that one will be overwritten with each reboot/system clean.

For a more permanent change, you will need to edit the Deluge file in the components folder itself: `/var/local/Gooby/Docker/components/40-deluge.yaml' - that one will be used to rebuild the compose file and will "stick around" until you manually change it again.

If you uninstall Deluge altogether and then reinstall it from the menu, it will replace the components file with the "Gooby" version.

Hope that clears up the confusion 😄
