### ISSUE TITLE
Securing a server does not work on a fresh install

### ISSUE THREAD

**Issue by deedeefink** [TechPerplexed/Gooby#45]
This is not a huge problem, more of a inconvenience, but in any case the function is not working as intended.

Securing a server after a fresh Linux and Gooby install does not work unless you have completed a System Cleanup first. 

Reproduce:
1. Install Linux
2. Install Gooby
3. Install any app, ie. Jackett
4. Secure Jackett
= This fails with message like (Forgot to save the exact message): "Could not create plexuser"

- Reboot does not help
- System Cleanup fixes the problem and you can secure a server.

I've experienced this a after each fresh install whilst testing of our [favourite bug](https://github.com/TechPerplexed/Gooby/issues/36)

**Comment by TechPerplexed** [comment]
Thanks, good catch 👍  Let me look into this 😄

**Comment by TechPerplexed** [comment]
And.... sorted... at last I'm pretty sure it's sorted. Thanks for the bug report! 🥇

**Comment by deedeefink** [comment]
Thanks, I'll trust you on this one. I've done plenty of fresh installs lately :-) 
I'll check next time.
