### ISSUE TITLE
Docker not installing

### ISSUE THREAD

**Issue by pcs333** [TechPerplexed/Gooby#46]
Hi
I'm trying a new setup and after running setup and installing sonarr etc I realised docker was not installed.
Getting the error below

Ign:5 https://download.docker.com/linux/ubuntu cosmic InReleaseErr:6 

https://download.docker.com/linux/ubuntu cosmic Release
  
404  Not Found [IP: 2600:9000:2006:3200:3:db06:4200:93a1 443]Reading package lists... Done
E: The repository 'https://download.docker.com/linux/ubuntu cosmic Release' does not have a Release file.

**Comment by pcs333** [comment]
I have ubuntu 18.10 installed.
So now i am re-installing with 18.04 to see what happens ;-)

**Comment by TechPerplexed** [comment]
Ugh, don't tell me they will be changing things once AGAIN for 18.10 😝 
Ah well we'll cross that bridge when we need to 😆
