### ISSUE TITLE
How does the backup function?

### ISSUE THREAD

**Issue by nesbcn** [TechPerplexed/Gooby#47]
Hi,

There is an option in the menu to perform a backup, I tried it yesterday because I'm interested in migrating the system to another server. Is there a tar file somewhere that I can take and restore the backup on another system? There was no indication on what the backup performed, other than it could take a long time. The function is also not documented...

Thanks!

**Comment by nesbcn** [comment]
Ok now I discovered that there is a backup folder sitting in the /Backup of the remote mounted drive... Would the restore Backup function take the content and restore everything? Containers, configs, libraries and all?

**Comment by TechPerplexed** [comment]
Did you manage to backup and restore? :) I'll close this thread for now... but you can still add to it!

**Comment by bdschuster** [comment]
Wait, it creats a cron job after you run it the first time? Hi BTW! Missed ya'll.

**Comment by TechPerplexed** [comment]
Welcome back @bdschuster hope your health is back to what it should be :) And yes, it creates a cron job the first time you run a backup... remember to create one manual backup after you restore the server to a new one!

**Comment by TechPerplexed** [comment]
Thanks for letting me know.... what do you mean by future files? If your fix works it might be a good idea to make that a Gooby fix 😆

**Comment by bdschuster** [comment]
Remember me telling you when files download with future times/dates, they wouldn't upload till after whatever time that is? Especially when using "change date/time to air date" in Sonarr/Radarr/

**Comment by TechPerplexed** [comment]
OH DUH, sorry memory is a sieve sometimes.... yep, of course I remember now. One random thought just popping up, might it be that your server is another timezone as yourself? 
Mind you, mine is in Europe and I haven't noticed anything odd myself!

**Comment by bdschuster** [comment]
Usually happens on Wed Shows, like Chicago PD, Fire, Med.  Also Monday shows like The Resident, and The Good Doctor. Seems to be NBC shows that upload faster cause the appear on CTV (Canada) before the US.

**Comment by TechPerplexed** [comment]
Hmmm.... not downloading any of those myself. So far you are the only one that noticed/mentioned it... but if it happens to others, I may pick your brain (again) on setting it straight :)
