### ISSUE TITLE
Non-Standard components?

### ISSUE THREAD

**Issue by claym** [TechPerplexed/Gooby#49]
I noticed this project does not have a few useful tools like nzbhydra and mylar. How feasible is it for me to add them on my own without blowing everything up?

**Comment by TechPerplexed** [comment]
"Theoretically" you can't blow up anything by just adding a new container... at least not for good (the worst that could happen is that you'd need to remove it again).

Check the Wiki on how to install containers: https://github.com/TechPerplexed/Gooby/wiki/Custom-Containers

That said, naturally the risk is all yours, anything I said above cannot be held against me, ever 😆
