### ISSUE TITLE
Deluge download folder

### ISSUE THREAD

**Issue by deedeefink** [TechPerplexed/Gooby#50]
For the past two weeks I've not been able to download with Deluge. The torrent is added from ie. Radarr but the metadata is not downloaded and the torrent never starts. File size remains at 0.0 KiB and I never get any Seeders/Peers.

I tired to change the DL folder to the below, but no luck. 
- /Downloads/
- /Downloads
- ~/Downloads 
- /home/plexuser/Downloads

I suspected this might be a permissions problem and when I use Midnight Commander i can see that the ~/Downloads folder is a symlink to /mnt/google/Downloads and not a folder locally on my system. 

I tried to rename ~/Downloads and create a new "on-system" folder but still no luck downloading. I also installed qBittorrent(nox) with same results = No download

Help is appreciated. Thanks

I'm on Ubuntu 18.04.1 and Gooby 2.1.1

**Comment by TechPerplexed** [comment]
Hmmm, weird, yes /Downloads is the correct place from within Deluge.

That said, changing the folder names and/or locations would definitely break the system ;) The symlink and actual folder name/location both have to be in place... (symlink is it prevent problems and also make it easier to locate download files).

To restore it to default, Make sure that you have a folder /mnt/uploads/Downloads (this is the actual location). 
Let's make sure permissions are ok: `sudo chown -R $USER:$USER $HOME /mnt/uploads`

Then get the symlink back in place: `sudo ln -s /mnt/uploads/Downloads $HOME/Downloads'

See if you can write to $HOME/Downloads (just try `touch helloworld` from within the symlink directory and see if it writes the file to /mnt/uploads/Downloads).

If all that works properly, Deluge should definitely work!

**Comment by deedeefink** [comment]
Thanks,
I set the permissions and recreated the symlink. This worked like charm but Dluge is still not downloading. I see no errors what so ever, but dl never starts. Hmm Not even Torguard Check my IP works.

Is there a way to access Deluge logs?

**Comment by deedeefink** [comment]
Hang on for a min.
It seem's that this might have been my own fault (Gosh, i battled with this fro two weeks) as i did not configure my proxy and therefore might have been blocked by the hosting/isp provider.

Doh!
