### ISSUE TITLE
Possible Docker Add - Monitorr

### ISSUE THREAD

**Issue by bdschuster** [TechPerplexed/Gooby#58]
This this may be cool to add. I think im going to add it to mine and check it out.
https://hub.docker.com/r/monitorr/monitorr/

Check it out and let me know.

**Comment by bdschuster** [comment]
Got it working! Adding the file now.

**Comment by TechPerplexed** [comment]
Wow, looks nice!! Let me install it too using your file - and as always: thanks ❤️

**Comment by TechPerplexed** [comment]
It's installed! Can you give a nudge how you set up the services please?

**Comment by bdschuster** [comment]
Did you tell it to create the app directory (which you should have just left it default), and create a username/password?

**Comment by TechPerplexed** [comment]
Yes, I did - the app directory was rather odd, something like ./././././something but I couldn't change it. I did create a username and password, and it's showing me Google and Monitorr as online - but Plex/Emby (that I tried to add manually) as offline. Something isn't quite right I guess ^_^

**Comment by bdschuster** [comment]
is plex on the same machine using Gooby?

**Comment by TechPerplexed** [comment]
Yes, it sure it! (and it's fun that you are troubleshooting me for a change) 🤣

**Comment by bdschuster** [comment]
Check URL should be: http://plex:32400
Service URL is what it is to access it from the outside, so i'm assuming https://plex.whatever.com

All the other boxes should be default except whatever you want to call it and the image you want to use.

**Comment by TechPerplexed** [comment]
Gah, I had those two reversed! Thanks!

**Comment by TechPerplexed** [comment]
Working like a charm... I'll archive this thread now and everyone can use the Wiki plus this thread to self install the app :)

![screenshot 2019-02-02 12 10 52](https://user-images.githubusercontent.com/15312691/52168162-e13fd780-26e3-11e9-9b79-ccb2bc6e8308.png)
