### ISSUE TITLE
Docker containers fail to start after server reboot

### ISSUE THREAD

**Issue by theboywonder** [TechPerplexed/Gooby#60]
Hi,

I have a few issues on a new install but I'll split them out into separate posts.

I've installed Gooby on Ubuntu Server (18.04) and I'm finding that after rebooting the server, Plex fails to start. `docker container ls` and `docker ps` both fail to show any results.

If I enter the Gooby menu, and try to update Plex, it tells me that it's not installed. If I run the install again, it starts up Plex (and the other 2 containers) and it's accessible with all my previous configuration.

How can I solve this?

Thanks.

**Comment by TechPerplexed** [comment]
Hi and welcome :) I'm wondering if your issue has to do with sudo privileges - funny enough this question has popped up a few times lately. Could you check please if `sudo visudo` contains the line

`yourusername ALL=NOPASSWD: ALL`

(should be at the bottom). If it's there, we'll need to check further :)

Also, question for you: Did you create your user through Gooby or manually?

**Comment by theboywonder** [comment]
Hi, thanks for the reply (and thanks for your hard work on Gooby!). It appears to be missing. 

```

# User privilege specification
root    ALL=(ALL:ALL) ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL
```

When I installed Ubuntu it asked me for a username which I provided, and since then I've just used that account. I recall the installation initially throwing up a message about it being better run as root (I think), but I don't remember it prompting me to create a user account. I will clone the VM and revert to a snapshot prior to installation to check that.

If I add `myusername ALL=NOPASSWD: ALL` to the file and give the server a reboot, do you think this would fix things?

**Comment by TechPerplexed** [comment]
Did you add the line as sudo user? You will need to sudo to root first: `sudo -s` and then add the line.

You can also try the following method:

```
sudo -s
PU=yourusername
sudo -s usermod -a -G sudo $PU
sudo -s echo -e "$PU\tALL=(ALL)\tNOPASSWD:ALL" > /etc/sudoers.d/$PU
sudo -s chmod 0440 /etc/sudoers.d/$PU
exit
```

Make sure that PU=_yourownusername_ - don't just copy and paste the entire code ;)

**Comment by theboywonder** [comment]
> Did you add the line as root? You will need to sudo to root first: `sudo -s` and then add the line.

I didn't! So, running `sudo -s` changed my command prompt from $ to # as you'd expect. I ran `sudo visudo` again, and added `myusername ALL=NOPASSWD: ALL` (yes, my actual username lol) to the bottom of the file, saved it (it prompts to save to `/etc/sudoers.tmp`) and rebooted. Still no automatic start of containers.

**Comment by TechPerplexed** [comment]
No, you won't have to start from scratch - at least not yet, let's keep that for a last resort :) And if you do, restoring the backup would be infinitely quicker than restarting all over again!

Let's try to troubleshoot this:
1) when you run a manual system cleanup from the menu, do all the containers come back then? 
2) Do you get any errors or prompts for passwords in the process?
3) When you perform a sudo command as your user, do you still get prompted for a password the first time you run the command?

Thanks for your patience and willing to work with me - learn something new every time 😆

**Comment by theboywonder** [comment]
No problem - it's forcing me to learn some Linux stuff lol (I hate it, but I'm a long time Windows admin). Thanks for your patience also :) To answer your questions:

1 and 2. System cleanup runs fine, without any errors or prompts (earlier it didn't - I've had issues with the Google Mount also and was trying some steps from a closed issue which fixed it).

3. I do not get prompted for a password now, which suggests that the edit made earlier is working?

**Comment by theboywonder** [comment]
I just rebooted and the containers are started! Not sure what happened but it seems to be good :D

Now, is there a way that I can fix the exposed port 8443 to 32400 permanently? I managed to do this by stopping docker and editing two .json files in the plex container directory, but I feel like when I go to reinstall/upgrade it might overwrite this.

**Comment by TechPerplexed** [comment]
Yay! Let's hope it stays this way 👍 

As for changing the Plex port - why would you do that? But if you really want to, you can edit everything yourself for sure - best way is change the Plex yaml file in /var/local/Gooby/Docker/components, then run a system cleanup from the Gooby menu to activate the changes.

Meanwhile, I'll close this issue (since it's no longer an issue - hopefully) but it'll be open for further comments so we can continue this discussion 🙂

**Comment by theboywonder** [comment]
@TechPerplexed The reason for wanting to use port 32400 is because, rather than opening a specific port, there's an 'application definition' the firewalls here for Plex and this is what's applied to the IP of my VM. When using 8443 it doesn't work, but with port 32400 it springs to life (at least the web interface does). Thanks for the tip and your help on this - I've already done that so hopefully it sticks when upgrading in the future :)

**Comment by TechPerplexed** [comment]
Haha thanks for the explanation, there you go... everyone has their own unique use cases!

As for whether the changes will stick: yes, edits to the files in the components folder won't be overwritten with updates/upgrades - with the exception of uninstalling the app itself and then reinstalling it. In that case, the yaml file in components will be deleted and then pulled from the repository afresh when you reinstall.

It's a very flexible system and basically any element you can think of can be changed to your liking :)
