### ISSUE TITLE
Issue with rclone 

### ISSUE THREAD

**Issue by RykerCohen** [TechPerplexed/Gooby#62]
Hi. I was following your guide to install rclone, and i get this error.

`cat:
 /var/local/.Gooby/plexclaim: No such file or directory
done
Failed to enable unit: File rclonefs.service: Invalid argument
Failed to start rclonefs.service: Unit rclonefs.service is not loaded properly: Invalid argument.
See system logs and 'systemctl status rclonefs.service' for`

**Comment by TechPerplexed** [comment]
My apologies! I had added one line the other day and forgot to close it with a \ at the end. Please uninstall Rclone (no need to remove your credentials), update Gooby (option E - A in the menu) and try again.

Also I suggest you run a system clean after installing everything (option E - C) :)

**Comment by RykerCohen** [comment]
I appreciate it! love this whole program! thought i was doing something wrong at first lol

**Comment by TechPerplexed** [comment]
No it was definitely me... Thanks for pointing it out :) Glad you enjoy Gooby!
