### ISSUE TITLE
Plex 502 Error

### ISSUE THREAD

**Issue by RykerCohen** [TechPerplexed/Gooby#63]
Hi. I got a new server, started, installed Plex. when I try to access the URL, i get a Plex 502 Error

**Comment by bdschuster** [comment]
@RykerCohen are you using plex.yourdomain.com?

**Comment by RykerCohen** [comment]
yes. other programs are working, just not plex @bdschuster

**Comment by bdschuster** [comment]
Brand new Plex server? You may have to claim it.

**Comment by RykerCohen** [comment]
i did claim it. any way to remove it and try it again?

**Comment by RykerCohen** [comment]
also got that for my jackett install @bdschuster

**Comment by bdschuster** [comment]
You shouldnt have to reclaim it. For the heck of it, do a system cleanup (option E > C) from the Gooby menu and wait about 5mins after it completes then try again. Make sure you are using HTTPS in your url (https://plex.whatever.com) no capitals (sometimes Linux is picky with case) and no port number. If you did any type of port forwarding from your router to be able to access, make sure you are forwarding 8443 not 32400.

**Comment by RykerCohen** [comment]
ok and its actually on a dedicated server i bought. will port fordward on there

**Comment by RykerCohen** [comment]
still getting that 502

**Comment by RykerCohen** [comment]
Having alot of issues on thiss new server. its Ubuntu 18.04. Should i downgrade?

**Comment by bdschuster** [comment]
I have a physical server as well, I will admit, I had issues trying to get everything working in 18.04. I went down to 16.04, and all my issues seemed to go away. I haven't been able to test upgrading again since then. You could try, let me know though, I'm curious.

**Comment by RykerCohen** [comment]
ok ill downgrade now

**Comment by TechPerplexed** [comment]
I switched to Debian a few months ago, never looked back. You could try that if you like, at least you'll have the latest version of a distro that way...

**Comment by RykerCohen** [comment]
Ah i was going off the guide with Ubuntu. anyways it fixed it. just trying to get jacket to work with sonarr. thanbks for your great work on  this!

**Comment by RykerCohen** [comment]
Wierd how everything but the search all for jackett isnt working

**Comment by RykerCohen** [comment]
One more thing before I close this, The jacket indexer is not working in sonarr and radarr

**Comment by RykerCohen** [comment]
if anything =, ill move to Debian if everything is working there lol

**Comment by bdschuster** [comment]
I'm not sure the indexer has anything to do with Gooby.

**Comment by RykerCohen** [comment]
I’m just switching over to Debian. Ubuntu if giving me issues all the time lol

**Comment by RykerCohen** [comment]
@TechPerplexed Is it the same command for Debian?

**Comment by RykerCohen** [comment]
Not sure if its me or jackett not working, but i cant get it indexer to work,

**Comment by deedeefink** [comment]
Did you look at the Wiki no how to connect Jackett to Sonarr and Radarr? Might help
https://github.com/TechPerplexed/Gooby/wiki/Sonarr-and-Radarr

**Comment by RykerCohen** [comment]
Yes i did. Still not able to connect.

**Comment by deedeefink** [comment]
And where is the problem. That you cannot add indexer to Jackett or that you cannot connect the indexer in Sonarr/Radarr? Can you add a bit more detail on what you do and what the result is

**Comment by RykerCohen** [comment]
It cant connect 

![image](https://i.imgur.com/3QtR4T0.jpg)

**Comment by deedeefink** [comment]
Drop the https and use http only. It's internal network so Let's Encrypt does not work

**Comment by RykerCohen** [comment]
Thanks. I appreciate it!

**Comment by deedeefink** [comment]
No worries. I've been there as well :-) I updated the Wiki to reflect this more precisely.

**Comment by RykerCohen** [comment]
Great. Missed the https issue. Thanks again!
