### ISSUE TITLE
Plex update issue

### ISSUE THREAD

**Issue by thunderstorm654** [TechPerplexed/Gooby#64]
Hi,

I tried the Plex update via the Gooby menus. It said something along the lines of access denied, so I tried it again. Now it says it is up to date. Meanwhile the update didn't take effect as Plex still reports the older version. Do you know what went wrong with the permissions doing the update? 

Thanks!

**Comment by TechPerplexed** [comment]
Hi @thunderstorm654 thunderstorm and welcome :)

First, if you encounter any permission issues, try a system clean first (option E - C). That usually solves just about all problems 😄 

As for Plex updates, those are handled by Plex themselves (not by the container). If you get the message that there is an update, that just means they haven't pushed it out to you yet. Your server should be kept pretty much up to date by itself - though sometimes you can trigger it by running the system clean above.

**Comment by thunderstorm654** [comment]
Hi there, thanks for the response. I tried system cleanup which worked fine, Plex still says there's an update with a link to "please install manually". Is that expected?
I wasn't sure about the update Plex option in the menu so thanks for clarifying.

**Comment by TechPerplexed** [comment]
Yes, if you wait a day or so, the Plex team will have caught up on their Docker update and you'll have the latest version without having to do anything. The "please install manually" is a bit misleading, because it's up to them to deliver - but don't worry, they will 😁 

I'll close this issue in the meantime, but if you have any question or additional concerns, feel free to add them to this thread!

**Comment by thunderstorm654** [comment]
Hi there. The update is still showing as available and to install it manually. Do you know how I can do that?
Also, super dumb question but how to I restart Plex without rebooting? I added some new folders to my server to add to libraries and need a restart so Plex can see them. All the usual ways I've done it on other boxes don't work, I also couldn't do it using sudo as I can't see the service so unsure how it's set up :). Thanks!

**Comment by TechPerplexed** [comment]
What update is showing for you @thunderstorm654? Mine is showing Version 1.15.3.876 - up to date.

You can restart Plex (or any service) by typing `docker restart plex` (or `docker stop plex` and `docker start plex`, if you prefer).

As for your last question, can you explain what you mean by new folder with optimized versions? Can you give an example of how you want to use this?

To give you a little background: all your Plex folders reside in /mnt/google. You shouldn't really touch that folder directly, so based on your answer I can recommend you how to set it up the way you want it :)

**Comment by bdschuster** [comment]
@TechPerplexed mine is showing 1.15.4.919, might want to do an update or system cleanup ☺️. Unless you aren't using PlexPass versions.

**Comment by TechPerplexed** [comment]
Hah, right, I'm using stable (since PlexPass is basically "beta", right? 🤣 I guess Plex came out with a NEW version then!

**Comment by bdschuster** [comment]
I wouldn't say "beta", i would say "early release"...lol

**Comment by thunderstorm654** [comment]
Hi @TechPerplexed would you believe it it's now on the same version as you. For the past few weeks it was stuck on 1.14 something, despite doing a few system cleanups. 

Thanks for the info re starting/stopping services. I did some more digging yesterday and figured out how to solve my "optimized versions" query. 

I have a couple of (kids!) Plex users who only access a small part of my content via tablets. Nearly all my content is remux quality. So when new movies come out that they want to watch, I use my server (just using Plex's built in "optimise" feature) to pre convert and create a smaller version (they come out in 720p around 2-3gb) using the optimise for mobile profile. There's other utilities I could use to do the conversions but Plex works well enough for me. I didn't want them tying up the server always transcoding, even though it can cope with one or two. 

Once they're all done I then automate moving them off the server into Google Drive. So I needed to add another folder to Plex that was writable. Just created it under my user account, have it write permissions then added it into the yaml file under volumes and it's working now :-)

Thanks again for your help!

**Comment by TechPerplexed** [comment]
I see, thanks for the explanation :) Glad you find a solution that works for you 👍
