### ISSUE TITLE
Manual Sync Question

### ISSUE THREAD

**Issue by bdschuster** [TechPerplexed/Gooby#65]
When I run a manual Sync (because I'm sometimes inpatient..lol), I noticed it's been sitting for about 10mins before actually uploading.

Starting sync at Mon Apr 15 19:47:44 CDT 2019
Copying files
/TVShows/Bar Rescue/Season 6/Bar Rescue-S06E25.mkv
Files to copy: 1
Bytes to copy: 1562664119
2019/04/15 19:47:44 INFO  : Starting HTTP transaction limiter: max 5 transactions/s with burst 1
0 / 0 Bytes, -, 0 Bytes/s, ETA -

This didn't start to upload uploading till 19:58.

Any ideas?

**Comment by TechPerplexed** [comment]
Eh, that is strange... it should upload right after the two minute mark. Does it ALWAYS happen or just this once?

**Comment by bdschuster** [comment]
Usually happens to be honest. At least the times I tried. It was usually just after one (or more), just finished by the cron job, then I will run it again manually because some downloaded while it was running. It isn't always 10mins though I don't think...but it definitely sits at that for a bit before starting.

**Comment by TechPerplexed** [comment]
Strange, I don't upload manually that often (being a more patient type 🤣 jk!) - but I don't think I had to wait longer than 2 minutes ever when I did try. Keep me posted 😄

**Comment by TechPerplexed** [comment]
I'm going to close this issue for now in order to keep the list of open issues manageable - but you know you can always add more information 😄
