### ISSUE TITLE
Issues with docker? Plex and RClone keep unloading.

### ISSUE THREAD

**Issue by spladesrus** [TechPerplexed/Gooby#67]
So first, I apologize. This is my first experience with docker so if my terminology is incorrect please tell me. :) I have installed Gooby, rClone(Google Drive) and Plex. I am having issues with the persistence of the rClone and Plex installations. I am not sure if it is related, but it happens when I add content to my Plex Library. First the rClone installation will fall off. I can select "install" and run through the setup, but it does not actually install. Rebooting as root results in Plex no longer showing up in concurrence with the rClone issue. 

When I run a system cleanup I get this error:
_Failed to start rclonefs.service: Unit rclonefs.service not found.
Failed to start mergerfs.service: Unit mergerfs.service not found._

Followed by this endless loop of errors:
_mountpoint: /mnt/rclone: No such file or directory
mountpoint: /mnt/google: No such file or directory
Waiting on mounts to be created...
mountpoint: /mnt/rclone: No such file or directory
mountpoint: /mnt/google: No such file or directory
Waiting on mounts to be created...
etc etc_

I've reimaged the server in order to get back to a functional Gooby, install rClone and Plex, add my libraries and then about midway through boom. Plex can't find the Media directory because rClone has disappeared. I am back where I am started. This most recent time I did the OS update before installing anything and I have listed that version information below. 

Gooby Information: 
Ubuntu 18.04.2 LTS (Hetzner)
Gooby version: 2.1.4

I am not sure if you have seen this before, but I figured I would bring it to your attention. I am reimaging the server again since I did so much fiddling around. This time I will be installing Ubuntu 18.04.1 LTS and not doing the version upgrade.

**Comment by TechPerplexed** [comment]
Hi and welcome! From the error you're getting it sounds as if Rclone did not install correctly - since you whole system hinges on that, nothing will work after that :)

So trying to understand your issue: you installed Gooby and your mount works at first, right? Do you see your content in /mnt/google (`ls /mnt/google`)?

**Comment by Trentflix** [comment]
Also, avoid my mistake and make sure you run the install script with root instead of just sudo privileges

**Comment by spladesrus** [comment]
> Hi and welcome! From the error you're getting it sounds as if Rclone did not install correctly - since you whole system hinges on that, nothing will work after that :)
> 
> So trying to understand your issue: you installed Gooby and your mount works at first, right? Do you see your content in /mnt/google (`ls /mnt/google`)?

Based on what I can tell, everything is working normally. Even Plex after the initial install. I am not sure how to navigate directories in terminal and see that info(Windows guy here XD). What command would I be using to get there?



> Also, avoid my mistake and make sure you run the install script with root instead of just sudo privileges

Right now, I am signed in as root and using this command:
sudo wget http://bit.ly/GetGooby -O /tmp/install.sh && sudo bash /tmp/install.sh
Should I be doing this differently?

**Comment by TechPerplexed** [comment]
The command I gave you ;) `ls /mnt/google` should give you a list of your content (ls is the equivalent of dir in Windows).

You're saying everything is working normally - at what point does your server behave abnormally?

As for running that command in root, did it ask you to create a user?

**Comment by spladesrus** [comment]
I've reimaged the server and reinstalled Gooby, Rclone, and Plex. So far so good. I used the command you gave me and it listed all of the folders in my Google Drive. 

Based on what I've experienced, it seems as though it all fails when I index my media library in Plex. I'll reboot as root and Rclone and Plex instances just do not come back up.

Going to index my media now to attempt to reproduce the issue.

**Comment by TechPerplexed** [comment]
Good luck, let me know if that worked!

**Comment by spladesrus** [comment]
Ironically, everything seems to be loading up fine. In the event that I need to reboot the server, is there anything I need to do outside of rebooting under root?

**Comment by TechPerplexed** [comment]
After a reboot everything should come back seamlessly, you shouldn't notice a thing :)

I'll close this issue now, but feel free to reopen it or add anything that might come up!

**Comment by spladesrus** [comment]
Well my Plex instance was running extremely poorly so I rebooted my server and ended up back in the same spot I was before. I ran that command you gave me: ls /mnt/google 
and it returned this: ls: cannot access '/mnt/google': No such file or directory
So at this point I don’t think Rclone is starting back up properly after the reboot.
