### ISSUE TITLE
2.1.4: Rclone install and remote name input

### ISSUE THREAD

**Issue by Coxeroni** [TechPerplexed/Gooby#68]
Where does the issue occur:
In rclone setup user is asked, whether the remote name is correct to be used by gooby.

Current behaviour:
My remote name which was typed in is ignored and still the standard/first remote is used.

Expected behaviour:
If I type in another remote name, this should be used.

Background:
I encrypt my Gdrive storage and therefore I am adding two rclone remotes after each other, wherein only the second remote is to be mounted by Gooby.

**Comment by TechPerplexed** [comment]
Thanks @Coxeroni - I'll look into that 😄

**Comment by Coxeroni** [comment]
The bug is more "annoying" than I thought. After rebooting /var/local/Gooby/Docker/.env is populated with the wrong rclone remote and therefore neither the mounts nor the containers come up. Manually editing that .env again and rebooting does not solve the issue, I currently don't know why. With the next reboot, the remote is changed again.

I first have to hunt down, where that rclone remote entry to .env comes from, maybe you can assist? I know you are on holiday, so no hurry ;)

**Comment by TechPerplexed** [comment]
Thanks 😄 Having a good time, so apologies for the late replies for the coming few weeks!

I promise I'll have a good look at the script when I get back... but yes, your first action was to change the $CONFIGS/.config/rcloneservice file as you did. 

Also, you definitely need to give your user permissions not to ask for your password, so I'm pretty sure (but never COMPLETELY sure) that your woes will be over for now :)

**Comment by Coxeroni** [comment]
No apologies needed.

Concerning the sudo password, I seemed to have messed up again myself by creating my own user before running Gooby. Just checked the `user-create.sh` script and spotted line 22-24 with the respective entries into the sudoers file.

So sorry for wasting your time on my own misbehaviour :D 

Enjoy your time with your folks, all is smoothly running again on my end ;)

**Comment by TechPerplexed** [comment]
Andddd.... now that I'm back and (almost) alive again... this issue should solved :) Thanks for the report!
