### ISSUE TITLE
Deluge doesn’t download and Rclone doesn’t upload automatically 

### ISSUE THREAD

**Issue by recse** [TechPerplexed/Gooby#70]
Hi,
First of all, thank you for the good project you made.

I installed your suit and all works fine. I have the server in a VPS running 24/7 (Ubuntu machine) but, I have two problems that i can’t find the solution:

1- Deluge only downloads when I’m on my website (Deluge.mywebsite.com). If the server is running 24/7, why Deluge doesn’t download automatically during all the day?

2- Rclone doesn’t upload automatically the media to my TeamDrive (but it works doing manually). Should I do anything? I checked your script in your Cron folder but i think it should works automatically.

Thanks for your help in advance

**Comment by TechPerplexed** [comment]
Thanks and welcome :)

As for your problems: I have never even heard of Deluge only downloading when you visit the site! Normally it's the other way around ("a watched pot never boils", lol). I would definitely need more information to troubleshoot that one!

You say Rclone doesn't upload automatically to TeamDrive - are you saying it uploads when you run the cron script manually, but it doesn't when called upon in the cron script?

**Comment by recse** [comment]
Hi again,
What kind of information will you need to try to help me with Deluge?. I can say you that the server works correctly (24/7 I mean) so, i dont know why Deluge only works when I’m on the website. I’d like to try other Downloader but, unfortunately, NBZget doesn’t work  (dont know why neither) and RuTorrent doesn’t like me.

About the Rclone problem, yes, i mean that the Rclone only uploads when I use the Sync and Upload command directly. I think, your script is not working directly. It is done to works automatically? Or must I configure it? 

Thanks

**Comment by recse** [comment]
Following my last comment, i meant that your script is not being called. I just achieved upload the media using the Rclone commands, not your script. That is why I asked you if i should configure something in your script, in otder to it be called

**Comment by TechPerplexed** [comment]
What is the manual command that you use that DOES work?

**Comment by recse** [comment]
The sync and upload command by Rclone (which is shown through the -help command)

**Comment by TechPerplexed** [comment]
Thanks but... I'm trying to establish what is different with your command (that works for you) and the Gooby command (which doesn't). So please be more specific what exactly you type ;)

**Comment by recse** [comment]
Hi 
I use:
cd into rclone package directory
    
rclone --transfers=32 --checkers=16 --drive-chunk-size=16384k --drive-upload-cutoff=16384k copy ~/FilePATH/ REMOTENAME(eg:gdrive):DataToBeUploadedPATH

**Comment by bdschuster** [comment]
Can you check your syslog (/var/log/syslog) and see if any errors at the 0,15,30, and :45 of every hour? Also, the cron script will only upload stuff in /mnt/google/Downloads/completed which if Sonarr and Radarr are properly configured, that's where they would move the files (within the container of course).

**Comment by TechPerplexed** [comment]
Did that sort your issue, @recse? If not you can add your questions to this thread, but it's been 5 days since we heard so I'll close the issue in the meantime :)
