### ISSUE TITLE
deluge

### ISSUE THREAD

**Issue by Whitexp** [TechPerplexed/Gooby#72]
hi , after deluge download to /download it will copy to gdrive automatically? 

i need to do something ?

thanks

**Comment by bdschuster** [comment]
Do you have anything organizing your downloads? Sonarr, Radarr?

**Comment by Whitexp** [comment]
no , i just download a film using deluge to /Downloads folder .

**Comment by Whitexp** [comment]
when using deluge i need to point to wich folder ?

thanks

**Comment by bdschuster** [comment]
Oh, well, usually Sonarr or Radarr or alike will take it from /download and move it to /Media, which will then be available in Plex right away while it uploads to Google every 15mins

**Comment by Whitexp** [comment]
so , so with this config 
![image](https://user-images.githubusercontent.com/1900530/56691438-58b74e80-66b6-11e9-881e-cddd52c88e83.png) 

will work well ? 

thanks

**Comment by bdschuster** [comment]
Shouldn't be a problem, but it's not going to be organized in any way. Not sure how the structure of your Google drive is.

**Comment by TechPerplexed** [comment]
Thanks so much for all your help, @bdschuster!

Did that sort your problem, @Whitexp ? If not, you can add to this issue. I will close it now but it'll always remain open for additional comments :)
