### ISSUE TITLE
Issues with Docker not reloading Rclone and Plex after reboot

### ISSUE THREAD

**Issue by spladesrus** [TechPerplexed/Gooby#73]
Reference my previous ticket #67
Well my Plex instance was running extremely poorly so I rebooted my server and ended up back in the same spot I was before. I ran that command you gave me: ls /mnt/google
and it returned this: ls: cannot access '/mnt/google': No such file or directory
So at this point I don’t think Rclone is starting back up properly after the reboot.

**Comment by TechPerplexed** [comment]
What do you see when you run a system clean (option E - C)? Does the mount come back after that?

PS sorry for the late replies, I'm currently traveling and not always able to respond :)

**Comment by spladesrus** [comment]
It’s cool!
I was troubleshooting and got it running for our family’s movie night :) I ended up blowing it out and reinstalling everything and then restoring the backup I made before I did the reboot before. I’ll reboot the server tonight to force the error and let you know what it comes back with after the system clean. I know that when I ran it while troubleshooting it did not resolve the issue.

I’ll reboot it(seems to consistently fail after the reboot) tonight and let you know here what the system clean comes back with.

**Comment by spladesrus** [comment]
See below:

-------------------------------------------------
 This will cleanup system
--------------------------------------------------


--------------------------------------------------
 Are you sure you want to cleanup system (y/N)? 
--------------------------------------------------

 ---> 

Giving your system a nice little spring cleaning...


Updating Gooby

Cloning into '/opt/.Gooby'...
remote: Enumerating objects: 165, done.
remote: Counting objects: 100% (165/165), done.
remote: Compressing objects: 100% (164/164), done.
remote: Total 10226 (delta 78), reused 0 (delta 0), pack-reused 10061
Receiving objects: 100% (10226/10226), 1.79 MiB | 3.74 MiB/s, done.
Resolving deltas: 100% (6933/6933), done.

Shutting everything down

Removing network docker_default
WARNING: Network docker_default not found.

Updating Rclone if possible

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4278  100  4278    0     0  22165      0 --:--:-- --:--:-- --:--:-- 22165
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0     76      0 --:--:-- --:--:-- --:--:--    76

The latest version of rclone rclone v1.47.0 is already installed.


Cleaning mount leftovers

mountpoint: /mnt/rclone: No such file or directory
mountpoint: /mnt/google: No such file or directory

Calling on Upgrade Service

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100    13    0     0     55      0 --:--:-- --:--:-- --:--:--    55
done

Updating and starting containers

Pulling nginx-proxy                       ... done
Pulling letsencrypt-nginx-proxy-companion ... done
Pulling plex                              ... done
Creating network "docker_default" with the default driver
Creating plex        ... done
Creating nginx-proxy ... done
Creating letsencrypt ... done

Cleaning Docker leftovers

Deleted Volumes:
44b3fb9057ebbfba9541b11244155be99e635c135302eaa8a8a923a398f3a848
77b59f1d0ff4c11135e160f1ad739f2444f999915aa650af14e50b76ddef4cc1
a69f399d93d2db5e18507f4ba7ac58dcb26cdc79a7303b6a82c816b7d74975ef
bf39f28a100b8b0c714bd72992824659fcf28e1baddcb2def2f6eb859e435dc9
213a9b073fe08d62dc71ace2c7a1484891d1fd414501d6b69092de31fd944b33
c8d4b386bc49471e59b03d3e654c93ee3efb5900d591dab03033d07d5efc42b0

Total reclaimed space: 3.402kB

Patching server

Hit:1 http://de.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://mirror.hetzner.de/ubuntu/packages bionic InRelease                     
Hit:3 https://download.docker.com/linux/ubuntu bionic InRelease                     
Get:4 http://de.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]        
Hit:5 http://mirror.hetzner.de/ubuntu/packages bionic-backports InRelease           
Hit:6 http://mirror.hetzner.de/ubuntu/packages bionic-security InRelease            
Hit:7 http://mirror.hetzner.de/ubuntu/packages bionic-updates InRelease             
Get:8 http://de.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]      
Get:9 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]         
Fetched 252 kB in 1s (269 kB/s)    
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

Mon Apr 29 04:31:32 CEST 2019 - Done! Your system should be back online

Restoring permissions... this could take a few minutes

--------------------------------------------------
 cleanup system completed
--------------------------------------------------


--------------------------------------------------
 All done! Press Enter to return to the menu
--------------------------------------------------

 --->

**Comment by TechPerplexed** [comment]
Looking good :) Is everything working okay now?

**Comment by spladesrus** [comment]
Nope. Rclone has “lost” the profile. If I put it in again, it will retain it, but doesn’t actually work.

**Comment by spladesrus** [comment]
More specifically, I get this error:
2019/04/30 01:42:21 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults

**Comment by TechPerplexed** [comment]
I see... can you share the contents of your rclone.service file (in /etc/systemd/system)?

**Comment by spladesrus** [comment]
Sure. What commands do I need to run to get to it?

Also, I spent the night troubleshooting and got it all running after this series of troubleshooting steps:
Initial Reboot that caused Rclone and Plex to not work> Ran System cleanup> Installed Rclone and added profile(Profile did not stick)> Ran System Cleanup> Updated Rclone with profile> Ran system cleanup > Profile stuck around but was file system was unavailable, "Updated Rclone" to resolve. 

I am pretty confident that if I reboot it again, it will all fall out again so I can reboot it again whenever you are ready for me to.

**Comment by TechPerplexed** [comment]
A simple `nano` would do it (you can Google how). How are you installing Rclone? If done through Gooby your config file should default to your home folder, so I'm puzzled how it could have ended up in root. I'm pretty sure that is the "root"of your problem :)

**Comment by spladesrus** [comment]
Nice Pun. :)
I am installing Rclone through Gooby via the standard account created in the gooby setup. Contents of the rclonefs.service file is below.

  GNU nano 2.9.3           /etc/systemd/system/rclonefs.service                      
[Unit]
Description=Mount Google Drive (rclone)
After=syslog.target local-fs.target network.target

[Service]
EnvironmentFile=/var/local/Gooby/Docker/.env

Type=simple
User=USERNAME
Group=USERNAME
ExecStartPre=/bin/mkdir -p ${RCLONEMOUNT}
ExecStart=/usr/bin/rclone mount \
--allow-other \
--checkers 12 \
--checksum \
--delete-during \
--delete-excluded \
--dir-cache-time 96h \
--drive-chunk-size 32M \
--fast-list \
--gid ${USERID} \
--log-level INFO \
--log-file ${HOMEDIR}/logs/rclone.log \
--rc \
--rc-pass Go0by \
--rc-user gooby \
--timeout 1h \
--transfers 12 \
--tpslimit 10 \
--uid ${GROUPID} \
--umask 002 \
--config ${HOMEDIR}/.config/rclone/rclone.conf \
${RCLONESERVICE}:${RCLONEFOLDER} ${RCLONEMOUNT}
ExecStop=/bin/fusermount -uz ${RCLONEMOUNT}
ExecStop=/bin/rmdir ${RCLONEMOUNT}
Restart=always
[ File '/etc/systemd/system/rclonefs.service' is unwritable ]

**Comment by TechPerplexed** [comment]
Hmmm, that's looking good. Can you share the content of your /var/local/Gooby/Docker/.env file as well? Preferably both when things are working, and when things are getting wonky. I'm sure it can be sorted... It's just slightly more difficult for me to reply because I'm still traveling :s

**Comment by spladesrus** [comment]
I haven't been able to get this to happen again after having had it happen so many times -_- So I am going to close this for now.
