### ISSUE TITLE
How to add modifications to nginx?

### ISSUE THREAD

**Issue by Coxeroni** [TechPerplexed/Gooby#74]
I want to add a very tiny modification to the nginx proxy, namely increasing the allowed upload file size for nextcloud.
I tried to put the `/etc/nginx/vhost.d` folder outside the container to be able to modify it, but any modification to the nginx part of the compose file are overwritten at reboot, which I guess is done by design to keep the extremely vital proxy functional at any time.
The modification would expect the same fate when made inside the container I guess.

It would be great if the standard nginx compose could include an external mount for `/etc/nginx` or at least `/etc/nginx/vhost.d` to easily include custom config files, as jwilder also points out for his container:
https://github.com/jwilder/nginx-proxy#custom-nginx-configuration

**Comment by TechPerplexed** [comment]
I'll ask the expert, @Coxeroni :) Thanks!

**Comment by Coxeroni** [comment]
Thanks for that.
I might try to contribute by editing it "myself", when I have understood how this Github thing works :D 
The change itself is minor and I already have done it on my VPS and therefore confirmed that pulling the vhost.d doesn't break nginx and adds the functionality needed for modifying nginx itself.

**Comment by TechPerplexed** [comment]
Thanks!!! Perfect - and according to Kelinger it shouldn't break anything, so I'm sure we're golden. Let's make this permanent :)

**Comment by Coxeroni** [comment]
Great! Thanks for incorporating this!
