### ISSUE TITLE
Emby connect linking

### ISSUE THREAD

**Issue by spladesrus** [TechPerplexed/Gooby#76]
Has anyone gotten Emby Connect to successfully work? If so, what port settings (internal and external) did you use? 

After some googling, I found that docker ps will list all port settings set up in Docker? 
> Ubuntu-1804-bionic-64-minimal:~$ docker ps
> CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                    PORTS                                                                                          NAMES
> fa6f6175d4cf        emby/embyserver:latest                   "/init"                  11 hours ago        Up 11 hours (unhealthy)   1900/udp, 7359/udp, 8096/tcp, 0.0.0.0:2096->8920/tcp                                           emby
> 5882d29420e6        jrcs/letsencrypt-nginx-proxy-companion   "/bin/bash /app/entr…"   23 hours ago        Up 23 hours (healthy)                                                                                                    letsencrypt
> 408005ce3b2b        plexinc/pms-docker                       "/init"                  23 hours ago        Up 23 hours (healthy)     3005/tcp, 1900/udp, 32410/udp, 8324/tcp, 32412-32414/udp, 32469/tcp, 0.0.0.0:8443->32400/tcp   plex
> 1288c42d0051        jwilder/nginx-proxy:alpine               "/app/docker-entrypo…"   23 hours ago        Up 23 hours (healthy)     0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                                       nginx-proxy

In this case, it is showing 1900, 7359, and 8096 are listed here. However after looking at the emby yaml, I see that it explicity lists 2096(http?), 8029(https?) and the virtual port 8096. See in bold. 

> emby:
>     restart: unless-stopped
>     image: emby/embyserver:latest
>     container_name: emby
>     hostname: emby
>     cpu_shares: 8192
>     ports:
>       - **2096:8920**
>     volumes:
>       - ${CONFIGS}/Emby:/config
>       - ${MEDIA}:/Media
>       - /tmp:/transcode
>     environment:
>       - ADVERTISE_IP=https://emby.${MYDOMAIN}
>       - UID=${USERID}
>       - GID=${GROUPID}
>       - GIDLIST=44
>       - TZ=${TIMEZONE}
>       - VIRTUAL_HOST=emby.${MYDOMAIN}
>       - VIRTUAL_PORT=**8096**
>       - VIRTUAL_PROTO=http
>       - VIRTUAL_NETWORK=nginx-proxy
>       - LETSENCRYPT_HOST=emby.${MYDOMAIN}
>       - LETSENCRYPT_EMAIL=${MYEMAIL}

Maybe I am just looking into this too much? I am able to access the web panel at emby.mydomain.com and at emby.mydomain.com:80 but am unable to link anything via emby connect.

**Comment by TechPerplexed** [comment]
What exactly is Emby Connect?

**Comment by spladesrus** [comment]
It is what you use to connect mobile devices and consoles. See here: https://emby.media/connect.html
When connecting to the server, it is unable to connect through the app.

**Comment by TechPerplexed** [comment]
Sorry for the late reply.... but I'm home at last and almost able to think again 😆  I just installed Emby on my Android phone and logged in with Emby connect - it's working out of the box. Not sure why it wouldn't work for you... but since you can connect the "other" way, I shall close this issue as "solved" :)
