### ISSUE TITLE
Could not read folder

### ISSUE THREAD

**Issue by Trentflix** [TechPerplexed/Gooby#77]
After a few days of running Gooby I begin to have trouble when attempting to transcode files. I always get the same three error messages in the Plex console logs (with different filenames of course):

[Transcoder] [eac3_eae @ 0x994800] EAE timeout! EAE not running, or wrong folder? Could not read '/tmp/pms-2c167e12-3787-46cc-a4f3-969f543290cf/EasyAudioEncoder/Convert to WAV (to 8ch or less)/337wvya3eupnv1th4lun3mqv_31008-0-11.wav'
[Transcoder] [eac3_eae @ 0x994800] error reading output
[Transcoder] Error while decoding stream #0:1: Input/output error

If I restart the server or run a system clean-up everything works again but this shouldn't be necessary.

**Comment by TechPerplexed** [comment]
You're right, it should happen but Plex is a stubborn one :) I'm pretty sure the problem is not with Gooby, but will leave this open in case the gurus know the answer. Alternatively, you might want to ask your question in the Plex forums - maybe they know what could cause it!
