### ISSUE TITLE
Reopening #76 - Emby connect issues

### ISSUE THREAD

**Issue by spladesrus** [TechPerplexed/Gooby#78]
Unfortunately, EMBY connect is not working for me. While I am able to access it through a browser, I cannot access it through any app requiring EMBY connect. Did you change any settings when you setup yours?

**Comment by TechPerplexed** [comment]
Nope, I have no idea. Did you ask this in the Emby forums? You might try the information here: https://github.com/TechPerplexed/Gooby/wiki/Origin-Certificate
Otherwise, I'm out of options!

**Comment by spladesrus** [comment]
I’d didnt setup the certificate. I guess that’s the only thing I have different? I’ll try setting that up tomorrow. Would you mind sharing what port settings you have setup under server settings? This way I can confirm I have everything else setup properly.

**Comment by TechPerplexed** [comment]
You don't need to mess with port settings on the server, Docker looks after that.

**Comment by spladesrus** [comment]
Okay, after setting up the certificate using the link you provided Emby started working for me(With the exception of IOS devices but I think this is a separate issue). 

Thanks for the support.
