### ISSUE TITLE
how to add a site to ngnix ?

### ISSUE THREAD

**Issue by Whitexp** [TechPerplexed/Gooby#79]
hi,

I installed gooby a while back, and it comes working fine, now I would like to create a site using my current vps, how can I modify ngnix for this?

thanks

**Comment by TechPerplexed** [comment]
The good news is: Gooby supports this right out of the box, no need to modify anything except your component file :)

Here's a sample file that you can to copy to your Gooby config folder with all the components:
https://github.com/TechPerplexed/Gooby/blob/master/scripts/components/80-httpd.yaml

By default it uses your regular domain with the subdomain of web.yourdomain.com. If you need to use another domain, just edit the lines

`      - VIRTUAL_HOST=web.${MYDOMAIN}`
and
`      - LETSENCRYPT_HOST=web.${MYDOMAIN}`

to something like

`      - VIRTUAL_HOST=www.yourdomain.com`
and
`      - LETSENCRYPT_HOST=www.yourdomain.com`
