### ISSUE TITLE
Plex server unreachable

### ISSUE THREAD

**Issue by Ninazuu** [TechPerplexed/Gooby#80]
Hi there, I set up following your guide yesterday with a few tweaks as I am using Google Team Drive as my server so needed to input a client name and secret etc.

All was working fine until a couple of hours ago.  I noticed that the remote access was disabled so I tried to re-enable using port 8443 which is how I had configured it for secure connection before.  I am also using oneprovider for my server.

The server then basically kicked me out, it says my server is unavailable.  I have checked that the rclone mount is working and that plex is loading and have run the cleanup program in Gooby, everything seems fine.  Howeveer, I am still effectively locked out. 

Is this an issue with how I have setup the server or something expiring after 24 hours or is oneprovider blocking something?

Any help appreciated!!

**Comment by TechPerplexed** [comment]
Hi, normally you shouldn't need to manually change any ports, because Docker looks after its own ports. What exact command did you give? 
For example if you close the ssh port (22), you would indeed lock yourself out of your server and the only way to get it back is through the Oneprovider support team...

**Comment by Ninazuu** [comment]
Hi there, thanks for the response.  I installed Emby to see if it was just Plex being annoying.

All setup fine as well but cannot connect externally to Emby using Emby Connect either. 

The port for Plex is definitely open for Oneprovider, they say they don't block any ports in my location, however the Emby port does seem to be blocked when I checked it so that may be the issue there.

I am at a bit of a loss as to why trying to re enable remote access in Plex would effectively disable the server or if there is something more fundamental with how I have set it up that is wrong.

The only other thing I can think of is that the email I used for the certificates was my personal email, I have my own domain and used that but don't have an email address for it, would this effect it?  

Sorry for the nooby questions I am very lost!

**Comment by TechPerplexed** [comment]
No worries about the nooby questions, we all gotta start somewhere :)

Easy answer first: the certificate email is just to inform you that your certificates will be renewing after 90 days, no other purpose. You can indeed use any email at all, even a fake one if you don't wish to get these mails. No worries there and nothing to do with accessing your server!

However, I'm lost as to what exactly the issues you are experiencing. What do you mean by opening ports in Plex? Are you talking about changing settings from WITHIN Plex? Again, what exactly did you change?

**Comment by Ninazuu** [comment]
Hello again, was the Remote Access setting inside Plex I changed.  It had a green tick next to it yesterday but today it was red.  I tried to re enable it but it has locked me out.

Looking at your cloudflare guide, should I try to do that and get the certificates and see if that makes a difference?  I will have to reinstall Plex most likely.

**Comment by TechPerplexed** [comment]
Well you could and I would recommend it for various reasons, but the Cloudflare setting is optional. You will need to get your Plex accessible first. Can you access Plex directly by typing in your server address, eg plex.yourdomain?

I have a feeling your Plex might have lost its token somehow (this seems to be a recent bug in Plex itself, according to their forums). If you can't access it at all, you may indeed need to uninstall it and then reinstall it from the menu, and follow the steps to get your token again. 

Then, all that should be needed for external access is open port 8443 in the remote access settings, and it should be okay:

![Screenshot 2019-05-30 10 19 59](https://user-images.githubusercontent.com/15312691/58650838-fcef6f00-82cc-11e9-9ede-3f90fedc9147.png)

Once all that is working fine, then you can consider setting up the Cloudflare certificate - that will work for Emby as well.

**Comment by Ninazuu** [comment]
Hi again.

Wow this has been a challenging one.  So I decided in my infinite wisdom to go ahead with the cloudflare change to see if it would make a difference, it instantly did, I was straight back into the Plex server and all was working.  Then after about 20 minutes it started flickering and I lost settings access.  I decided to reinstall Plex, went to uninstall and did not delete my settings.  I somehow managed to log out of my server in the Plex app at the same time so now cannot claim the server as when I try to uninstall and reinstall Plex through Gooby it will not ask for a Plex claim token as the settings are still there...  I am kind of stuck here, is there a way to manually remove all the Plex settings and generate a new token?

Also, since I moved to Cloudflare I now cannot access Emby!  The port 8096 is closed on my dedicated server, and I cannot open it Oneprovider helpfully linked me to a guide to open ports in Ubuntu and I have but using a port checker the port is still blocked.

**Comment by TechPerplexed** [comment]
Yeah, so. Forget contacting Oneprovider for a while, and definitely, really, absolutely forget about messing with ports and/or Cloudflare. You are trying to fly when you haven't managed to walk yet, a great recipe for disaster 😉 

At this point you're best off to start from scratch, since you only installed everything yesterday - then claim your Plex server (through the token) and don't mess with any settings for a few days. No touching of ports, no messing with settings... until things are stable (or until you find out what is making your Plex installation unstable) 😄

**Comment by Ninazuu** [comment]
Hi again, thanks for your patience.

I am on the long road of reinstalling, am hoping it doesn't happen again!

:D

**Comment by TechPerplexed** [comment]
If it does, we will try some methodical troubleshooting. We'll tame that beast :D
