### ISSUE TITLE
Plex unable to read Rclone

### ISSUE THREAD

**Issue by ASchluterman** [TechPerplexed/Gooby#81]
Hi!

First I just want to say thanks for everything you have done to put this together. It truly is an incredible resource! I built a server roughly 8 months ago based on your legacy tutorials, and am currently attempting to create a new server following the simple Gooby tutorials.

My issue seems to be related to a few of the other individuals that have posted, but I have not been able to find a solution through the comments. 

Everything through the installation appears to be working fine. I get Gooby up and running just fine. I install Rclone and Plex without what appears to be a hitch. Plex server is up and running, however, when I attempt to add my media through Rclone, none of my folders are being recognized. 

I have removed Rclone a handful of times and reinstalled it, as well as run a system clean without success. 

Any advice would be greatly appreciated!

**Comment by TechPerplexed** [comment]
Hi and happy to hear the project is useful to you 😄 
As for your question, first of all, can you access your media by typing `ls /mnt/Google`?

If that is the case, then your media from within Plex should be accessible through the folder /Media. Does that answer your question or is something else not right yet?

**Comment by ASchluterman** [comment]
Thanks for the quick reply!

Yes, I am using Google Drive and I'm getting an error back stating "ls: cannot access '/mnt/Google': No such file or directory".

Which makes me think it is not installing correctly?

**Comment by bdschuster** [comment]
See corrected directory, should be lower case "google", so /mnt/google 
Also, did you happen to move VPS's to another hosting company? If so, may I ask who? Some require you to email support and allow the FUSE module to be enabled on you VPS. Some will not enable it.

**Comment by ASchluterman** [comment]
Thank you for the clarification. 

All it spits now out is "Downloads" and nothing with regards to my Google Drive. 

I am using DirectSpace for both of my servers. My original server I did not need to contact anyone to enable FUSE, but I suppose it could be the issue with the new one.

Is there a way to verify if it is enabled? Thanks for all of your help.

**Comment by TechPerplexed** [comment]
Sounds like @bdschuster nailed it and your provider hasn't enabled Fuse. Check if it is installed with the command `fusermount -V` which should spit out something like `fusermount version: 2.9.7` if it is. Otherwise you'll need to raise a ticket with your provider for them to enable it!

**Comment by ASchluterman** [comment]
It appears FUSE is enabled as I received back `fusermount version: 2.9.7` with the command you provided. 

If only that were it!

**Comment by bdschuster** [comment]
Are you using a team drive?

**Comment by ASchluterman** [comment]
All of my media is not stored in a team drive portion of Google Drive, so no.

**Comment by ASchluterman** [comment]
On a potentially related note, after restarting the server, Plex no longer seems to be booting up.

Perhaps an issue with Docker?

**Comment by TechPerplexed** [comment]
Did you specify a folder for your media in Rclone? Remember, Linux is case sensitive (as you found out from my previous mistake, heh).

Since Plex comes back after a system clean, it seems as if Rclone is working just fine, as you indicated before.

What do you get when you type `ls /mnt/rclone`?

**Comment by TechPerplexed** [comment]
Also, what do you get when you type `rclone lsd Gdrive:`? (replace Gdrive with whatever you named your mount)

**Comment by ASchluterman** [comment]
Following your tutorial, I specified the folder at the end of setting up Rclone to be "Media", and named the mount "Gdrive".

From the first command it spat out `ls: reading directory '/mnt/rclone': Input/output error`.

The second command gave me `2019/06/03 07:33:08 ERROR : : error listing: couldn't list directory: googleapi: Error 404: File not found: ., notFound
2019/06/03 07:33:08 Failed to lsd: couldn't list directory: googleapi: Error 404: File not found: ., notFound`

**Comment by TechPerplexed** [comment]
Sounds like Rclone can't communicate with Google. I suggest you remove your Rclone installation from the menu, then reinstall it. Then remove your Rclone credentials that you created and start from scratch with those as well (see https://www.techperplexed.ga/2018/03/part-2-installing-necessary-apps.html - yes I know you've done this succesfully before) 😄 

Then see if your mount is working properly... fingers crossed!

**Comment by ASchluterman** [comment]
I am honestly unsure why that worked, but Rclone seems to be mounted correctly! I legitimately walked through that exact process three or four times yesterday afternoon. `rclone lsd Gdrive:` is now returning my Google Drive folder structure. 

`ls /mnt/rclone` is not returning anything, however. Unsure if that is correct or not, but at least it isn't spitting back an error.

Whoo Hoo! :)

Unfortunately, something still appears to be off on the Plex side of things. When I go to add a library and direct it to the mount, Plex it is not retrieving the folder structure. I ran a system clean up with the same result. Should I uninstall/reinstall Plex?

**Comment by TechPerplexed** [comment]
Whoo hoo, progress!

No, reinstalling Plex won't help you, as long as the /mnt/google can't take any data from /mnt/rclone, the folder /Media in Plex will remain empty. Yeah I never said things are simple 😆 

However, I'm sure it'll be downhill from now on. First, you are absolutely positive that your movies are in Gdrive:Media right? Can you verify this by typing `rclone lsd Gdrive:Media` - it should give you a list of your Plex folder structure.

**Comment by TechPerplexed** [comment]
There's your answer then 😄 You will need to uninstall Rclone one last time, no need to remove your remote this time. Reinstall it and don't specify a folder Media, but just leave it empty since you're using the root.

Alternatively, you could move those 6 folders in a single folder named Media and "free up" your Google drive for other folders and files (such as the weekly Gooby backup which I definitely recommend).

**Comment by ASchluterman** [comment]
There it is! Everything is pulling up in Plex as it should be. 

I actually might just do that, although I am hesitant to disrupt the original server. The purpose of this new server was to get it up and going with your new version of Gooby (the original was established back when it was GooPlex). It got caught mid update between something and currently operates in some limbo version of itself without a menu directive. Honestly I'm not sure how it hasn't failed yet!

Going to give it a shot though!

I'm assuming the Gooby backup wouldn't work correctly without the media in a "Media" folder?

**Comment by TechPerplexed** [comment]
> There it is! Everything is pulling up in Plex as it should be.

Yippee! I shall close this issue then, but you can still add to it should the need arise :)

> I'm assuming the Gooby backup wouldn't work correctly without the media in a "Media" folder?

Heck no!! It'll work just fine 😄 Gooby is FLEXIBLE and will work the way YOU want it... there is no need for you to adapt your system to Gooby. If it works better for you to leave the root as it is, that'll be perfectly fine. You can still create the backup, then the Backup folder will reside side by side with your current Plex folders.

**Comment by ASchluterman** [comment]
Thank you so much for your time and patience working through this with me. I greatly appreciate it!

**Comment by TechPerplexed** [comment]
No worries at all :) It's easy to troubleshoot someone who is communicative... and the problem proved to be fairly straightforward in the end. Glad you got it all resolved!

If you ever decide to use a folder like Media for your Plex collection, the good news is that in Gooby, as far as Plex (and Emby, Radarr, Sonarr, etc) are concerned, nothing changes. You won't have to rescan your files since they still use /Media as the internal (within Docker) mount.

However you would need to change each library in old GooPlex environment to point to the new location... and Plex can take a long time to rescan!
