### ISSUE TITLE
Fixing IP addresses for containers?

### ISSUE THREAD

**Issue by theboywonder** [TechPerplexed/Gooby#82]
Hi,

Is there any way to fix the IP addresses used by the containers? My issue is that everytime I restart the container, or restart the server on which they run, IP addresses change and this often breaks the link between tautulli and Plex.

Thanks!

**Comment by bdschuster** [comment]
Why not use the hostnames? Plex is just simply "plex" when setup in tautulli and the hostnames never change.

**Comment by theboywonder** [comment]
I wasn't aware that I could type in that field in Tautilli - I thought it was limited to the dropdown options! I've done that though, and will try it out. Thanks!

**Comment by bdschuster** [comment]
No worries. That should work for you. Let us know if you need anything else!

**Comment by TechPerplexed** [comment]
Right on, thanks @bdschuster 😄 

To give some background as to why and I quote from my friend @kelinger:

> The intent of Docker is to provide portable containers that can be run anywhere and who’s location doesn’t matter.  Just as the same Plex container can run on a CentOS 6 or Ubuntu 18 server, the server itself may be in Paris, France or Paris, Texas.  Getting hung up on IP addresses is a sure-fire way to have something work one time and the same configuration not work another time.  DNS from the outside world is used to point a common URL (eg, plex.mydomain.com) to the correct hosting server while internal Docker hostnames (plex, deluge, radarr, jackett) are used to communicate between the containers without worrying about whether the IP address changed or, in more advanced configurations, whether that other container is even hosted on the same server.  
> While it is POSSIBLE to give a container a fixed IP address and, thus, lock in an unchanging IP configuration, such blasphemy will not be part of this project.

Well, we're joking with that last bit of course, but yeah, that's the reason why you need to choose the internal host name, rather than an internal IP address 😆
