### ISSUE TITLE
Unique Question - Variables

### ISSUE THREAD

**Issue by bdschuster** [TechPerplexed/Gooby#86]
Hello!

I have a question unique to one of my server setups. I have a decently powerfull server at my house that I have multiple Plex containers installed using Gooby, I have edited a few things here and there, obviously changing ports for external communication to Plex and also adding/editing two of your scrips to add variables for PLEXCLAIM2 and PLEXCLAIM3. Problem I'm forseeing, since currently I have commented out updating Gooby from the cleanup script, is when I do decide to uncomment that and update, when I run a clean, your build environment script will more than likely rebuild the .env file, removing PLEXCLAIM2 and 3. Will that break Plex if it's not in there, even after I already have setup on my Plex account? 

I actually have 3 physical servers running in the cloud, for load balancing reasons since I have over 50 users. This server, located at home, will only strictly be fore Live TV support to my users since I can't have an antenna in a data center ..lol, so yeah, any help appreciated. And BTW, Live TV is running perfect, and it helps I'm in-between Chicago and Milwaukee, so I get both cities. 

Thanks in advance.

-Me

**Comment by TechPerplexed** [comment]
Wow, you have quite the setup :)

Unless your question entails more than I understand (not at all unlikely), you shouldn't have any problems at all. In fact, you wouldn't even need a PLEXCLAIM2 and 3... because once your server is claimed, it's claimed for life and you no longer need the token.
Even after you make a backup and restore it on a new server, your setup will remain intact.

The only thing you shouldn't do (and haven't, obviously), is use the same token for each of your servers - that'll definitely get you in trouble. But, as long as you give each server a unique ID (through the token claiming process), you should be fine.

Now, again, I might have completely misunderstood your question, if so, I'm sure you will elaborate 😸

**Comment by bdschuster** [comment]
Yeah, you answered it perfectly, I'll try in a bit and see if it works. Thanks as always!

**Comment by TechPerplexed** [comment]
Let me know how it goes!

**Comment by bdschuster** [comment]
Everything is working as it should! Thank you! Now if I could just figure out what you are doing with that Upgrade Service 🤣🤣,

**Comment by TechPerplexed** [comment]
Haha, nothing fancy just yet... Just consolidating three folders into the Docker folder, where they belong 😃

**Comment by bdschuster** [comment]
Don't get me all excited like that! 🤣 Name it something like consolidation 🤣🤣

**Comment by TechPerplexed** [comment]
Lol! Well, still leaving options open... Kelinger and I are testing an even more "ban proof" setup of Rclone, but I want to make sure the upgrade is smooth for all users.

If you are interested: the service itself well control everything centrally, that is to say, not just streaming, but also uploading, downloading, file checking, etc.

The advantage is that we can tweak all settings to “maximum”, such as the number of API calls and no longer individually for each action.

Testing has been successful for the last 6 months, but upgrading is a bit moody still... And I don't really want to break things, even temporarily, and get people all grumpy :D

**Comment by bdschuster** [comment]
Makes sense, what are you running into during upgrade? And are you able to fix the issue after the upgrade?

**Comment by TechPerplexed** [comment]
It's more that I'm afraid to "mess" with people's setups, and to some degree this would be needed. The new Rclone commands would use the "RC" feature, something we haven't utilized yet.
To that end the Rclone service file will need to contain rc settings including a simple password and user (for internal use only, no risks involved and no complicated pw needed) - this has already been default for new installations for a while, but people with older installations might not have it yet. 

That would mean either "forcing" an updated rclonefs.service file and potentially kill whatever customizations people made to their service file - OR - go ahead with the update and wait for the complaints to come in that uploading no longer works and then tell them "yeah well you need to reinstall Rclone".

I haven't quite decided yet which is the lesser evil and hoping to hear opinions 😁 

Also, thanks for all your help today with other issues 👍

**Comment by bdschuster** [comment]
I would just update the readme to say that of you have an older version of Gooby, you may need to reinstall rclone, and lose any custom rclone customizations. I know, not everyone will read that, but hey, it's gotta happen at some point, and at least you know how to correct the issue quick. We will be here to support you too with letting people know. 

And no worries, I've gotten very familiar with all the components of Gooby, so troubleshooting is just in nature considering I work in IT and it's all i do...lol

**Comment by TechPerplexed** [comment]
Great 😄 It's always nice when you know a system inside and out... proof of the pudding is the ability to assist other in making it their own 👍 

As for the update, I still have to go ahead and set up a temp server to see if everything else goes smoothly... besides, it IS summer so it might be a while. And then even more people will have a compatible setup already, haha.

You can "admire" the new codes already: https://github.com/TechPerplexed/Gooby/blob/rctest/scripts/cron/syncmount.sh (line 46) and
https://github.com/TechPerplexed/Gooby/blob/rctest/scripts/cron/backup.sh (line 26)

If you want to test this, make sure your Rclone service is up to date (duh). You also need to add these lines to the bottom of the $HOME/.config/rclone/rclone.conf file:

```
[Local]
type = local
nounc =
```

If they're not there yet, could you please try if 

```
cat $HOME/.config/rclone/rclone.conf | grep "[Local]" > /dev/null
		if ! [[ ${?} -eq 0 ]]; then
			echo [Local] >> $HOME/.config/rclone/rclone.conf
			echo type = local >> $HOME/.config/rclone/rclone.conf
			echo nounc = >> $HOME/.config/rclone/rclone.conf
		fi
```

adds those lines?

**Comment by bdschuster** [comment]
Want me to try this on my existing install (a lesser used server..lol)? Or want me to try and install fresh in one of my test VM's?

**Comment by TechPerplexed** [comment]
Adding those 3 lines won't impact anything, so you can test that anywhere. As for the whole setup... "insert all standard disclaimers about things that can go wrong" lol!

**Comment by bdschuster** [comment]
🤣🤣 no worries ..just a test VM Server, if it breaks, I just have a snapshot to go back to my standard install before installing Gooby. Lol...is it in a different Branch, for this test version? 

Also, can you please close out that other issue? it's fixed, I forgot I don't have permission to close other people's issues, only mine 🤣

**Comment by bdschuster** [comment]
@TechPerplexed Code looks good! Also, lines were already in the rclone config...I actually noticed the "Local" when editing rclone config , and wondered what it was...lol

**Comment by TechPerplexed** [comment]
Haha great, ok, will do that and thanks for confirming the code is already there for newer setups 🥇 

The test version is a different branch, but it's not up to date (it's just there to copy into the main branch once I feel confident enough to go ahead with it). If you want to test this, you're best off to just copy those two files into your opt/Gooby folder and prevent it from updating, like you did before :)

**Comment by bdschuster** [comment]
Sounds good. I'll test this later today and let you know.

**Comment by TechPerplexed** [comment]
If you would like a more direct line of communication... my email address is my first name and last name at Gmail. My last name is the same as a famous poet from Scotland whose first name is Robert (he wrote an ode to a mouse). My first name I believe you already know.... if not I'll drop further hints 😃 

That should be cryptic enough to confuse even the most determined bot 😆

**Comment by bdschuster** [comment]
I know who the poet is, but cannot for the life of me remember your first name 🤔 and you can remove the previous comment for security reasons since I figured that out.

**Comment by TechPerplexed** [comment]
Haha ok, done. My first name is Sophia :)
