### ISSUE TITLE
No TV/Movies Folders

### ISSUE THREAD

**Issue by VeelaCleave** [TechPerplexed/Gooby#87]
Sorry new to docker stuff so might be a simple fix, in your walkthrough/guide you have a screenshot that looks like this:

`
![image](https://user-images.githubusercontent.com/1869884/59862581-f6f42780-937a-11e9-9a98-a8fcaa148efa.png)
`
However my installation is not adding the TV Shows, Movies folders.  If I add Media to sonarr and radarr and then add Media to plex as either a TV or Movie source it then has multiple copies of the same content due to it adding the /Media/Downloads folder as well.

I can't for the life of me work out where the /Media folder would be so I could add those folders manually?  Any ideas!

Thanks for the awesome management tool though :)

**Comment by bdschuster** [comment]
Are you using Google Drive?

**Comment by VeelaCleave** [comment]
> Are you using Google Drive?

I set up rclone initially with my Google Drive yes, and Oh....  Is there a way to stop /Media/Downloads from syncing to google drive then?

**Comment by bdschuster** [comment]
So, you are trying to use local storage and not Google Drive?

**Comment by VeelaCleave** [comment]
> So, you are trying to use local storage and not Google Drive?

I followed the guide, created a google drive and added it etc. It's completely fresh based off;

At the moment my Google Drive is empty, it's a fresh new business one.

`https://www.techperplexed.ga/p/index.html`

The 3 step install.  I've not yet downloaded anything, but when I go to Sonarr, I can see the /Media but cannot set it to /Media/TV etc.  Those folders do not exist.

**Comment by bdschuster** [comment]
Correct, just go to your Google Drive and add those folders. The guide is assuming you already had an established library on Google Drive.

**Comment by VeelaCleave** [comment]
> Correct, just go to your Google Drive and add those folders. The guide is assuming you already had an established library on Google Drive.

Ah ok thank you, how often will it download from Google Drive?  Added those folders a few minutes ago, just wandering how long I should wait patiently :P

**Comment by bdschuster** [comment]
When you installed rclone and towards the end, when it asked what folder would you like to use in Google Drive, did you just leave blank for "/" directory of Google Drive? If so, those folder must be added to the root directory of your GD, also, did you use team drive? 
As far as you adding those folders on your Google drive, the sync is pretty much instant, as for uploading to Google drive (things you downloaded), happen at every 15mins of the hour. Example: 1:00, 1:15, 1:30, 1:45, 2:00, etc. And depending on file size and upload speed, they may take a moment to sync, mine, 1GB upload, for a decent sized movie can take up to around 10-15mins, if there are multiple files downloaded in that 15min period, it may take longer. Can you do me a favor and show me the output of 'ls -al /mnt/rclone' ?

**Comment by VeelaCleave** [comment]
`veela@valhalla:~$ ls -al /mnt/rclone
total 0
`
I guess I messed something up, I set it to "Media" as per the guide

**Comment by bdschuster** [comment]
Ok, that's fine. So in Google Drive, make sure you add the folder Media, then inside that folder add your TV and Movies directories. After that, run gooby, and do a system cleanup ( menu E then C). When that is complete run 'ls -al /mnt/rclone' again and see if your folders are in there.

**Comment by VeelaCleave** [comment]
> Ok, that's fine. So in Google Drive, make sure you add the folder Media, then inside that folder add your TV and Movies directories. After that, run gooby, and do a system cleanup ( menu E then C). When that is complete run 'ls -al /mnt/rclone' again and see if your folders are in there.

Yep that worked, didn't realise the guide was aimed more at people who already had an existing library!  Will start moving mine across shortly :)

**Comment by bdschuster** [comment]
Yeah, most people already have their library uploaded to Google or at least have a couple things setup in there already, so no worries. Glad that worked out! I'll go ahead and close this out, but if you need help with anything else, feel free to continue to comment here, it make a new issue if unrelated. Have a good day!

**Comment by TechPerplexed** [comment]
Glad it's all resolved! Closing this issue now :)
