### ISSUE TITLE
Plex can't read the "/Media" files

### ISSUE THREAD

**Issue by JustSquiddy** [TechPerplexed/Gooby#88]
Hi there,

i installed gooby on my ubuntu server and mounted with rclone my Google Drive. Everything works fine, i can access my media folder with `rclone lsd Gdrive:Media`, but it seems that the plex server can't open it, so it shows nothing. i've already read other issues, but nothing helped.
`fusermount -V` returns `fusermount version: 2.9.8`

**Comment by bdschuster** [comment]
Hello! Sorry you are having this issue. What does

**Comment by bdschuster** [comment]
Hello! Sorry you are having troubles, let's see what we can do. What does `ls -al /mnt/rclone` return? Does it contain your media?

**Comment by JustSquiddy** [comment]
thanks for the quick answer

>  What does `ls -al /mnt/rclone` return?
nope it doesn't contain my data...

**Comment by bdschuster** [comment]
So let me get a little history here. On your Google Drive, does it contain a folder called "Media" (yes caps matter) in your root directory, the highest level? Then inside that folder you have TV and Movies or something like that? Is this a team drive or just using your drive?

**Comment by JustSquiddy** [comment]
Well, on my Google Drive is the Media Folder and I am alone on this drive.

**Comment by bdschuster** [comment]
Ok, lastly, when installing rclone via the Gooby menu, when it asks where your media is located, did you leave that blank, or did you type "Media"?

**Comment by JustSquiddy** [comment]
i typed "Media"

**Comment by bdschuster** [comment]
what does `sudo service rclonefs status` come back as, does it say "active" or is there an error of some sort?

**Comment by JustSquiddy** [comment]
`* rclonefs.service - Mount Google Drive (rclone)
   Loaded: loaded (/etc/systemd/system/rclonefs.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-06-24 20:47:58 UTC; 39min ago
  Process: 198798 ExecStart=/usr/bin/rclone mount --allow-other --checkers 12 --checksum --delete-during --delete-excluded 
  Process: 198797 ExecStartPre=/bin/mkdir -p ${RCLONEMOUNT} (code=exited, status=0/SUCCESS)
 Main PID: 198798 (code=exited, status=1/FAILURE)

Jun 24 20:47:58 vps-zap405560-1 systemd[1]: rclonefs.service: Service RestartSec=100ms expired, scheduling restart.
Jun 24 20:47:58 vps-zap405560-1 systemd[1]: rclonefs.service: Scheduled restart job, restart counter is at 18.
Jun 24 20:47:58 vps-zap405560-1 systemd[1]: Stopped Mount Google Drive (rclone).
Jun 24 20:47:58 vps-zap405560-1 systemd[1]: rclonefs.service: Start request repeated too quickly.
Jun 24 20:47:58 vps-zap405560-1 systemd[1]: rclonefs.service: Failed with result 'exit-code'.
Jun 24 20:47:58 vps-zap405560-1 systemd[1]: Failed to start Mount Google Drive (rclone).`

**Comment by JustSquiddy** [comment]
* rclonefs.service - Mount Google Drive (rclone)
   Loaded: loaded (/etc/systemd/system/rclonefs.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-06-24 20:47:58 UTC; 39min ago
  Process: 198798 ExecStart=/usr/bin/rclone mount --allow-other --checkers 12 --checksum --delete-during --delete-excluded 
  Process: 198797 ExecStartPre=/bin/mkdir -p ${RCLONEMOUNT} (code=exited, status=0/SUCCESS)
 Main PID: 198798 (code=exited, status=1/FAILURE)

Jun 24 20:47:58 vps-zap405560-1 systemd[1]: rclonefs.service: Service RestartSec=100ms expired, scheduling restart.
Jun 24 20:47:58 vps-zap405560-1 systemd[1]: rclonefs.service: Scheduled restart job, restart counter is at 18.
Jun 24 20:47:58 vps-zap405560-1 systemd[1]: Stopped Mount Google Drive (rclone).
Jun 24 20:47:58 vps-zap405560-1 systemd[1]: rclonefs.service: Start request repeated too quickly.
Jun 24 20:47:58 vps-zap405560-1 systemd[1]: rclonefs.service: Failed with result 'exit-code'.
Jun 24 20:47:58 vps-zap405560-1 systemd[1]: Failed to start Mount Google Drive (rclone).

**Comment by JustSquiddy** [comment]
* rclonefs.service - Mount Google Drive (rclone)
   Loaded: loaded (/etc/systemd/system/rclonefs.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-06-24 20:47:58 UTC; 39min ago
  Process: 198798 ExecStart=/usr/bin/rclone mount --allow-other --checkers 12 --checksum --delete-during --delete-excluded 
  Process: 198797 ExecStartPre=/bin/mkdir -p ${RCLONEMOUNT} (code=exited, status=0/SUCCESS)
 Main PID: 198798 (code=exited, status=1/FAILURE)

Jun 24 20:47:58 vps systemd[1]: rclonefs.service: Service RestartSec=100ms expired, scheduling restart.
Jun 24 20:47:58 vps systemd[1]: rclonefs.service: Scheduled restart job, restart counter is at 18.
Jun 24 20:47:58 vps systemd[1]: Stopped Mount Google Drive (rclone).
Jun 24 20:47:58 vps systemd[1]: rclonefs.service: Start request repeated too quickly.
Jun 24 20:47:58 vps systemd[1]: rclonefs.service: Failed with result 'exit-code'.
Jun 24 20:47:58 vps systemd[1]: Failed to start Mount Google Drive (rclone).

**Comment by bdschuster** [comment]
Well that's a problem. Before I get deep into this, can you please try and do a system cleanup real quick?  Gooby menu E then C.

**Comment by JustSquiddy** [comment]
okay, 
it threw that:
`Job for mergerfs.service failed because the control process exited with error code.
See "systemctl status mergerfs.service" and "journalctl -xe" for details.`

and now it is stuck at `Waiting on mounts to be created...`

**Comment by TechPerplexed** [comment]
Hmmm... weird... so what do you get when you type `systemctl status mergerfs.service`? (might need to use sudo, not sure).

That said I did just correct a tiny issue in mergerfs, but I can't imagine that is your problem since the current version has been live for 5 months.

You could try to uninstall and reinstall Rclone (no need to update your credentials), worth a try perhaps...

**Comment by JustSquiddy** [comment]
* mergerfs.service - MergerFS overlay writable storage and local mount
   Loaded: loaded (/etc/systemd/system/mergerfs.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-06-24 21:35:16 UTC; 19min ago
  Process: 266623 ExecStart=/usr/bin/mergerfs -o use_ino,hard_remove,auto_cache,sync_read,allow_other,category.action=all,category.create=ff ${UPLOADS}:${UNSYNCED}:${RCLONEMOUNT} ${MOUNTTO} (code=exited, status=1/FAILURE)
  Process: 266622 ExecStartPre=/bin/mkdir -p ${UPLOADS} ${MOUNTTO} ${UNSYNCED} (code=exited, status=0/SUCCESS)

Jun 24 21:35:16 vps-zap405560-1 systemd[1]: mergerfs.service: Service RestartSec=100ms expired, scheduling restart.
Jun 24 21:35:16 vps-zap405560-1 systemd[1]: mergerfs.service: Scheduled restart job, restart counter is at 5.
Jun 24 21:35:16 vps-zap405560-1 systemd[1]: Stopped MergerFS overlay writable storage and local mount.
Jun 24 21:35:16 vps-zap405560-1 systemd[1]: mergerfs.service: Start request repeated too quickly.
Jun 24 21:35:16 vps-zap405560-1 systemd[1]: mergerfs.service: Failed with result 'exit-code'.
Jun 24 21:35:16 vps-zap405560-1 systemd[1]: Failed to start MergerFS overlay writable storage and local mount.

**Comment by TechPerplexed** [comment]
Can you please try these commands one by one:

```
sudo systemctl daemon-reload
sudo systemctl stop mergerfs
sudo systemctl stop rclonefs
sudo systemctl start rclonefs
```

Don't go any further yet. please check if it shows your content in /mnt/rclone?

**Comment by bdschuster** [comment]
Also, out of curiosity, did you create the user you are currently using to login to your server manually? Or did you use root to install and created a user when prompted in Gooby?

**Comment by JustSquiddy** [comment]
/mnt/rclone is still empty… :/

**Comment by JustSquiddy** [comment]
I started the installation with root and created with gooby an account.

**Comment by TechPerplexed** [comment]
Did you try uninstalling Rclone from the menu and reinstalling it? Don't worry I'm sure we'll get to the bottom of this :)

**Comment by JustSquiddy** [comment]
yep, i tried, but there were some errors.
i‘m going to sleep now, i hope tomorrow we‘ll get that to work. thanks guys.

• •
|—————————————————|
________________________________
Von: Tech Perplexed <notifications@github.com>
Gesendet: Tuesday, June 25, 2019 12:06:22 AM
An: TechPerplexed/Gooby
Cc: JustSquiddy; Author
Betreff: Re: [TechPerplexed/Gooby] Plex can't read the "/Media" files (#88)


Did you try uninstalling Rclone from the menu and reinstalling it? Don't worry I'm sure we'll get to the bottom of this :)

**Comment by bdschuster** [comment]
Anyway we can get those errors? might help us in troubleshooting.

**Comment by JustSquiddy** [comment]
okay, i resetted the hole server and while mounting the Gdrive this comes up:
`cat: /var/local/.Gooby/plexclaim: No such file or directory
done
Created symlink /etc/systemd/system/default.target.wants/rclonefs.service -> /etc/systemd/system/rclonefs.service.
Created symlink /etc/systemd/system/unionfs.service.wants/rclonefs.service -> /etc/systemd/system/rclonefs.service.
Created symlink /etc/systemd/system/mergerfs.service.wants/rclonefs.service -> /etc/systemd/system/rclonefs.service.
Created symlink /etc/systemd/system/default.target.wants/mergerfs.service -> /etc/systemd/system/mergerfs.service.
Job for mergerfs.service failed because the control process exited with error code.
See "systemctl status mergerfs.service" and "journalctl -xe" for details.

Done!`

**Comment by JustSquiddy** [comment]
so with 

> mounting the Gdrive

i mean the "Confirm that this is what you named your mount" and "What is your media folder in Gdrive?" questions. after that, it seems to be a problem with mergerfs...
`sudo service mergerfs status` throws this error:
* mergerfs.service
   Loaded: not-found (Reason: No such file or directory)
   Active: failed (Result: exit-code) since Tue 2019-06-25 15:47:52 UTC; 24min ago

Jun 25 15:47:52 vps systemd[1]: mergerfs.service: Service hold-off time over, scheduling restart.
Jun 25 15:47:52 vps systemd[1]: mergerfs.service: Scheduled restart job, restart counter is at 5.
Jun 25 15:47:52 vps systemd[1]: Stopped MergerFS overlay writable storage and local mount.
Jun 25 15:47:52 vps systemd[1]: mergerfs.service: Start request repeated too quickly.
Jun 25 15:47:52 vps systemd[1]: mergerfs.service: Failed with result 'exit-code'.
Jun 25 15:47:52 vps systemd[1]: Failed to start MergerFS overlay writable storage and local mount.

**Comment by TechPerplexed** [comment]
Right, MergerFS is spitting out the error because it can't find the Rclone mount... but I'm puzzled why Rclone would fail for you!

What version of Ubuntu are you using? 

Let's try this:

```
cd ~
mkdir rclonetest
rclone mount Gdrive:Media rclonetest &
ls rclonetest
```

Do you see your media? Or if you are getting errors, what are they?

**Comment by JustSquiddy** [comment]
> What version of Ubuntu are you using?

18.04.2 LTS

`Command 'rclone' not found, but can be installed with: apt install rclone`
seems that rclone isn't installed. i went back to gooby and tried to update it, "isn't installed yet". after installation, Gdrive is already a remote and now i can use rclone again.
it gives that:
`2019/06/25 17:00:59 mount helper error: fusermount: fuse device not found, try 'modprobe fuse' first 2019/06/25 17:00:59 Fatal error: failed to mount FUSE fs: fusermount: exit status 1`

**Comment by bdschuster** [comment]
There's the million dollar error. It seems you need to contact your VPS provider and ask them to enable FUSE. I have had a few that do not enable by default, and some won't even enable it, but most will if you just send in a support ticket to enable, then all your problems should be fixed.

**Comment by JustSquiddy** [comment]
hi, i've just received the message, that fuse can't be enabled on my vps, not very cool but what should i do. i'll try it with another hoster...

**Comment by TechPerplexed** [comment]
Yay for @bdschuster for winning the million dollars, er I mean compliments (it's all I have to give, lol).

As for your FUSE problem... Yikes, yes, well if they won't enable it, you're out of luck. Out of curiosity, who is your provider?

**Comment by JustSquiddy** [comment]
> Out of curiosity, who is your provider?

zap-hosting.com
i'm going to try oneprovider, i think.

**Comment by JustSquiddy** [comment]
however, thanks guys for trying to help me

**Comment by bdschuster** [comment]
I have a dedicated physical server at 1&1, better for transcoding, but you don't need that if you don't have a lot of people transcoding. Do your research or message them prior to see if FUSE can be enabled.

**Comment by TechPerplexed** [comment]
Let us know if your new provider has solved the issue... in the meantime, I think we can close this as we've gone to the bottom of the problem at last :) Good luck with your new server!
