### ISSUE TITLE
Waiting on mounts to be created...

### ISSUE THREAD

**Issue by Ninazuu** [TechPerplexed/Gooby#90]
Hi there,

Having an issue today after I rebooted my server.  Plex would not access at all so I have searched around the issues here and tried a few things to try and fix based on others problems but I am still stuck.

It seems nothing is loading on restart at all.

I initially tried running the cleanup option but it gets stuck on the message Waiting for mounts to be created... and never stops.

If I try and update Plex it says not installed.  If I install Plex it comes back but even though rclone is installed the mount is not working and I cannot play any files.

Restarting the server again removes plex again.  It seems like gooby is not starting at all.  Everything is up to date.  I can still access gooby by typing gooby with my login.

Based on the questions you have asked in other threads:

I created my login through gooby.

My sudo visudo looks like this:

#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults        env_reset
Defaults        mail_badpass
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root    ALL=(ALL:ALL) ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d
myusername ALL=NOPASSWD: ALL

*myusername is actually my username here

The following commands you recommended to a different user do the following:

sudo systemctl stop gooby.service gooby-rclone.service gooby-find.service mnt-google.mount
Failed to stop gooby.service: Unit gooby.service not loaded.
Failed to stop gooby-rclone.service: Unit gooby-rclone.service not loaded.
Failed to stop gooby-find.service: Unit gooby-find.service not loaded.

sudo systemctl disable gooby.service gooby-rclone.service gooby-find.service mnt-google.mount
Failed to disable unit: Unit file gooby.service does not exist.

I am pretty much stuck now, I am hoping this can be recovered!

Thanks :)

**Comment by TechPerplexed** [comment]
It almost seems as if you have a very old version of Gooby installed... Can you try uninstalling Rclone from the menu and reinstalling it? You can use your old credentials again. Then run a system clean (option E-C) and see if your mount comes up?

**Comment by Ninazuu** [comment]
Hah, well I reinstalled Rclone and it did come back to life after the cleaner.

A strange issue, when I rebooted again to test it failed again but then the system restarted a second time and it all is working.  Not sure why something went wrong, I ran a clean about a week ago and all was fine until the reboot today.  Will hope it was a one off, thanks for the help!

**Comment by TechPerplexed** [comment]
Let's hope so :smile:  Sometimes these things just need a swift kick to get going :laughing:

**Comment by Ninazuu** [comment]
Just to come back to this, I just had to reinstall rclone again.  Any ideas why this is happening?

Thanks!

**Comment by bdschuster** [comment]
Was it after upgrading to the newest version of Gooby? Or doing a clean (which also upgrades)?

**Comment by Ninazuu** [comment]
So I ran a clean this morning and it worked fine all day until around an hour ago.

**Comment by Ninazuu** [comment]
Ok thanks :)
