### ISSUE TITLE
Sonarr failing to install, causing all other applications to fail

### ISSUE THREAD

**Issue by Ruta25** [TechPerplexed/Gooby#93]
When installing Sonarr, it is unable to install, and thereby causing all other installs to fail. Please see these screen shots: 
1) https://drive.google.com/file/d/1uP8TstzeBUzdhza6dcDLMA2YE6kmOBBR/view?usp=sharing

2) https://drive.google.com/file/d/1056khJMr8jreCf0PemZJHwrjx5pIU-E1/view?usp=sharing

I've tried to run system clean, but then everything goes down and does not work. Even Plex which was installed before Sonarr

**Comment by bdschuster** [comment]
Sorry about that...there was a mistype in the code for that image...it has been corrected. Please run a cleanup (Gooby menu > E > C) and try installing again.

**Comment by Ruta25** [comment]
Thank you! All working now :)

**Comment by bdschuster** [comment]
no worries! sorry for the issue.
