### ISSUE TITLE
Rclone not uploading

### ISSUE THREAD

**Issue by nesbcn** [TechPerplexed/Gooby#94]
Hi,

I've observed a worrying behavior that's been happening the last few days, it seems that rclone is not uploading anything to google Drive! This is what I get when I manually trigger uploading through gooby:

```
Starting sync at Mon 29 Jul 17:11:35 CEST 2019
/opt/Gooby/scripts/cron/syncmount.sh: line 37: jq: command not found
2019/07/29 17:11:35 Failed to rc: connection failed: Post http://localhost:5572/core/stats: dial tcp [::1]:5572: connect: connection refused
Queuing /XXXXX/YYYY (2019)/YYYY.ext of size 84K
2019/07/29 17:11:36 Failed to rc: connection failed: Post http://localhost:5572/operations/movefile: dial tcp [::1]:5572: connect: connection refused
/opt/Gooby/scripts/cron/syncmount.sh: line 37: jq: command not found
```

(filenames obfuscated btw)

I've run a few system cleanups, which also fail because then rclone doesn't want to re-mount when it finds files sitting in its folder...

Should I reinstall rclone? Will I lose everything? 

Thanks for your help!

P.s: some info regarding the server where gooby is installed

> OS version        : Ubuntu 18.04.2 LTS
>  Timezone          :
>  Domain            : 
>  Email Address
>  IP Address        : 
>  Media location    : /Media
>  Download location : /Media/Downloads
>  Gooby version     : 2.2.0

**Comment by bdschuster** [comment]
yes, please reinstall rclone...no, you will not lose anything. let us know.

**Comment by TechPerplexed** [comment]
It seems as if the command jq is not found. Can you please also run the command

`sudo apt-get install jq`

And try again?

**Comment by nesbcn** [comment]
Thanks for your prompt reply!
After installing jq I only get the 'connection refused' error messages. Will I lose stuff / databases if I reinstall rclone?

**Comment by TechPerplexed** [comment]
No you won't lose anything and you won't have to enter your credentials again either. Should be a two minute job 😊

**Comment by nesbcn** [comment]
After removing rclone and installing again, I get this:

```
Please follow the instructions to setup Rclone

2019/07/29 17:41:28 Failed to load config file "/home/XXXX/.config/rclone/rclone.conf": open /home/XXXX/.config/rclone/rclone.conf: permission denied

/opt/Gooby/install/apps/install-rclone.sh: line 55: /home/XXXX/.config/rclone/rclone.conf: Permission denied
Confirm that this is what you named your mount  driv
```

**Comment by TechPerplexed** [comment]
Ok, try this: 

`sudo chown -R $USER:$USER $HOME`

Then try to reinstall Rclone again?

**Comment by Ruta25** [comment]
I'm also having the same issue (not uploading to Gdrive), albeit not getting any errors

Are you sure you want to trigger upload (y/N)? 
--------------------------------------------------

 ---> 

This will manually trigger your uploads.
This process runs every 15 minutes regardless!

Starting sync at Mon Jul 29 13:50:13 EDT 2019
Queuing /XXXXXXXX/XXXXXXX.mp4 of size 1.6G
Finished at Mon Jul 29 13:50:13 EDT 2019
---------------------------------------------------

--------------------------------------------------
 trigger upload completed
--------------------------------------------------


--------------------------------------------------
 All done! Press Enter to return to the menu
---------------------------------------------

**Comment by bdschuster** [comment]
@Ruta25 so this just triggers the upload ..says finished, but that just means it sent it to the script to upload it..have you checked in gdrive after some time to see if it's actually there?  you can watch the actual upload once you trigger it by going to gooby menu, then F > C.

**Comment by Ruta25** [comment]
It starts, I check the actual upload, and then fails at 2% and gives this error:

jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)

**Comment by bdschuster** [comment]
are you both using Ubuntu? if so, what version?

**Comment by Ruta25** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

**Comment by Ruta25** [comment]
After restart, containers didn't start. So ran system cleanup and got these errors

Pulling nginx-proxy                       ... done
..lling letsencrypt-nginx-proxy-companion ... done
Pulling netdata                           ... done
..lling Organizr                          ... done
..lling plex                              ... done
Pulling deluge                            ... done
..lling radarr                            ... done
Pulling sonarr                            ... done
Creating network "docker_default" with the default driver
Creating nginx-proxy ... 
Creating deluge      ... 
Creating plex        ... error

Creating deluge      ... error
(2 matches found on name)
Creating nginx-proxy ... error
ERROR: for deluge  Cannot start service deluge: network docker_default is ambiguous (2 matches found on name)

ERROR: for nginx-proxy  Cannot start service nginx-proxy: network docker_default is ambiguous (2 matches found on name)

ERROR: for plex  Cannot start service plex: network docker_default is ambiguous (2 matches found on name)

ERROR: for deluge  Cannot start service deluge: network docker_default is ambiguous (2 matches found on name)

ERROR: for nginx-proxy  Cannot start service nginx-proxy: network docker_default is ambiguous (2 matches found on name)
ERROR: Encountered errors while bringing up the project.

Cleaning Docker leftovers

Error response from daemon: a prune operation is already running

**Comment by Ruta25** [comment]
Okay it seems like I fixed the problem. I rebooted the system, ran the system cleanup twice, and then triggered a manual upload and my file now shows on Gdrive (failed twice, but third time the upload went through)
Thank you for the help nonetheless :)

**Comment by TechPerplexed** [comment]
I blame it on gremlins, since we didn't change anything on you 😄 Glad it finally got sorted!

**Comment by TechPerplexed** [comment]
Oops sorry closed this too soon, let us know if you're got sorted too, @nesbcn

**Comment by nesbcn** [comment]
I was running some tests, it seems like everything works now as it should.
Thanks!

Missatge de Tech Perplexed <notifications@github.com> del dia dt., 30 de
jul. 2019 a les 0:06:

**Comment by Ruta25** [comment]
Sorry to open this again, but it seems that it is still happening. I let three files download, and only one of the three successfully uploaded to Gdrive. When I trigger a manual upload it gives these errors again: 
jq: error (at :1): Cannot iterate over null (null)
jq: error (at :1): Cannot iterate over null (null)
jq: error (at :1): Cannot iterate over null (null)
