### ISSUE TITLE
Gooby services not loading?

### ISSUE THREAD

**Issue by Ninazuu** [TechPerplexed/Gooby#96]
Hi there,

I have had my emby server running for about a month or so absolutely flawlessly, I changed a setting last night for Open Subtitles.  It got stuck and was non responsive whilst downloading so I stopped the download restarted my server and tried to perform a system clean.

This happens:

--------------------------------------------------
 This will cleanup system
--------------------------------------------------

--------------------------------------------------
 Are you sure you want to cleanup system (y/N)?
--------------------------------------------------

 --->

Giving your system a nice little spring cleaning...

Updating Gooby

Cloning into '/opt/.Gooby'...
remote: Enumerating objects: 123, done.
remote: Counting objects: 100% (123/123), done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 11013 (delta 83), reused 0 (delta 0), pack-reused 10890
Receiving objects: 100% (11013/11013), 1.93 MiB | 4.69 MiB/s, done.
Resolving deltas: 100% (7462/7462), done.

Shutting everything down

Removing network docker_default
WARNING: Network docker_default not found.

Updating Rclone if possible

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4426  100  4426    0     0  50295      0 --:--:-- --:--:-- --:--:-- 50295
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0    170      0 --:--:-- --:--:-- --:--:--   170

The latest version of rclone rclone v1.48.0 is already installed.

Cleaning mount leftovers

mountpoint: /mnt/google: No such file or directory

Calling on Upgrade Service

Your system has already been upgraded... prodeeding

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0    112      0 --:--:-- --:--:-- --:--:--   112
done

Then gets into a loop of waiting for a mount to be created.

I reinstalled rclone, my mount is showing in /mnt/rclone with the correct folders.

When I go to rclone activity I get the following:

2019/08/16 12:03:14 Failed to rc: connection failed: Post http://localhost:5572/core/stats: dial tcp [::1]:5572: connect: connection refused
2019/08/16 12:03:14 Failed to rc: connection failed: Post http://localhost:5572/job/list: dial tcp [::1]:5572: connect: connection refused

I am a bit confused, any help appreciated.

**Comment by Ninazuu** [comment]
Decided to reinstall everything so going to close.

**Comment by bdschuster** [comment]
Sorry, usually get back pretty quick, but it's been a busy day. Hopefully everything worked out for you.

**Comment by TechPerplexed** [comment]
Ditto! Apologies from me too... Let us know how it goes 😊
