### ISSUE TITLE
Origin Certificate

### ISSUE THREAD

**Issue by Ninazuu** [TechPerplexed/Gooby#97]
Hi there,

I followed your Origin Certificate guide for Emby, it had worked on a previous install, I am using Cloudflare also.

When I go through the process and try to add the certificate to Emby on the dashboard it is still listing an http://emby.**********.com:80 address and not the https one.  

I have tried removing the files using the "If you wish, you can delete the three files in your home folder: rm cert.pem, rm private.key and rm origin.pfx." commands, removing the certificate in Cloudflare and generating a new one and restarting the process but getting the same result.

Any ideas why it is not using https and port 2096, is like Emby is not recognising the certificate?

Thanks!

**Comment by bdschuster** [comment]
Sorry, this is @TechPerplexed 's domain...i don't use Emby, but she does :-) I'm sure she will reach out shortly.

**Comment by Ninazuu** [comment]
OK thanks, will wait for the expert!

Just as an additional info, the method in the guide worked fine for Ubuntu 16.04 but I am on 18.04.3 now and the same method does not seem to work.

**Comment by bdschuster** [comment]
Ubuntu has changed A LOT! And it keeps breaking stuff. Would you be willing to try Debian? Pretty much the same thing, but we have found it works much smoother and doesn't break with updates (as much).

**Comment by TechPerplexed** [comment]
Sorry again for the late reply! Pfft I'm slipping!

Ok, first things first, can you verify that the `origin.pfx` file can be found in `/var/local/Gooby/Emby`?

And second, in Emby itself, did you add the path `/config/origin.pfx` to `custom ssl path` plus the password you chose for your certificate?

**Comment by Ninazuu** [comment]
Hah, no worries at all, Gooby is so helpful that I am grateful for any help.

Yes to both questions, I also removed and redid everything and check again and still the same result.

I did have to use the sudo command to copy the file, the first time I just did as root so not sure if this is the issue?

**Comment by TechPerplexed** [comment]
If you want to try Debian, the Gooby backup should restore your system without any downtime... everything back in an hour :) But that might not be necessary.

You should definitely change your permissions first: `sudo chown -R $USER:$USER /var/local/Gooby/Emby`

If that doesn't allow Emby to recognize the certificate still, can you please share your settings in Emby in the "Advanced" section?

**Comment by Ninazuu** [comment]
Annnnnd, that fixed it straight away...!  Thanks so much!

Are my settings not correct for the login I use for Gooby?

**Comment by TechPerplexed** [comment]
If everything works correctly otherwise, I'm sure it was just a fluke. So glad that worked for you!
