### ISSUE TITLE
Submitting nzb files through NZBGet webui doesn't do anything

### ISSUE THREAD

**Issue by Ly-sAn** [TechPerplexed/Gooby#99]
Hi, I'm trying to add nzb files directly through NZBGet webui (nzbget.domain.com) but it doesn't do anything. The problem might come from nginx default `client_max_body_size` parameter which is too low but I'm unable to modify it as nginx is in a container.
Related: https://github.com/nzbget/nzbget/issues/521 & https://nzbget.net/behind-other-web-server

Thank you.

**Comment by Ly-sAn** [comment]
I've tried with 2 nzbs, one is 1,1 Mo and the other 2,2 Mo. Didn't work

**Comment by Ly-sAn** [comment]
It worked flawlessly! A huge thanks!

**Comment by mr-handerson** [comment]
I think perhaps there's been a regression here? It looks like the change was added, and then almost immediately removed.

Currently unable to add large NZBs via the webui

**Comment by bdschuster** [comment]
I did not put this in the new version as it was a 1 off since most people use sonarr or radarr to add their nzb files, or they connect their NZBGet to their indexer and their indexer sends it. Please see instructions above from me on how to correct, it will stay until there is a major release, that is the only time the 01-proxy files is updated, Sorry for any inconvenience.

**Comment by mr-handerson** [comment]
OK np. Yeah, it's a fringe usage case for sure. Most stuff can be added automatically via search from within the *arrs but occasionally search doesn't return the desired release. I've been able to modify the indexer search settings in some instances, and can add via URL in others, but occasionally the only way has been to manually grab the NZB and load it.

**Comment by TechPerplexed** [comment]
If for some reason we need to update the file again, we'll try to remember to post it here so you won't have to find out the hard way 😄
